/* arabic_mathematical_alphabetic_symbols.h – Unicode constants for U+1EE00 … U+1EEFF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Arabic_Mathematical_Alphabetic_Symbols
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1EE00.pdf
 
* Consistency Check:
* Total Defined Code Points: 143
* Total Significant Hex Values: 143
* Status: OK (Counts Match)

*/

#pragma once

#define UC_ALEF                                  0x1EE00 0  // 𞸀
#define UC_BEH                                   0x1EE01 0  // 𞸁
#define UC_JEEM                                  0x1EE02 0  // 𞸂
#define UC_DAL                                   0x1EE03 0  // 𞸃
#define UC_WAW                                   0x1EE05 0  // 𞸅
#define UC_ZAIN                                  0x1EE06 0  // 𞸆
#define UC_HAH                                   0x1EE07 0  // 𞸇
#define UC_TAH                                   0x1EE08 0  // 𞸈
#define UC_YEH                                   0x1EE09 0  // 𞸉
#define UC_KAF                                   0x1EE0A 0  // 𞸊
#define UC_LAM                                   0x1EE0B 0  // 𞸋
#define UC_MEEM                                  0x1EE0C 0  // 𞸌
#define UC_NOON                                  0x1EE0D 0  // 𞸍
#define UC_SEEN                                  0x1EE0E 0  // 𞸎
#define UC_ARABIC_MATHEMATICAL_AIN               0x1EE0F 0  // 𞸏
#define UC_FEH                                   0x1EE10 0  // 𞸐
#define UC_SAD                                   0x1EE11 0  // 𞸑
#define UC_QAF                                   0x1EE12 0  // 𞸒
#define UC_REH                                   0x1EE13 0  // 𞸓
#define UC_SHEEN                                 0x1EE14 0  // 𞸔
#define UC_TEH                                   0x1EE15 0  // 𞸕
#define UC_THEH                                  0x1EE16 0  // 𞸖
#define UC_KHAH                                  0x1EE17 0  // 𞸗
#define UC_THAL                                  0x1EE18 0  // 𞸘
#define UC_DAD                                   0x1EE19 0  // 𞸙
#define UC_ZAH                                   0x1EE1A 0  // 𞸚
#define UC_GHAIN                                 0x1EE1B 0  // 𞸛
#define UC_DOTLESS_BEH                           0x1EE1C 0  // 𞸜
#define UC_DOTLESS_NOON                          0x1EE1D 0  // 𞸝
#define UC_DOTLESS_FEH                           0x1EE1E 0  // 𞸞
#define UC_DOTLESS_QAF                           0x1EE1F 0  // 𞸟
#define UC_INITIAL_BEH                           0x1EE21 0  // 𞸡
#define UC_INITIAL_JEEM                          0x1EE22 0  // 𞸢
#define UC_INITIAL_HEH                           0x1EE24 0  // 𞸤
#define UC_INITIAL_HAH                           0x1EE27 0  // 𞸧
#define UC_INITIAL_YEH                           0x1EE29 0  // 𞸩
#define UC_INITIAL_KAF                           0x1EE2A 0  // 𞸪
#define UC_INITIAL_LAM                           0x1EE2B 0  // 𞸫
#define UC_INITIAL_MEEM                          0x1EE2C 0  // 𞸬
#define UC_INITIAL_NOON                          0x1EE2D 0  // 𞸭
#define UC_INITIAL_SEEN                          0x1EE2E 0  // 𞸮
#define UC_INITIAL_AIN                           0x1EE2F 0  // 𞸯
#define UC_INITIAL_FEH                           0x1EE30 0  // 𞸰
#define UC_INITIAL_SAD                           0x1EE31 0  // 𞸱
#define UC_INITIAL_QAF                           0x1EE32 0  // 𞸲
#define UC_INITIAL_SHEEN                         0x1EE34 0  // 𞸴
#define UC_INITIAL_TEH                           0x1EE35 0  // 𞸵
#define UC_INITIAL_THEH                          0x1EE36 0  // 𞸶
#define UC_INITIAL_KHAH                          0x1EE37 0  // 𞸷
#define UC_INITIAL_DAD                           0x1EE39 0  // 𞸹
#define UC_INITIAL_GHAIN                         0x1EE3B 0  // 𞸻
#define UC_TAILED_JEEM                           0x1EE42 0  // 𞹂
#define UC_TAILED_HAH                            0x1EE47 0  // 𞹇
#define UC_TAILED_YEH                            0x1EE49 0  // 𞹉
#define UC_TAILED_LAM                            0x1EE4B 0  // 𞹋
#define UC_TAILED_NOON                           0x1EE4D 0  // 𞹍
#define UC_TAILED_SEEN                           0x1EE4E 0  // 𞹎
#define UC_TAILED_AIN                            0x1EE4F 0  // 𞹏
#define UC_TAILED_SAD                            0x1EE51 0  // 𞹑
#define UC_TAILED_QAF                            0x1EE52 0  // 𞹒
#define UC_TAILED_SHEEN                          0x1EE54 0  // 𞹔
#define UC_TAILED_KHAH                           0x1EE57 0  // 𞹗
#define UC_TAILED_DAD                            0x1EE59 0  // 𞹙
#define UC_TAILED_GHAIN                          0x1EE5B 0  // 𞹛
#define UC_TAILED_DOTLESS_NOON                   0x1EE5D 0  // 𞹝
#define UC_TAILED_DOTLESS_QAF                    0x1EE5F 0  // 𞹟
#define UC_STRETCHED_BEH                         0x1EE61 0  // 𞹡
#define UC_STRETCHED_JEEM                        0x1EE62 0  // 𞹢
#define UC_STRETCHED_HEH                         0x1EE64 0  // 𞹤
#define UC_STRETCHED_HAH                         0x1EE67 0  // 𞹧
#define UC_STRETCHED_TAH                         0x1EE68 0  // 𞹨
#define UC_STRETCHED_YEH                         0x1EE69 0  // 𞹩
#define UC_STRETCHED_KAF                         0x1EE6A 0  // 𞹪
#define UC_STRETCHED_MEEM                        0x1EE6C 0  // 𞹬
#define UC_STRETCHED_NOON                        0x1EE6D 0  // 𞹭
#define UC_STRETCHED_SEEN                        0x1EE6E 0  // 𞹮
#define UC_STRETCHED_AIN                         0x1EE6F 0  // 𞹯
#define UC_STRETCHED_FEH                         0x1EE70 0  // 𞹰
#define UC_STRETCHED_SAD                         0x1EE71 0  // 𞹱
#define UC_STRETCHED_QAF                         0x1EE72 0  // 𞹲
#define UC_STRETCHED_SHEEN                       0x1EE74 0  // 𞹴
#define UC_STRETCHED_TEH                         0x1EE75 0  // 𞹵
#define UC_STRETCHED_THEH                        0x1EE76 0  // 𞹶
#define UC_STRETCHED_KHAH                        0x1EE77 0  // 𞹷
#define UC_STRETCHED_DAD                         0x1EE79 0  // 𞹹
#define UC_STRETCHED_ZAH                         0x1EE7A 0  // 𞹺
#define UC_STRETCHED_GHAIN                       0x1EE7B 0  // 𞹻
#define UC_STRETCHED_DOTLESS_BEH                 0x1EE7C 0  // 𞹼
#define UC_STRETCHED_DOTLESS_FEH                 0x1EE7E 0  // 𞹾
#define UC_LOOPED_ALEF                           0x1EE80 0  // 𞺀
#define UC_LOOPED_BEH                            0x1EE81 0  // 𞺁
#define UC_LOOPED_JEEM                           0x1EE82 0  // 𞺂
#define UC_LOOPED_DAL                            0x1EE83 0  // 𞺃
#define UC_LOOPED_HEH                            0x1EE84 0  // 𞺄
#define UC_LOOPED_WAW                            0x1EE85 0  // 𞺅
#define UC_LOOPED_ZAIN                           0x1EE86 0  // 𞺆
#define UC_LOOPED_HAH                            0x1EE87 0  // 𞺇
#define UC_LOOPED_TAH                            0x1EE88 0  // 𞺈
#define UC_LOOPED_YEH                            0x1EE89 0  // 𞺉
#define UC_LOOPED_LAM                            0x1EE8B 0  // 𞺋
#define UC_LOOPED_MEEM                           0x1EE8C 0  // 𞺌
#define UC_LOOPED_NOON                           0x1EE8D 0  // 𞺍
#define UC_LOOPED_SEEN                           0x1EE8E 0  // 𞺎
#define UC_LOOPED_AIN                            0x1EE8F 0  // 𞺏
#define UC_LOOPED_FEH                            0x1EE90 0  // 𞺐
#define UC_LOOPED_SAD                            0x1EE91 0  // 𞺑
#define UC_LOOPED_QAF                            0x1EE92 0  // 𞺒
#define UC_LOOPED_REH                            0x1EE93 0  // 𞺓
#define UC_LOOPED_SHEEN                          0x1EE94 0  // 𞺔
#define UC_LOOPED_TEH                            0x1EE95 0  // 𞺕
#define UC_LOOPED_THEH                           0x1EE96 0  // 𞺖
#define UC_LOOPED_KHAH                           0x1EE97 0  // 𞺗
#define UC_LOOPED_THAL                           0x1EE98 0  // 𞺘
#define UC_LOOPED_DAD                            0x1EE99 0  // 𞺙
#define UC_LOOPED_ZAH                            0x1EE9A 0  // 𞺚
#define UC_LOOPED_GHAIN                          0x1EE9B 0  // 𞺛
#define UC_DS_BEH                                0x1EEA1 0  // 𞺡
#define UC_DS_JEEM                               0x1EEA2 0  // 𞺢
#define UC_DS_DAL                                0x1EEA3 0  // 𞺣
#define UC_DS_WAW                                0x1EEA5 0  // 𞺥
#define UC_DS_ZAIN                               0x1EEA6 0  // 𞺦
#define UC_DS_HAH                                0x1EEA7 0  // 𞺧
#define UC_DS_TAH                                0x1EEA8 0  // 𞺨
#define UC_DS_YEH                                0x1EEA9 0  // 𞺩
#define UC_DS_LAM                                0x1EEAB 0  // 𞺫
#define UC_DS_MEEM                               0x1EEAC 0  // 𞺬
#define UC_DS_NOON                               0x1EEAD 0  // 𞺭
#define UC_DS_SEEN                               0x1EEAE 0  // 𞺮
#define UC_DS_AIN                                0x1EEAF 0  // 𞺯
#define UC_DS_FEH                                0x1EEB0 0  // 𞺰
#define UC_DS_SAD                                0x1EEB1 0  // 𞺱
#define UC_DS_QAF                                0x1EEB2 0  // 𞺲
#define UC_DS_REH                                0x1EEB3 0  // 𞺳
#define UC_DS_SHEEN                              0x1EEB4 0  // 𞺴
#define UC_DS_TEH                                0x1EEB5 0  // 𞺵
#define UC_DS_THEH                               0x1EEB6 0  // 𞺶
#define UC_DS_KHAH                               0x1EEB7 0  // 𞺷
#define UC_DS_THAL                               0x1EEB8 0  // 𞺸
#define UC_DS_DAD                                0x1EEB9 0  // 𞺹
#define UC_DS_ZAH                                0x1EEBA 0  // 𞺺
#define UC_DS_GHAIN                              0x1EEBB 0  // 𞺻
#define UC_OPERATOR_MEEM_HAH_TATWEEL             0x1EEF0 0  // 𞻰
#define UC_OPERATOR_HAH_DAL                      0x1EEF1 0  // 𞻱
