/* armenian.h – Unicode constants for U+0530 … U+058F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Armenian may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Armenian
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U0530.pdf
 
* Consistency Check:
* Total Defined Code Points: 91
* Total Significant Hex Values: 91
* Status: OK (Counts Match)

*/

#pragma once

#define UC_AM_ARMENIAN_MODIFIER_LEFT_HALF_RING   0x0559 0  // ՙ
#define UC_AM_ARMENIAN_APOSTROPHE                0x055A 0  // ՚
#define UC_AM_ARMENIAN_EMPHASIS_MARK             0x055B 0  // ՛
#define UC_AM_ARMENIAN_EXCLAMATION_MARK          0x055C 0  // ՜
#define UC_AM_ARMENIAN                           0x055D 0  // ՝
#define UC_AM_ARMENIAN_QUESTION_MARK             0x055E 0  // ՞
#define UC_AM_ARMENIAN_ABBREVIATION_MARK         0x055F 0  // ՟
#define UC_AM_ARMENIAN_SMALL_TURNED_AYB          0x0560 0  // ՠ
#define UC_AM_ARMENIAN_AYB                       0x0561 0x0531  // ա/Ա
#define UC_AM_ARMENIAN_BEN                       0x0562 0x0532  // բ/Բ
#define UC_AM_ARMENIAN_GIM                       0x0563 0x0533  // գ/Գ
#define UC_AM_ARMENIAN_DA                        0x0564 0x0534  // դ/Դ
#define UC_AM_ARMENIAN_ECH                       0x0565 0x0535  // ե/Ե
#define UC_AM_ARMENIAN_ZA                        0x0566 0x0536  // զ/Զ
#define UC_AM_ARMENIAN_EH                        0x0567 0x0537  // է/Է
#define UC_AM_ARMENIAN_ET                        0x0568 0x0538  // ը/Ը
#define UC_AM_ARMENIAN_TO                        0x0569 0x0539  // թ/Թ
#define UC_AM_ARMENIAN_ZHE                       0x056A 0x053A  // ժ/Ժ
#define UC_AM_ARMENIAN_INI                       0x056B 0x053B  // ի/Ի
#define UC_AM_ARMENIAN_LIWN                      0x056C 0x053C  // լ/Լ
#define UC_AM_ARMENIAN_XEH                       0x056D 0x053D  // խ/Խ
#define UC_AM_ARMENIAN_CA                        0x056E 0x053E  // ծ/Ծ
#define UC_AM_ARMENIAN_KEN                       0x056F 0x053F  // կ/Կ
#define UC_AM_ARMENIAN_HO                        0x0570 0x0540  // հ/Հ
#define UC_AM_ARMENIAN_JA                        0x0571 0x0541  // ձ/Ձ
#define UC_AM_ARMENIAN_GHAD                      0x0572 0x0542  // ղ/Ղ
#define UC_AM_ARMENIAN_CHEH                      0x0573 0x0543  // ճ/Ճ
#define UC_AM_ARMENIAN_MEN                       0x0574 0x0544  // մ/Մ
#define UC_AM_ARMENIAN_YI                        0x0575 0x0545  // յ/Յ
#define UC_AM_ARMENIAN_NOW                       0x0576 0x0546  // ն/Ն
#define UC_AM_ARMENIAN_SHA                       0x0577 0x0547  // շ/Շ
#define UC_AM_ARMENIAN_VO                        0x0578 0x0548  // ո/Ո
#define UC_AM_ARMENIAN_CHA                       0x0579 0x0549  // չ/Չ
#define UC_AM_ARMENIAN_PEH                       0x057A 0x054A  // պ/Պ
#define UC_AM_ARMENIAN_JHEH                      0x057B 0x054B  // ջ/Ջ
#define UC_AM_ARMENIAN_RA                        0x057C 0x054C  // ռ/Ռ
#define UC_AM_ARMENIAN_SEH                       0x057D 0x054D  // ս/Ս
#define UC_AM_ARMENIAN_VEW                       0x057E 0x054E  // վ/Վ
#define UC_AM_ARMENIAN_TIWN                      0x057F 0x054F  // տ/Տ
#define UC_AM_ARMENIAN_REH                       0x0580 0x0550  // ր/Ր
#define UC_AM_ARMENIAN_CO                        0x0581 0x0551  // ց/Ց
#define UC_AM_ARMENIAN_YIWN                      0x0582 0x0552  // ւ/Ւ
#define UC_AM_ARMENIAN_PIWR                      0x0583 0x0553  // փ/Փ
#define UC_AM_ARMENIAN_KEH                       0x0584 0x0554  // ք/Ք
#define UC_AM_ARMENIAN_OH                        0x0585 0x0555  // օ/Օ
#define UC_AM_ARMENIAN_FEH                       0x0586 0x0556  // ֆ/Ֆ
#define UC_AM_ARMENIAN_SMALL_LIGATURE_ECH_YIWN   0x0587 0  // և
#define UC_AM_ARMENIAN_SMALL_YI_STROKE           0x0588 0  // ֈ
#define UC_AM_ARMENIAN_FULL_STOP                 0x0589 0  // ։
#define UC_AM_ARMENIAN_HYPHEN                    0x058A 0  // ֊
#define UC_AM_RIGHT_FACING_ARMENIAN_ETERNITY_SIGN 0x058D 0  // ֍
#define UC_AM_LEFT_FACING_ARMENIAN_ETERNITY_SIGN 0x058E 0  // ֎
#define UC_AM_ARMENIAN_DRAM_SIGN                 0x058F 0  // ֏
