/* avestan.h – Unicode constants for U+10B00 … U+10B3F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Avestan
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U10B00.pdf
 
* Consistency Check:
* Total Defined Code Points: 61
* Total Significant Hex Values: 61
* Status: OK (Counts Match)

*/

#pragma once

#define UC_AVESTAN_A                             0x10B00 0  // 𐬀
#define UC_AVESTAN_AA                            0x10B01 0  // 𐬁
#define UC_AVESTAN_AO                            0x10B02 0  // 𐬂
#define UC_AVESTAN_AAO                           0x10B03 0  // 𐬃
#define UC_AVESTAN_AN                            0x10B04 0  // 𐬄
#define UC_AVESTAN_AAN                           0x10B05 0  // 𐬅
#define UC_AVESTAN_AE                            0x10B06 0  // 𐬆
#define UC_AVESTAN_AEE                           0x10B07 0  // 𐬇
#define UC_AVESTAN_E                             0x10B08 0  // 𐬈
#define UC_AVESTAN_EE                            0x10B09 0  // 𐬉
#define UC_AVESTAN_O                             0x10B0A 0  // 𐬊
#define UC_AVESTAN_OO                            0x10B0B 0  // 𐬋
#define UC_AVESTAN_I                             0x10B0C 0  // 𐬌
#define UC_AVESTAN_II                            0x10B0D 0  // 𐬍
#define UC_AVESTAN_U                             0x10B0E 0  // 𐬎
#define UC_AVESTAN_UU                            0x10B0F 0  // 𐬏
#define UC_AVESTAN_KE                            0x10B10 0  // 𐬐
#define UC_AVESTAN_XE                            0x10B11 0  // 𐬑
#define UC_AVESTAN_XYE                           0x10B12 0  // 𐬒
#define UC_AVESTAN_XVE                           0x10B13 0  // 𐬓
#define UC_AVESTAN_GE                            0x10B14 0  // 𐬔
#define UC_AVESTAN_GGE                           0x10B15 0  // 𐬕
#define UC_AVESTAN_GHE                           0x10B16 0  // 𐬖
#define UC_AVESTAN_CE                            0x10B17 0  // 𐬗
#define UC_AVESTAN_JE                            0x10B18 0  // 𐬘
#define UC_AVESTAN_TE                            0x10B19 0  // 𐬙
#define UC_AVESTAN_THE                           0x10B1A 0  // 𐬚
#define UC_AVESTAN_DE                            0x10B1B 0  // 𐬛
#define UC_AVESTAN_DHE                           0x10B1C 0  // 𐬜
#define UC_AVESTAN_TTE                           0x10B1D 0  // 𐬝
#define UC_AVESTAN_PE                            0x10B1E 0  // 𐬞
#define UC_AVESTAN_FE                            0x10B1F 0  // 𐬟
#define UC_AVESTAN_BE                            0x10B20 0  // 𐬠
#define UC_AVESTAN_BHE                           0x10B21 0  // 𐬡
#define UC_AVESTAN_NGE                           0x10B22 0  // 𐬢
#define UC_AVESTAN_NGYE                          0x10B23 0  // 𐬣
#define UC_AVESTAN_NGVE                          0x10B24 0  // 𐬤
#define UC_AVESTAN_NE                            0x10B25 0  // 𐬥
#define UC_AVESTAN_NYE                           0x10B26 0  // 𐬦
#define UC_AVESTAN_NNE                           0x10B27 0  // 𐬧
#define UC_AVESTAN_ME                            0x10B28 0  // 𐬨
#define UC_AVESTAN_HME                           0x10B29 0  // 𐬩
#define UC_AVESTAN_YYE                           0x10B2A 0  // 𐬪
#define UC_AVESTAN_YE                            0x10B2B 0  // 𐬫
#define UC_AVESTAN_VE                            0x10B2C 0  // 𐬬
#define UC_AVESTAN_RE                            0x10B2D 0  // 𐬭
#define UC_AVESTAN_LE                            0x10B2E 0  // 𐬮
#define UC_AVESTAN_SE                            0x10B2F 0  // 𐬯
#define UC_AVESTAN_ZE                            0x10B30 0  // 𐬰
#define UC_AVESTAN_SHE                           0x10B31 0  // 𐬱
#define UC_AVESTAN_ZHE                           0x10B32 0  // 𐬲
#define UC_AVESTAN_SHYE                          0x10B33 0  // 𐬳
#define UC_AVESTAN_SSHE                          0x10B34 0  // 𐬴
#define UC_AVESTAN_HE                            0x10B35 0  // 𐬵
#define UC_AVESTAN_ABBREVIATION_MARK             0x10B39 0  // 𐬹
#define UC_TINY_TWO_DOTS_OVER_ONE_DOT_PUNCTUATION 0x10B3A 0  // 𐬺
#define UC_SMALL_TWO_DOTS_OVER_ONE_DOT_PUNCTUATION 0x10B3B 0  // 𐬻
#define UC_LARGE_TWO_DOTS_OVER_ONE_DOT_PUNCTUATION 0x10B3C 0  // 𐬼
#define UC_LARGE_ONE_DOT_OVER_TWO_DOTS_PUNCTUATION 0x10B3D 0  // 𐬽
#define UC_LARGE_TWO_RINGS_OVER_ONE_RING_PUNCTUATION 0x10B3E 0  // 𐬾
#define UC_LARGE_ONE_RING_OVER_TWO_RINGS_PUNCTUATION 0x10B3F 0  // 𐬿
