/* basic_latin.h – Unicode constants for U+0000 … U+007F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Basic Latin may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Basic_Latin
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U0000.pdf
 
* Consistency Check:
* Total Defined Code Points: 128
* Total Significant Hex Values: 128
* Status: OK (Counts Match)

*/

#pragma once

#define UC_LA_NULL                               0x0000 0  /* U+0000 (NULL) */
#define UC_LA_SOH                                0x0001 0  /* U+0001 (SOH) */
#define UC_LA_STX                                0x0002 0  /* U+0002 (STX) */
#define UC_LA_ETX                                0x0003 0  /* U+0003 (ETX) */
#define UC_LA_EOT                                0x0004 0  /* U+0004 (EOT) */
#define UC_LA_ENQ                                0x0005 0  /* U+0005 (ENQ) */
#define UC_LA_ACK                                0x0006 0  /* U+0006 (ACK) */
#define UC_LA_BEL                                0x0007 0  /* U+0007 (BEL) */
#define UC_LA_BS                                 0x0008 0  /* U+0008 (BS) */
#define UC_LA_HT                                 0x0009 0  /* U+0009 (HT) */
#define UC_LA_LF                                 0x000A 0  /* U+000A (LF) */
#define UC_LA_VT                                 0x000B 0  /* U+000B (VT) */
#define UC_LA_FF                                 0x000C 0  /* U+000C (FF) */
#define UC_LA_CR                                 0x000D 0  /* U+000D (CR) */
#define UC_LA_SO                                 0x000E 0  /* U+000E (SO) */
#define UC_LA_SI                                 0x000F 0  /* U+000F (SI) */
#define UC_LA_DLE                                0x0010 0  /* U+0010 (DLE) */
#define UC_LA_DC1                                0x0011 0  /* U+0011 (DC1) */
#define UC_LA_DC2                                0x0012 0  /* U+0012 (DC2) */
#define UC_LA_DC3                                0x0013 0  /* U+0013 (DC3) */
#define UC_LA_DC4                                0x0014 0  /* U+0014 (DC4) */
#define UC_LA_NAK                                0x0015 0  /* U+0015 (NAK) */
#define UC_LA_SYN                                0x0016 0  /* U+0016 (SYN) */
#define UC_LA_ETB                                0x0017 0  /* U+0017 (ETB) */
#define UC_LA_CAN                                0x0018 0  /* U+0018 (CAN) */
#define UC_LA_EM                                 0x0019 0  /* U+0019 (EM) */
#define UC_LA_SUB                                0x001A 0  /* U+001A (SUB) */
#define UC_LA_ESC                                0x001B 0  /* U+001B (ESC) */
#define UC_LA_FS                                 0x001C 0  /* U+001C (FS) */
#define UC_LA_GS                                 0x001D 0  /* U+001D (GS) */
#define UC_LA_RS                                 0x001E 0  /* U+001E (RS) */
#define UC_LA_US                                 0x001F 0  /* U+001F (US) */
#define UC_LA_SPACE                              0x0020 0  //  
#define UC_LA_EXCLAMATION_MARK                   0x0021 0  // !
#define UC_LA_QUOTATION_MARK                     0x0022 0  // "
#define UC_LA_SIGN                               0x0023 0  // #
#define UC_LA_DOLLAR_SIGN                        0x0024 0  // $
#define UC_LA_PERCENT_SIGN                       0x0025 0  // %
#define UC_LA_AMPERSAND                          0x0026 0  // &
#define UC_LA_APOSTROPHE                         0x0027 0  // '
#define UC_LA_LEFT_PARENTHESIS                   0x0028 0  // (
#define UC_LA_RIGHT_PARENTHESIS                  0x0029 0  // )
#define UC_LA_ASTERISK                           0x002A 0  // *
#define UC_LA_PLUS_SIGN                          0x002B 0  // +
#define UC_LA_CHAR                               0x002C 0  // ,
#define UC_LA_HYPHEN_MINUS                       0x002D 0  // -
#define UC_LA_FULL_STOP                          0x002E 0  // .
#define UC_LA_SOLIDUS                            0x002F 0  // /
#define UC_LA_ZERO                               0x0030 0  // 0
#define UC_LA_ONE                                0x0031 0  // 1
#define UC_LA_TWO                                0x0032 0  // 2
#define UC_LA_THREE                              0x0033 0  // 3
#define UC_LA_FOUR                               0x0034 0  // 4
#define UC_LA_FIVE                               0x0035 0  // 5
#define UC_LA_SIX                                0x0036 0  // 6
#define UC_LA_SEVEN                              0x0037 0  // 7
#define UC_LA_EIGHT                              0x0038 0  // 8
#define UC_LA_NINE                               0x0039 0  // 9
#define UC_LA_COLON                              0x003A 0  // :
#define UC_LA_SEMICOLON                          0x003B 0  // ;
#define UC_LA_LESS_THAN_SIGN                     0x003C 0  // <
#define UC_LA_EQUALS_SIGN                        0x003D 0  // =
#define UC_LA_GREATER_THAN_SIGN                  0x003E 0  // >
#define UC_LA_QUESTION_MARK                      0x003F 0  // ?
#define UC_LA_COMMERCIAL_AT                      0x0040 0  // @
#define UC_LA_LEFT_SQUARE_BRACKET                0x005B 0  // [
#define UC_LA_REVERSE_SOLIDUS                    0x005C 0  // \
#define UC_LA_RIGHT_SQUARE_BRACKET               0x005D 0  // ]
#define UC_LA_CIRCUMFLEX_ACCENT                  0x005E 0  // ^
#define UC_LA_LOW_LINE                           0x005F 0  // _
#define UC_LA_GRAVE_ACCENT                       0x0060 0  // `
#define UC_LA_A                                  0x0061 0x0041  // a/A
#define UC_LA_B                                  0x0062 0x0042  // b/B
#define UC_LA_C                                  0x0063 0x0043  // c/C
#define UC_LA_D                                  0x0064 0x0044  // d/D
#define UC_LA_E                                  0x0065 0x0045  // e/E
#define UC_LA_F                                  0x0066 0x0046  // f/F
#define UC_LA_G                                  0x0067 0x0047  // g/G
#define UC_LA_H                                  0x0068 0x0048  // h/H
#define UC_LA_I                                  0x0069 0x0049  // i/I
#define UC_LA_J                                  0x006A 0x004A  // j/J
#define UC_LA_K                                  0x006B 0x004B  // k/K
#define UC_LA_L                                  0x006C 0x004C  // l/L
#define UC_LA_M                                  0x006D 0x004D  // m/M
#define UC_LA_N                                  0x006E 0x004E  // n/N
#define UC_LA_O                                  0x006F 0x004F  // o/O
#define UC_LA_P                                  0x0070 0x0050  // p/P
#define UC_LA_Q                                  0x0071 0x0051  // q/Q
#define UC_LA_R                                  0x0072 0x0052  // r/R
#define UC_LA_S                                  0x0073 0x0053  // s/S
#define UC_LA_T                                  0x0074 0x0054  // t/T
#define UC_LA_U                                  0x0075 0x0055  // u/U
#define UC_LA_V                                  0x0076 0x0056  // v/V
#define UC_LA_W                                  0x0077 0x0057  // w/W
#define UC_LA_X                                  0x0078 0x0058  // x/X
#define UC_LA_Y                                  0x0079 0x0059  // y/Y
#define UC_LA_Z                                  0x007A 0x005A  // z/Z
#define UC_LA_LEFT_CURLY_BRACKET                 0x007B 0  // {
#define UC_LA_VERTICAL_LINE                      0x007C 0  // |
#define UC_LA_RIGHT_CURLY_BRACKET                0x007D 0  // }
#define UC_LA_TILDE                              0x007E 0  // ~
#define UC_LA_DEL                                0x007F 0  /* U+007F (DEL) */
