/* bhaiksuki.h – Unicode constants for U+11C00 … U+11C6F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Bhaiksuki ( Sanskrit : भैक्षुकी, Bhaiksuki: 𑰥𑰹𑰎𑰿𑰬𑰲𑰎𑰱 ) is a
 * Brahmi-based script that was used around the 11th and 12th centuries
 * CE. It used to be known in English as the " Arrow-Headed Script " or "
 * Point-Headed Script, " while an older designation, " Sindhura, " had
 * been used in Tibet for at least three centuries. Records showing usage
 * of the script mainly appeared in the present-day states of Bihar and
 * West Bengal in India, and in regions of Bangladesh . Records have also
 * been located in Tibet, Nepal , and Burma .
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Bhaiksuki
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U11C00.pdf
 
* Consistency Check:
* Total Defined Code Points: 97
* Total Significant Hex Values: 97
* Status: OK (Counts Match)

*/

#pragma once

#define UC_BHAIKSUKI_A                           0x11C00 0  // 𑰀
#define UC_BHAIKSUKI_AA                          0x11C01 0  // 𑰁
#define UC_BHAIKSUKI_I                           0x11C02 0  // 𑰂
#define UC_BHAIKSUKI_II                          0x11C03 0  // 𑰃
#define UC_BHAIKSUKI_U                           0x11C04 0  // 𑰄
#define UC_BHAIKSUKI_UU                          0x11C05 0  // 𑰅
#define UC_BHAIKSUKI_VOCALIC_R                   0x11C06 0  // 𑰆
#define UC_BHAIKSUKI_VOCALIC_RR                  0x11C07 0  // 𑰇
#define UC_BHAIKSUKI_VOCALIC_L                   0x11C08 0  // 𑰈
#define UC_BHAIKSUKI_E                           0x11C0A 0  // 𑰊
#define UC_BHAIKSUKI_AI                          0x11C0B 0  // 𑰋
#define UC_BHAIKSUKI_O                           0x11C0C 0  // 𑰌
#define UC_BHAIKSUKI_AU                          0x11C0D 0  // 𑰍
#define UC_BHAIKSUKI_KA                          0x11C0E 0  // 𑰎
#define UC_BHAIKSUKI_KHA                         0x11C0F 0  // 𑰏
#define UC_BHAIKSUKI_GA                          0x11C10 0  // 𑰐
#define UC_BHAIKSUKI_GHA                         0x11C11 0  // 𑰑
#define UC_BHAIKSUKI_NGA                         0x11C12 0  // 𑰒
#define UC_BHAIKSUKI_CA                          0x11C13 0  // 𑰓
#define UC_BHAIKSUKI_CHA                         0x11C14 0  // 𑰔
#define UC_BHAIKSUKI_JA                          0x11C15 0  // 𑰕
#define UC_BHAIKSUKI_JHA                         0x11C16 0  // 𑰖
#define UC_BHAIKSUKI_NYA                         0x11C17 0  // 𑰗
#define UC_BHAIKSUKI_TTA                         0x11C18 0  // 𑰘
#define UC_BHAIKSUKI_TTHA                        0x11C19 0  // 𑰙
#define UC_BHAIKSUKI_DDA                         0x11C1A 0  // 𑰚
#define UC_BHAIKSUKI_DDHA                        0x11C1B 0  // 𑰛
#define UC_BHAIKSUKI_NNA                         0x11C1C 0  // 𑰜
#define UC_BHAIKSUKI_TA                          0x11C1D 0  // 𑰝
#define UC_BHAIKSUKI_THA                         0x11C1E 0  // 𑰞
#define UC_BHAIKSUKI_DA                          0x11C1F 0  // 𑰟
#define UC_BHAIKSUKI_DHA                         0x11C20 0  // 𑰠
#define UC_BHAIKSUKI_NA                          0x11C21 0  // 𑰡
#define UC_BHAIKSUKI_PA                          0x11C22 0  // 𑰢
#define UC_BHAIKSUKI_PHA                         0x11C23 0  // 𑰣
#define UC_BHAIKSUKI_BA                          0x11C24 0  // 𑰤
#define UC_BHAIKSUKI_BHA                         0x11C25 0  // 𑰥
#define UC_BHAIKSUKI_MA                          0x11C26 0  // 𑰦
#define UC_BHAIKSUKI_YA                          0x11C27 0  // 𑰧
#define UC_BHAIKSUKI_RA                          0x11C28 0  // 𑰨
#define UC_BHAIKSUKI_LA                          0x11C29 0  // 𑰩
#define UC_BHAIKSUKI_VA                          0x11C2A 0  // 𑰪
#define UC_BHAIKSUKI_SHA                         0x11C2B 0  // 𑰫
#define UC_BHAIKSUKI_SSA                         0x11C2C 0  // 𑰬
#define UC_BHAIKSUKI_SA                          0x11C2D 0  // 𑰭
#define UC_BHAIKSUKI_HA                          0x11C2E 0  // 𑰮
#define UC_BHAIKSUKI_VOWEL_SIGN_AA               0x11C2F 0  // 𑰯
#define UC_BHAIKSUKI_VOWEL_SIGN_I                0x11C30 0  // 𑰰
#define UC_BHAIKSUKI_VOWEL_SIGN_II               0x11C31 0  // 𑰱
#define UC_BHAIKSUKI_VOWEL_SIGN_U                0x11C32 0  // 𑰲
#define UC_BHAIKSUKI_VOWEL_SIGN_UU               0x11C33 0  // 𑰳
#define UC_BHAIKSUKI_VOWEL_SIGN_VOCALIC_R        0x11C34 0  // 𑰴
#define UC_BHAIKSUKI_VOWEL_SIGN_VOCALIC_RR       0x11C35 0  // 𑰵
#define UC_BHAIKSUKI_VOWEL_SIGN_VOCALIC_L        0x11C36 0  // 𑰶
#define UC_BHAIKSUKI_VOWEL_SIGN_E                0x11C38 0  // 𑰸
#define UC_BHAIKSUKI_VOWEL_SIGN_AI               0x11C39 0  // 𑰹
#define UC_BHAIKSUKI_VOWEL_SIGN_O                0x11C3A 0  // 𑰺
#define UC_BHAIKSUKI_VOWEL_SIGN_AU               0x11C3B 0  // 𑰻
#define UC_BHAIKSUKI_SIGN_CANDRABINDU            0x11C3C 0  // 𑰼
#define UC_BHAIKSUKI_SIGN_ANUSVARA               0x11C3D 0  // 𑰽
#define UC_BHAIKSUKI_SIGN_VISARGA                0x11C3E 0  // 𑰾
#define UC_BHAIKSUKI_SIGN_VIRAMA                 0x11C3F 0  // 𑰿
#define UC_BHAIKSUKI_SIGN_AVAGRAHA               0x11C40 0  // 𑱀
#define UC_BHAIKSUKI_DANDA                       0x11C41 0  // 𑱁
#define UC_BHAIKSUKI_DOUBLE_DANDA                0x11C42 0  // 𑱂
#define UC_BHAIKSUKI_WORD_SEPARATOR              0x11C43 0  // 𑱃
#define UC_BHAIKSUKI_GAP_FILLER_1                0x11C44 0  // 𑱄
#define UC_BHAIKSUKI_GAP_FILLER_2                0x11C45 0  // 𑱅
#define UC_BHAIKSUKI_ZERO                        0x11C50 0  // 𑱐
#define UC_BHAIKSUKI_ONE                         0x11C51 0  // 𑱑
#define UC_BHAIKSUKI_TWO                         0x11C52 0  // 𑱒
#define UC_BHAIKSUKI_THREE                       0x11C53 0  // 𑱓
#define UC_BHAIKSUKI_FOUR                        0x11C54 0  // 𑱔
#define UC_BHAIKSUKI_FIVE                        0x11C55 0  // 𑱕
#define UC_BHAIKSUKI_SIX                         0x11C56 0  // 𑱖
#define UC_BHAIKSUKI_SEVEN                       0x11C57 0  // 𑱗
#define UC_BHAIKSUKI_EIGHT                       0x11C58 0  // 𑱘
#define UC_BHAIKSUKI_NINE                        0x11C59 0  // 𑱙
#define UC_BHAIKSUKI_NUMBER_ONE                  0x11C5A 0  // 𑱚
#define UC_BHAIKSUKI_NUMBER_TWO                  0x11C5B 0  // 𑱛
#define UC_BHAIKSUKI_NUMBER_THREE                0x11C5C 0  // 𑱜
#define UC_BHAIKSUKI_NUMBER_FOUR                 0x11C5D 0  // 𑱝
#define UC_BHAIKSUKI_NUMBER_FIVE                 0x11C5E 0  // 𑱞
#define UC_BHAIKSUKI_NUMBER_SIX                  0x11C5F 0  // 𑱟
#define UC_BHAIKSUKI_NUMBER_SEVEN                0x11C60 0  // 𑱠
#define UC_BHAIKSUKI_NUMBER_EIGHT                0x11C61 0  // 𑱡
#define UC_BHAIKSUKI_NUMBER_NINE                 0x11C62 0  // 𑱢
#define UC_BHAIKSUKI_TEN                         0x11C63 0  // 𑱣
#define UC_BHAIKSUKI_TWENTY                      0x11C64 0  // 𑱤
#define UC_BHAIKSUKI_THIRTY                      0x11C65 0  // 𑱥
#define UC_BHAIKSUKI_FORTY                       0x11C66 0  // 𑱦
#define UC_BHAIKSUKI_FIFTY                       0x11C67 0  // 𑱧
#define UC_BHAIKSUKI_SIXTY                       0x11C68 0  // 𑱨
#define UC_BHAIKSUKI_SEVENTY                     0x11C69 0  // 𑱩
#define UC_BHAIKSUKI_EIGHTY                      0x11C6A 0  // 𑱪
#define UC_BHAIKSUKI_NINETY                      0x11C6B 0  // 𑱫
#define UC_BHAIKSUKI_HUNDREDS_UNIT_MARK          0x11C6C 0  // 𑱬
