/* bopomofo.h – Unicode constants for U+3100 … U+312F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Bopomofo
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U3100.pdf
 
* Consistency Check:
* Total Defined Code Points: 43
* Total Significant Hex Values: 43
* Status: OK (Counts Match)

*/

#pragma once

#define UC_BOPOMOFO_B                            0x3105 0  // ㄅ
#define UC_BOPOMOFO_P                            0x3106 0  // ㄆ
#define UC_BOPOMOFO_M                            0x3107 0  // ㄇ
#define UC_BOPOMOFO_F                            0x3108 0  // ㄈ
#define UC_BOPOMOFO_D                            0x3109 0  // ㄉ
#define UC_BOPOMOFO_T                            0x310A 0  // ㄊ
#define UC_BOPOMOFO_N                            0x310B 0  // ㄋ
#define UC_BOPOMOFO_L                            0x310C 0  // ㄌ
#define UC_BOPOMOFO_G                            0x310D 0  // ㄍ
#define UC_BOPOMOFO_K                            0x310E 0  // ㄎ
#define UC_BOPOMOFO_H                            0x310F 0  // ㄏ
#define UC_BOPOMOFO_J                            0x3110 0  // ㄐ
#define UC_BOPOMOFO_Q                            0x3111 0  // ㄑ
#define UC_BOPOMOFO_X                            0x3112 0  // ㄒ
#define UC_BOPOMOFO_ZH                           0x3113 0  // ㄓ
#define UC_BOPOMOFO_CH                           0x3114 0  // ㄔ
#define UC_BOPOMOFO_SH                           0x3115 0  // ㄕ
#define UC_BOPOMOFO_R                            0x3116 0  // ㄖ
#define UC_BOPOMOFO_Z                            0x3117 0  // ㄗ
#define UC_BOPOMOFO_C                            0x3118 0  // ㄘ
#define UC_BOPOMOFO_S                            0x3119 0  // ㄙ
#define UC_BOPOMOFO_A                            0x311A 0  // ㄚ
#define UC_BOPOMOFO_O                            0x311B 0  // ㄛ
#define UC_BOPOMOFO_E                            0x311C 0  // ㄜ
#define UC_BOPOMOFO_EH                           0x311D 0  // ㄝ
#define UC_BOPOMOFO_AI                           0x311E 0  // ㄞ
#define UC_BOPOMOFO_EI                           0x311F 0  // ㄟ
#define UC_BOPOMOFO_AU                           0x3120 0  // ㄠ
#define UC_BOPOMOFO_OU                           0x3121 0  // ㄡ
#define UC_BOPOMOFO_AN                           0x3122 0  // ㄢ
#define UC_BOPOMOFO_EN                           0x3123 0  // ㄣ
#define UC_BOPOMOFO_ANG                          0x3124 0  // ㄤ
#define UC_BOPOMOFO_ENG                          0x3125 0  // ㄥ
#define UC_BOPOMOFO_ER                           0x3126 0  // ㄦ
#define UC_BOPOMOFO_I                            0x3127 0  // ㄧ
#define UC_BOPOMOFO_U                            0x3128 0  // ㄨ
#define UC_BOPOMOFO_IU                           0x3129 0  // ㄩ
#define UC_BOPOMOFO_V                            0x312A 0  // ㄪ
#define UC_BOPOMOFO_NG                           0x312B 0  // ㄫ
#define UC_BOPOMOFO_GN                           0x312C 0  // ㄬ
#define UC_BOPOMOFO_IH                           0x312D 0  // ㄭ
#define UC_BOPOMOFO_O_DOT_ABOVE                  0x312E 0  // ㄮ
#define UC_BOPOMOFO_NN                           0x312F 0  // ㄯ
