/* buginese.h – Unicode constants for U+1A00 … U+1A1F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Buginese may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Buginese
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1A00.pdf
 
* Consistency Check:
* Total Defined Code Points: 30
* Total Significant Hex Values: 30
* Status: OK (Counts Match)

*/

#pragma once

#define UC_BUGINESE_KA                           0x1A00 0  // ᨀ
#define UC_BUGINESE_GA                           0x1A01 0  // ᨁ
#define UC_BUGINESE_NGA                          0x1A02 0  // ᨂ
#define UC_BUGINESE_NGKA                         0x1A03 0  // ᨃ
#define UC_BUGINESE_PA                           0x1A04 0  // ᨄ
#define UC_BUGINESE_BA                           0x1A05 0  // ᨅ
#define UC_BUGINESE_MA                           0x1A06 0  // ᨆ
#define UC_BUGINESE_MPA                          0x1A07 0  // ᨇ
#define UC_BUGINESE_TA                           0x1A08 0  // ᨈ
#define UC_BUGINESE_DA                           0x1A09 0  // ᨉ
#define UC_BUGINESE_NA                           0x1A0A 0  // ᨊ
#define UC_BUGINESE_NRA                          0x1A0B 0  // ᨋ
#define UC_BUGINESE_CA                           0x1A0C 0  // ᨌ
#define UC_BUGINESE_JA                           0x1A0D 0  // ᨍ
#define UC_BUGINESE_NYA                          0x1A0E 0  // ᨎ
#define UC_BUGINESE_NYCA                         0x1A0F 0  // ᨏ
#define UC_BUGINESE_YA                           0x1A10 0  // ᨐ
#define UC_BUGINESE_RA                           0x1A11 0  // ᨑ
#define UC_BUGINESE_LA                           0x1A12 0  // ᨒ
#define UC_BUGINESE_VA                           0x1A13 0  // ᨓ
#define UC_BUGINESE_SA                           0x1A14 0  // ᨔ
#define UC_BUGINESE_A                            0x1A15 0  // ᨕ
#define UC_BUGINESE_HA                           0x1A16 0  // ᨖ
#define UC_BUGINESE_VOWEL_SIGN_I                 0x1A17 0  // ᨗ
#define UC_BUGINESE_VOWEL_SIGN_U                 0x1A18 0  // ᨘ
#define UC_BUGINESE_VOWEL_SIGN_E                 0x1A19 0  // ᨙ
#define UC_BUGINESE_VOWEL_SIGN_O                 0x1A1A 0  // ᨚ
#define UC_BUGINESE_VOWEL_SIGN_AE                0x1A1B 0  // ᨛ
#define UC_BUGINESE_PALLAWA                      0x1A1E 0  // ᨞
#define UC_BUGINESE_END_OF_SECTION               0x1A1F 0  // ᨟
