/* carian.h – Unicode constants for U+102A0 … U+102DF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Carian may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Carian
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U102A0.pdf
 
* Consistency Check:
* Total Defined Code Points: 49
* Total Significant Hex Values: 49
* Status: OK (Counts Match)

*/

#pragma once

#define UC_CARIAN_A                              0x102A0 0  // 𐊠
#define UC_CARIAN_P2                             0x102A1 0  // 𐊡
#define UC_CARIAN_D                              0x102A2 0  // 𐊢
#define UC_CARIAN_L                              0x102A3 0  // 𐊣
#define UC_CARIAN_UUU                            0x102A4 0  // 𐊤
#define UC_CARIAN_R                              0x102A5 0  // 𐊥
#define UC_CARIAN_LD                             0x102A6 0  // 𐊦
#define UC_CARIAN_A2                             0x102A7 0  // 𐊧
#define UC_CARIAN_Q                              0x102A8 0  // 𐊨
#define UC_CARIAN_B                              0x102A9 0  // 𐊩
#define UC_CARIAN_M                              0x102AA 0  // 𐊪
#define UC_CARIAN_O                              0x102AB 0  // 𐊫
#define UC_CARIAN_D2                             0x102AC 0  // 𐊬
#define UC_CARIAN_T                              0x102AD 0  // 𐊭
#define UC_CARIAN_SH                             0x102AE 0  // 𐊮
#define UC_CARIAN_SH2                            0x102AF 0  // 𐊯
#define UC_CARIAN_S                              0x102B0 0  // 𐊰
#define UC_CARIAN_C_18                           0x102B1 0  // 𐊱
#define UC_CARIAN_U                              0x102B2 0  // 𐊲
#define UC_CARIAN_NN                             0x102B3 0  // 𐊳
#define UC_CARIAN_X                              0x102B4 0  // 𐊴
#define UC_CARIAN_N                              0x102B5 0  // 𐊵
#define UC_CARIAN_TT2                            0x102B6 0  // 𐊶
#define UC_CARIAN_P                              0x102B7 0  // 𐊷
#define UC_CARIAN_SS                             0x102B8 0  // 𐊸
#define UC_CARIAN_I                              0x102B9 0  // 𐊹
#define UC_CARIAN_E                              0x102BA 0  // 𐊺
#define UC_CARIAN_UUUU                           0x102BB 0  // 𐊻
#define UC_CARIAN_K                              0x102BC 0  // 𐊼
#define UC_CARIAN_K2                             0x102BD 0  // 𐊽
#define UC_CARIAN_ND                             0x102BE 0  // 𐊾
#define UC_CARIAN_UU                             0x102BF 0  // 𐊿
#define UC_CARIAN_G                              0x102C0 0  // 𐋀
#define UC_CARIAN_G2                             0x102C1 0  // 𐋁
#define UC_CARIAN_ST                             0x102C2 0  // 𐋂
#define UC_CARIAN_ST2                            0x102C3 0  // 𐋃
#define UC_CARIAN_NG                             0x102C4 0  // 𐋄
#define UC_CARIAN_II                             0x102C5 0  // 𐋅
#define UC_CARIAN_C_39                           0x102C6 0  // 𐋆
#define UC_CARIAN_TT                             0x102C7 0  // 𐋇
#define UC_CARIAN_UUU2                           0x102C8 0  // 𐋈
#define UC_CARIAN_RR                             0x102C9 0  // 𐋉
#define UC_CARIAN_MB                             0x102CA 0  // 𐋊
#define UC_CARIAN_MB2                            0x102CB 0  // 𐋋
#define UC_CARIAN_MB3                            0x102CC 0  // 𐋌
#define UC_CARIAN_MB4                            0x102CD 0  // 𐋍
#define UC_CARIAN_LD2                            0x102CE 0  // 𐋎
#define UC_CARIAN_E2                             0x102CF 0  // 𐋏
#define UC_CARIAN_UUU3                           0x102D0 0  // 𐋐
