/* control_pictures.h – Unicode constants for U+2400 … U+243F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Control Pictures is a Unicode block containing characters for
 * graphically representing the C0 control codes , and other control
 * characters. Its block name in Unicode 1.0 was Pictures for Control
 * Codes .
 * Code points U+0000 NULL to U+0020 SPACE can be mapped onto their
 * corresponding control picture by incrementing the code point by
 * 0x2400. For example, the corresponding control picture for U+000A LINE
 * FEED is 0x000A + 0x2400 = 0x240A (␊).
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Control_Pictures
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U2400.pdf
 
* Consistency Check:
* Total Defined Code Points: 42
* Total Significant Hex Values: 42
* Status: OK (Counts Match)

*/

#pragma once

#define UC_FOR_NULL                              0x2400 0  // ␀
#define UC_FOR_START_OF_HEADING                  0x2401 0  // ␁
#define UC_FOR_START_OF_TEXT                     0x2402 0  // ␂
#define UC_FOR_END_OF_TEXT                       0x2403 0  // ␃
#define UC_FOR_END_OF_TRANSMISSION               0x2404 0  // ␄
#define UC_FOR_ENQUIRY                           0x2405 0  // ␅
#define UC_FOR_ACKNOWLEDGE                       0x2406 0  // ␆
#define UC_FOR_BELL                              0x2407 0  // ␇
#define UC_FOR_BACKSPACE                         0x2408 0  // ␈
#define UC_FOR_HORIZONTAL_TABULATION             0x2409 0  // ␉
#define UC_FOR_LINE_FEED                         0x240A 0  // ␊
#define UC_FOR_VERTICAL_TABULATION               0x240B 0  // ␋
#define UC_FOR_FORM_FEED                         0x240C 0  // ␌
#define UC_FOR_CARRIAGE_RETURN                   0x240D 0  // ␍
#define UC_FOR_SHIFT_OUT                         0x240E 0  // ␎
#define UC_FOR_SHIFT_IN                          0x240F 0  // ␏
#define UC_FOR_DATA_LINK_ESCAPE                  0x2410 0  // ␐
#define UC_FOR_DEVICE_CONTROL_ONE                0x2411 0  // ␑
#define UC_FOR_DEVICE_CONTROL_TWO                0x2412 0  // ␒
#define UC_FOR_DEVICE_CONTROL_THREE              0x2413 0  // ␓
#define UC_FOR_DEVICE_CONTROL_FOUR               0x2414 0  // ␔
#define UC_FOR_NEGATIVE_ACKNOWLEDGE              0x2415 0  // ␕
#define UC_FOR_SYNCHRONOUS_IDLE                  0x2416 0  // ␖
#define UC_FOR_END_OF_TRANSMISSION_BLOCK         0x2417 0  // ␗
#define UC_FOR_CANCEL                            0x2418 0  // ␘
#define UC_FOR_END_OF_MEDIUM                     0x2419 0  // ␙
#define UC_FOR_SUBSTITUTE                        0x241A 0  // ␚
#define UC_FOR_ESCAPE                            0x241B 0  // ␛
#define UC_FOR_FILE_SEPARATOR                    0x241C 0  // ␜
#define UC_FOR_GROUP_SEPARATOR                   0x241D 0  // ␝
#define UC_FOR_RECORD_SEPARATOR                  0x241E 0  // ␞
#define UC_FOR_UNIT_SEPARATOR                    0x241F 0  // ␟
#define UC_FOR_SPACE                             0x2420 0  // ␠
#define UC_FOR_DELETE                            0x2421 0  // ␡
#define UC_BLANK                                 0x2422 0  // ␢
#define UC_OPEN_BOX                              0x2423 0  // ␣
#define UC_FOR_NEWLINE                           0x2424 0  // ␤
#define UC_FOR_DELETE_FORM_TWO                   0x2425 0  // ␥
#define UC_FOR_SUBSTITUTE_FORM_TWO               0x2426 0  // ␦
#define UC_FOR_DELETE_SQUARE_CHECKER_BOARD_FORM  0x2427 0  // ␧
#define UC_FOR_DELETE_RECTANGULAR_CHECKER_BOARD_FORM 0x2428 0  // ␨
#define UC_FOR_DELETE_MEDIUM_SHADE_FORM          0x2429 0  // ␩
