/* coptic.h – Unicode constants for U+2C80 … U+2CFF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Coptic may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Coptic
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U2C80.pdf
 
* Consistency Check:
* Total Defined Code Points: 123
* Total Significant Hex Values: 123
* Status: OK (Counts Match)

*/

#pragma once

#define UC_ALFA                                  0x2C81 0x2C80  // ⲁ/Ⲁ
#define UC_VIDA                                  0x2C83 0x2C82  // ⲃ/Ⲃ
#define UC_COPTIC_SMALL_LETTER_GAMMA             0x2C85 0x2C84  // ⲅ/Ⲅ
#define UC_DALDA                                 0x2C87 0x2C86  // ⲇ/Ⲇ
#define UC_EIE                                   0x2C89 0x2C88  // ⲉ/Ⲉ
#define UC_SOU                                   0x2C8B 0x2C8A  // ⲋ/Ⲋ
#define UC_ZATA                                  0x2C8D 0x2C8C  // ⲍ/Ⲍ
#define UC_HATE                                  0x2C8F 0x2C8E  // ⲏ/Ⲏ
#define UC_THETHE                                0x2C91 0x2C90  // ⲑ/Ⲑ
#define UC_IAUDA                                 0x2C93 0x2C92  // ⲓ/Ⲓ
#define UC_KAPA                                  0x2C95 0x2C94  // ⲕ/Ⲕ
#define UC_LAULA                                 0x2C97 0x2C96  // ⲗ/Ⲗ
#define UC_MI                                    0x2C99 0x2C98  // ⲙ/Ⲙ
#define UC_NI                                    0x2C9B 0x2C9A  // ⲛ/Ⲛ
#define UC_KSI                                   0x2C9D 0x2C9C  // ⲝ/Ⲝ
#define UC_O                                     0x2C9F 0x2C9E  // ⲟ/Ⲟ
#define UC_PI                                    0x2CA1 0x2CA0  // ⲡ/Ⲡ
#define UC_RO                                    0x2CA3 0x2CA2  // ⲣ/Ⲣ
#define UC_SIMA                                  0x2CA5 0x2CA4  // ⲥ/Ⲥ
#define UC_TAU                                   0x2CA7 0x2CA6  // ⲧ/Ⲧ
#define UC_UA                                    0x2CA9 0x2CA8  // ⲩ/Ⲩ
#define UC_FI                                    0x2CAB 0x2CAA  // ⲫ/Ⲫ
#define UC_KHI                                   0x2CAD 0x2CAC  // ⲭ/Ⲭ
#define UC_PSI                                   0x2CAF 0x2CAE  // ⲯ/Ⲯ
#define UC_OOU                                   0x2CB1 0x2CB0  // ⲱ/Ⲱ
#define UC_DIALECT_P_ALEF                        0x2CB3 0x2CB2  // ⲳ/Ⲳ
#define UC_OLD_AIN                               0x2CB5 0x2CB4  // ⲵ/Ⲵ
#define UC_CRYPTOGRAMMIC_EIE                     0x2CB7 0x2CB6  // ⲷ/Ⲷ
#define UC_DIALECT_P_KAPA                        0x2CB9 0x2CB8  // ⲹ/Ⲹ
#define UC_DIALECT_P_NI                          0x2CBB 0x2CBA  // ⲻ/Ⲻ
#define UC_CRYPTOGRAMMIC_NI                      0x2CBD 0x2CBC  // ⲽ/Ⲽ
#define UC_OLD_OOU                               0x2CBF 0x2CBE  // ⲿ/Ⲿ
#define UC_SAMPI                                 0x2CC1 0x2CC0  // ⳁ/Ⳁ
#define UC_CROSSED_SHEI                          0x2CC3 0x2CC2  // ⳃ/Ⳃ
#define UC_OLD_SHEI                              0x2CC5 0x2CC4  // ⳅ/Ⳅ
#define UC_OLD_ESH                               0x2CC7 0x2CC6  // ⳇ/Ⳇ
#define UC_AKHMIMIC_KHEI                         0x2CC9 0x2CC8  // ⳉ/Ⳉ
#define UC_DIALECT_P_HORI                        0x2CCB 0x2CCA  // ⳋ/Ⳋ
#define UC_OLD_HORI                              0x2CCD 0x2CCC  // ⳍ/Ⳍ
#define UC_OLD_HA                                0x2CCF 0x2CCE  // ⳏ/Ⳏ
#define UC_L_SHAPED_HA                           0x2CD1 0x2CD0  // ⳑ/Ⳑ
#define UC_OLD_HEI                               0x2CD3 0x2CD2  // ⳓ/Ⳓ
#define UC_OLD_HAT                               0x2CD5 0x2CD4  // ⳕ/Ⳕ
#define UC_OLD_GANGIA                            0x2CD7 0x2CD6  // ⳗ/Ⳗ
#define UC_OLD_DJA                               0x2CD9 0x2CD8  // ⳙ/Ⳙ
#define UC_OLD_SHIMA                             0x2CDB 0x2CDA  // ⳛ/Ⳛ
#define UC_OLD_NUBIAN_SHIMA                      0x2CDD 0x2CDC  // ⳝ/Ⳝ
#define UC_OLD_NUBIAN_NGI                        0x2CDF 0x2CDE  // ⳟ/Ⳟ
#define UC_OLD_NUBIAN_NYI                        0x2CE1 0x2CE0  // ⳡ/Ⳡ
#define UC_OLD_NUBIAN_WAU                        0x2CE3 0x2CE2  // ⳣ/Ⳣ
#define UC_KAI                                   0x2CE4 0  // ⳤ
#define UC_MI_RO                                 0x2CE5 0  // ⳥
#define UC_PI_RO                                 0x2CE6 0  // ⳦
#define UC_STAUROS                               0x2CE7 0  // ⳧
#define UC_TAU_RO                                0x2CE8 0  // ⳨
#define UC_KHI_RO                                0x2CE9 0  // ⳩
#define UC_SHIMA_SIMA                            0x2CEA 0  // ⳪
#define UC_CRYPTOGRAMMIC_SHEI                    0x2CEC 0x2CEB  // ⳬ/Ⳬ
#define UC_CRYPTOGRAMMIC_GANGIA                  0x2CEE 0x2CED  // ⳮ/Ⳮ
#define UC_COMBINING_NI_ABOVE                    0x2CEF 0  // ⳯
#define UC_COMBINING_SPIRITUS_ASPER              0x2CF0 0  // ⳰
#define UC_COMBINING_SPIRITUS_LENIS              0x2CF1 0  // ⳱
#define UC_BOHAIRIC_KHEI                         0x2CF3 0x2CF2  // ⳳ/Ⳳ
#define UC_OLD_NUBIAN_FULL_STOP                  0x2CF9 0  // ⳹
#define UC_OLD_NUBIAN_DIRECT_QUESTION_MARK       0x2CFA 0  // ⳺
#define UC_OLD_NUBIAN_INDIRECT_QUESTION_MARK     0x2CFB 0  // ⳻
#define UC_OLD_NUBIAN_VERSE_DIVIDER              0x2CFC 0  // ⳼
#define UC_FRACTION_ONE_HALF                     0x2CFD 0  // ⳽
#define UC_FULL_STOP                             0x2CFE 0  // ⳾
#define UC_MORPHOLOGICAL_DIVIDER                 0x2CFF 0  // ⳿
