/* enclosed_ideographic_supplement.h – Unicode constants for U+1F200 … U+1F2FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Enclosed Ideographic Supplement is a Unicode block containing forms of
 * characters and words from Chinese, Japanese and Korean enclosed within
 * or stylised as squares, brackets, or circles. It contains three such
 * characters containing one or more kana , and many containing CJK
 * ideographs . Many of its characters were added for compatibility with
 * the Japanese ARIB STD-B24 standard. Six symbols from Chinese folk
 * religion were added in Unicode version 10.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Enclosed_Ideographic_Supplement
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1F200.pdf
 
* Consistency Check:
* Total Defined Code Points: 64
* Total Significant Hex Values: 64
* Status: OK (Counts Match)

*/

#pragma once

#define UC_SQUARE_HIRAGANA_HOKA                  0x1F200 0  // 🈀
#define UC_SQUARED_KATAKANA_KOKO                 0x1F201 0  // 🈁
#define UC_SQUARED_KATAKANA_SA                   0x1F202 0  // 🈂
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_624B    0x1F210 0  // 🈐
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_5B57    0x1F211 0  // 🈑
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_53CC    0x1F212 0  // 🈒
#define UC_SQUARED_KATAKANA_DE                   0x1F213 0  // 🈓
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_4E8C    0x1F214 0  // 🈔
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_591A    0x1F215 0  // 🈕
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_89E3    0x1F216 0  // 🈖
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_5929    0x1F217 0  // 🈗
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_4EA4    0x1F218 0  // 🈘
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6620    0x1F219 0  // 🈙
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_7121    0x1F21A 0  // 🈚
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6599    0x1F21B 0  // 🈛
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_524D    0x1F21C 0  // 🈜
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_5F8C    0x1F21D 0  // 🈝
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_518D    0x1F21E 0  // 🈞
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_65B0    0x1F21F 0  // 🈟
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_521D    0x1F220 0  // 🈠
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_7D42    0x1F221 0  // 🈡
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_751F    0x1F222 0  // 🈢
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_8CA9    0x1F223 0  // 🈣
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_58F0    0x1F224 0  // 🈤
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_5439    0x1F225 0  // 🈥
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6F14    0x1F226 0  // 🈦
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6295    0x1F227 0  // 🈧
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6355    0x1F228 0  // 🈨
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_4E00    0x1F229 0  // 🈩
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_4E09    0x1F22A 0  // 🈪
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_904A    0x1F22B 0  // 🈫
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_5DE6    0x1F22C 0  // 🈬
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_4E2D    0x1F22D 0  // 🈭
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_53F3    0x1F22E 0  // 🈮
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6307    0x1F22F 0  // 🈯
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_8D70    0x1F230 0  // 🈰
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6253    0x1F231 0  // 🈱
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_7981    0x1F232 0  // 🈲
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_7A7A    0x1F233 0  // 🈳
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_5408    0x1F234 0  // 🈴
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6E80    0x1F235 0  // 🈵
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6709    0x1F236 0  // 🈶
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_6708    0x1F237 0  // 🈷
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_7533    0x1F238 0  // 🈸
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_5272    0x1F239 0  // 🈹
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_55B6    0x1F23A 0  // 🈺
#define UC_SQUARED_CJK_UNIFIED_IDEOGRAPH_914D    0x1F23B 0  // 🈻
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_672C 0x1F240 0  // 🉀
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_4E09 0x1F241 0  // 🉁
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_4E8C 0x1F242 0  // 🉂
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_5B89 0x1F243 0  // 🉃
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_70B9 0x1F244 0  // 🉄
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_6253 0x1F245 0  // 🉅
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_76D7 0x1F246 0  // 🉆
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_52DD 0x1F247 0  // 🉇
#define UC_TORTOISE_SHELL_BRACKETED_CJK_UNIFIED_IDEOGRAPH_6557 0x1F248 0  // 🉈
#define UC_C_IDEOGRAPH_ADVANTAGE                 0x1F250 0  // 🉐
#define UC_C_IDEOGRAPH_ACCEPT                    0x1F251 0  // 🉑
#define UC_ROUNDED_FOR_FU                        0x1F260 0  // 🉠
#define UC_ROUNDED_FOR_LU                        0x1F261 0  // 🉡
#define UC_ROUNDED_FOR_SHOU                      0x1F262 0  // 🉢
#define UC_ROUNDED_FOR_XI                        0x1F263 0  // 🉣
#define UC_ROUNDED_FOR_SHUANGXI                  0x1F264 0  // 🉤
#define UC_ROUNDED_FOR_CAI                       0x1F265 0  // 🉥
