/* enclosed_alphanumeric_supplement.h – Unicode constants for U+1F100 … U+1F1FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Enclosed Alphanumeric Supplement is a Unicode block consisting of
 * Latin alphabet characters and Arabic numerals enclosed in circles,
 * ovals or boxes, used for a variety of purposes. It is encoded in the
 * range U+1F100–U+1F1FF in the Supplementary Multilingual Plane .
 * The block is mostly an extension of the Enclosed Alphanumerics block,
 * containing further enclosed alphanumeric characters which are not
 * included in that block or Enclosed CJK Letters and Months . Most of
 * the characters are single alphanumerics in boxes or circles, or with
 * trailing commas. Two of the symbols are identified as dingbats . A
 * number of multiple-letter enclosed abbreviations are also included,
 * mostly to provide compatibility with Broadcast Markup Language
 * standards (see ARIB STD B24 character set ) and Japanese
 * telecommunications networks' emoji sets. The block also includes the
 * regional indicator symbols to be used for emoji country flag support.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Enclosed_Alphanumeric_Supplement
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1F100.pdf
 
* Consistency Check:
* Total Defined Code Points: 200
* Total Significant Hex Values: 200
* Status: OK (Counts Match)

*/

#pragma once

#define UC_ZERO_FULL_STOP                        0x1F100 0  // 🄀
#define UC_ZERO                                  0x1F101 0  // 🄁
#define UC_ONE                                   0x1F102 0  // 🄂
#define UC_TWO                                   0x1F103 0  // 🄃
#define UC_THREE                                 0x1F104 0  // 🄄
#define UC_FOUR                                  0x1F105 0  // 🄅
#define UC_FIVE                                  0x1F106 0  // 🄆
#define UC_SIX                                   0x1F107 0  // 🄇
#define UC_SEVEN                                 0x1F108 0  // 🄈
#define UC_EIGHT                                 0x1F109 0  // 🄉
#define UC_NINE                                  0x1F10A 0  // 🄊
#define UC_DINGBAT_C_SS_ZERO                     0x1F10B 0  // 🄋
#define UC_DINGBAT_NEGATIVE_C_SS_ZERO            0x1F10C 0  // 🄌
#define UC_C_ZERO_SLASH                          0x1F10D 0  // 🄍
#define UC_C_ANTICLOCKWISE_ARROW                 0x1F10E 0  // 🄎
#define UC_C_DOLLAR_SIGN_OVERLAID_BACKSLASH      0x1F10F 0  // 🄏
#define UC_P_CAPITAL_A                           0x1F110 0  // 🄐
#define UC_P_CAPITAL_B                           0x1F111 0  // 🄑
#define UC_P_CAPITAL_C                           0x1F112 0  // 🄒
#define UC_P_CAPITAL_D                           0x1F113 0  // 🄓
#define UC_P_CAPITAL_E                           0x1F114 0  // 🄔
#define UC_P_CAPITAL_F                           0x1F115 0  // 🄕
#define UC_P_CAPITAL_G                           0x1F116 0  // 🄖
#define UC_P_CAPITAL_H                           0x1F117 0  // 🄗
#define UC_P_CAPITAL_I                           0x1F118 0  // 🄘
#define UC_P_CAPITAL_J                           0x1F119 0  // 🄙
#define UC_P_CAPITAL_K                           0x1F11A 0  // 🄚
#define UC_P_CAPITAL_L                           0x1F11B 0  // 🄛
#define UC_P_CAPITAL_M                           0x1F11C 0  // 🄜
#define UC_P_CAPITAL_N                           0x1F11D 0  // 🄝
#define UC_P_CAPITAL_O                           0x1F11E 0  // 🄞
#define UC_P_CAPITAL_P                           0x1F11F 0  // 🄟
#define UC_P_CAPITAL_Q                           0x1F120 0  // 🄠
#define UC_P_CAPITAL_R                           0x1F121 0  // 🄡
#define UC_P_CAPITAL_S                           0x1F122 0  // 🄢
#define UC_P_CAPITAL_T                           0x1F123 0  // 🄣
#define UC_P_CAPITAL_U                           0x1F124 0  // 🄤
#define UC_P_CAPITAL_V                           0x1F125 0  // 🄥
#define UC_P_CAPITAL_W                           0x1F126 0  // 🄦
#define UC_P_CAPITAL_X                           0x1F127 0  // 🄧
#define UC_P_CAPITAL_Y                           0x1F128 0  // 🄨
#define UC_P_CAPITAL_Z                           0x1F129 0  // 🄩
#define UC_TORTOISE_SHELL_BRACKETED_CAPITAL_S    0x1F12A 0  // 🄪
#define UC_C_IT_CAPITAL_C                        0x1F12B 0  // 🄫
#define UC_C_IT_CAPITAL_R                        0x1F12C 0  // 🄬
#define UC_C_CD                                  0x1F12D 0  // 🄭
#define UC_C_WZ                                  0x1F12E 0  // 🄮
#define UC_COPYLEFT                              0x1F12F 0  // 🄯
#define UC_SQUARED_CAPITAL_A                     0x1F130 0  // 🄰
#define UC_SQUARED_CAPITAL_B                     0x1F131 0  // 🄱
#define UC_SQUARED_CAPITAL_C                     0x1F132 0  // 🄲
#define UC_SQUARED_CAPITAL_D                     0x1F133 0  // 🄳
#define UC_SQUARED_CAPITAL_E                     0x1F134 0  // 🄴
#define UC_SQUARED_CAPITAL_F                     0x1F135 0  // 🄵
#define UC_SQUARED_CAPITAL_G                     0x1F136 0  // 🄶
#define UC_SQUARED_CAPITAL_H                     0x1F137 0  // 🄷
#define UC_SQUARED_CAPITAL_I                     0x1F138 0  // 🄸
#define UC_SQUARED_CAPITAL_J                     0x1F139 0  // 🄹
#define UC_SQUARED_CAPITAL_K                     0x1F13A 0  // 🄺
#define UC_SQUARED_CAPITAL_L                     0x1F13B 0  // 🄻
#define UC_SQUARED_CAPITAL_M                     0x1F13C 0  // 🄼
#define UC_SQUARED_CAPITAL_N                     0x1F13D 0  // 🄽
#define UC_SQUARED_CAPITAL_O                     0x1F13E 0  // 🄾
#define UC_SQUARED_CAPITAL_P                     0x1F13F 0  // 🄿
#define UC_SQUARED_CAPITAL_Q                     0x1F140 0  // 🅀
#define UC_SQUARED_CAPITAL_R                     0x1F141 0  // 🅁
#define UC_SQUARED_CAPITAL_S                     0x1F142 0  // 🅂
#define UC_SQUARED_CAPITAL_T                     0x1F143 0  // 🅃
#define UC_SQUARED_CAPITAL_U                     0x1F144 0  // 🅄
#define UC_SQUARED_CAPITAL_V                     0x1F145 0  // 🅅
#define UC_SQUARED_CAPITAL_W                     0x1F146 0  // 🅆
#define UC_SQUARED_CAPITAL_X                     0x1F147 0  // 🅇
#define UC_SQUARED_CAPITAL_Y                     0x1F148 0  // 🅈
#define UC_SQUARED_CAPITAL_Z                     0x1F149 0  // 🅉
#define UC_SQUARED_HV                            0x1F14A 0  // 🅊
#define UC_SQUARED_MV                            0x1F14B 0  // 🅋
#define UC_SQUARED_SD                            0x1F14C 0  // 🅌
#define UC_SQUARED_SS                            0x1F14D 0  // 🅍
#define UC_SQUARED_PPV                           0x1F14E 0  // 🅎
#define UC_SQUARED_WC                            0x1F14F 0  // 🅏
#define UC_NEGATIVE_C_CAPITAL_A                  0x1F150 0  // 🅐
#define UC_NEGATIVE_C_CAPITAL_B                  0x1F151 0  // 🅑
#define UC_NEGATIVE_C_CAPITAL_C                  0x1F152 0  // 🅒
#define UC_NEGATIVE_C_CAPITAL_D                  0x1F153 0  // 🅓
#define UC_NEGATIVE_C_CAPITAL_E                  0x1F154 0  // 🅔
#define UC_NEGATIVE_C_CAPITAL_F                  0x1F155 0  // 🅕
#define UC_NEGATIVE_C_CAPITAL_G                  0x1F156 0  // 🅖
#define UC_NEGATIVE_C_CAPITAL_H                  0x1F157 0  // 🅗
#define UC_NEGATIVE_C_CAPITAL_I                  0x1F158 0  // 🅘
#define UC_NEGATIVE_C_CAPITAL_J                  0x1F159 0  // 🅙
#define UC_NEGATIVE_C_CAPITAL_K                  0x1F15A 0  // 🅚
#define UC_NEGATIVE_C_CAPITAL_L                  0x1F15B 0  // 🅛
#define UC_NEGATIVE_C_CAPITAL_M                  0x1F15C 0  // 🅜
#define UC_NEGATIVE_C_CAPITAL_N                  0x1F15D 0  // 🅝
#define UC_NEGATIVE_C_CAPITAL_O                  0x1F15E 0  // 🅞
#define UC_NEGATIVE_C_CAPITAL_P                  0x1F15F 0  // 🅟
#define UC_NEGATIVE_C_CAPITAL_Q                  0x1F160 0  // 🅠
#define UC_NEGATIVE_C_CAPITAL_R                  0x1F161 0  // 🅡
#define UC_NEGATIVE_C_CAPITAL_S                  0x1F162 0  // 🅢
#define UC_NEGATIVE_C_CAPITAL_T                  0x1F163 0  // 🅣
#define UC_NEGATIVE_C_CAPITAL_U                  0x1F164 0  // 🅤
#define UC_NEGATIVE_C_CAPITAL_V                  0x1F165 0  // 🅥
#define UC_NEGATIVE_C_CAPITAL_W                  0x1F166 0  // 🅦
#define UC_NEGATIVE_C_CAPITAL_X                  0x1F167 0  // 🅧
#define UC_NEGATIVE_C_CAPITAL_Y                  0x1F168 0  // 🅨
#define UC_NEGATIVE_C_CAPITAL_Z                  0x1F169 0  // 🅩
#define UC_RAISED_MC_SIGN                        0x1F16A 0  // 🅪
#define UC_RAISED_MD_SIGN                        0x1F16B 0  // 🅫
#define UC_RAISED_MR_SIGN                        0x1F16C 0  // 🅬
#define UC_C_CC                                  0x1F16D 0  // 🅭
#define UC_C_C_OVERLAID_BACKSLASH                0x1F16E 0  // 🅮
#define UC_C_HUMAN_FIGURE                        0x1F16F 0  // 🅯
#define UC_NEGATIVE_SQUARED_CAPITAL_A            0x1F170 0  // 🅰
#define UC_NEGATIVE_SQUARED_CAPITAL_B            0x1F171 0  // 🅱
#define UC_NEGATIVE_SQUARED_CAPITAL_C            0x1F172 0  // 🅲
#define UC_NEGATIVE_SQUARED_CAPITAL_D            0x1F173 0  // 🅳
#define UC_NEGATIVE_SQUARED_CAPITAL_E            0x1F174 0  // 🅴
#define UC_NEGATIVE_SQUARED_CAPITAL_F            0x1F175 0  // 🅵
#define UC_NEGATIVE_SQUARED_CAPITAL_G            0x1F176 0  // 🅶
#define UC_NEGATIVE_SQUARED_CAPITAL_H            0x1F177 0  // 🅷
#define UC_NEGATIVE_SQUARED_CAPITAL_I            0x1F178 0  // 🅸
#define UC_NEGATIVE_SQUARED_CAPITAL_J            0x1F179 0  // 🅹
#define UC_NEGATIVE_SQUARED_CAPITAL_K            0x1F17A 0  // 🅺
#define UC_NEGATIVE_SQUARED_CAPITAL_L            0x1F17B 0  // 🅻
#define UC_NEGATIVE_SQUARED_CAPITAL_M            0x1F17C 0  // 🅼
#define UC_NEGATIVE_SQUARED_CAPITAL_N            0x1F17D 0  // 🅽
#define UC_NEGATIVE_SQUARED_CAPITAL_O            0x1F17E 0  // 🅾
#define UC_NEGATIVE_SQUARED_CAPITAL_P            0x1F17F 0  // 🅿
#define UC_NEGATIVE_SQUARED_CAPITAL_Q            0x1F180 0  // 🆀
#define UC_NEGATIVE_SQUARED_CAPITAL_R            0x1F181 0  // 🆁
#define UC_NEGATIVE_SQUARED_CAPITAL_S            0x1F182 0  // 🆂
#define UC_NEGATIVE_SQUARED_CAPITAL_T            0x1F183 0  // 🆃
#define UC_NEGATIVE_SQUARED_CAPITAL_U            0x1F184 0  // 🆄
#define UC_NEGATIVE_SQUARED_CAPITAL_V            0x1F185 0  // 🆅
#define UC_NEGATIVE_SQUARED_CAPITAL_W            0x1F186 0  // 🆆
#define UC_NEGATIVE_SQUARED_CAPITAL_X            0x1F187 0  // 🆇
#define UC_NEGATIVE_SQUARED_CAPITAL_Y            0x1F188 0  // 🆈
#define UC_NEGATIVE_SQUARED_CAPITAL_Z            0x1F189 0  // 🆉
#define UC_CROSSED_NEGATIVE_SQUARED_CAPITAL_P    0x1F18A 0  // 🆊
#define UC_NEGATIVE_SQUARED_IC                   0x1F18B 0  // 🆋
#define UC_NEGATIVE_SQUARED_PA                   0x1F18C 0  // 🆌
#define UC_NEGATIVE_SQUARED_SA                   0x1F18D 0  // 🆍
#define UC_NEGATIVE_SQUARED_AB                   0x1F18E 0  // 🆎
#define UC_NEGATIVE_SQUARED_WC                   0x1F18F 0  // 🆏
#define UC_SQUARE_DJ                             0x1F190 0  // 🆐
#define UC_SQUARED_CL                            0x1F191 0  // 🆑
#define UC_SQUARED_COOL                          0x1F192 0  // 🆒
#define UC_SQUARED_FREE                          0x1F193 0  // 🆓
#define UC_SQUARED_ID                            0x1F194 0  // 🆔
#define UC_SQUARED_NEW                           0x1F195 0  // 🆕
#define UC_SQUARED_NG                            0x1F196 0  // 🆖
#define UC_SQUARED_OK                            0x1F197 0  // 🆗
#define UC_SQUARED_SOS                           0x1F198 0  // 🆘
#define UC_SQUARED_UP_EXCLAMATION_MARK           0x1F199 0  // 🆙
#define UC_SQUARED_VS                            0x1F19A 0  // 🆚
#define UC_SQUARED_THREE_D                       0x1F19B 0  // 🆛
#define UC_SQUARED_SECOND_SCREEN                 0x1F19C 0  // 🆜
#define UC_SQUARED_TWO_K                         0x1F19D 0  // 🆝
#define UC_SQUARED_FOUR_K                        0x1F19E 0  // 🆞
#define UC_SQUARED_EIGHT_K                       0x1F19F 0  // 🆟
#define UC_SQUARED_FIVE_POINT_ONE                0x1F1A0 0  // 🆠
#define UC_SQUARED_SEVEN_POINT_ONE               0x1F1A1 0  // 🆡
#define UC_SQUARED_TWENTY_TWO_POINT_TWO          0x1F1A2 0  // 🆢
#define UC_SQUARED_SIXTY_P                       0x1F1A3 0  // 🆣
#define UC_SQUARED_ONE_HUNDRED_TWENTY_P          0x1F1A4 0  // 🆤
#define UC_SQUARED_SMALL_D                       0x1F1A5 0  // 🆥
#define UC_SQUARED_HC                            0x1F1A6 0  // 🆦
#define UC_SQUARED_HDR                           0x1F1A7 0  // 🆧
#define UC_SQUARED_HI_RES                        0x1F1A8 0  // 🆨
#define UC_SQUARED_LOSSLESS                      0x1F1A9 0  // 🆩
#define UC_SQUARED_SHV                           0x1F1AA 0  // 🆪
#define UC_SQUARED_UHD                           0x1F1AB 0  // 🆫
#define UC_SQUARED_VOD                           0x1F1AC 0  // 🆬
#define UC_MASK_WORK                             0x1F1AD 0  // 🆭
#define UC_REGIONAL_INDICATOR_A                  0x1F1E6 0  // 🇦
#define UC_REGIONAL_INDICATOR_B                  0x1F1E7 0  // 🇧
#define UC_REGIONAL_INDICATOR_C                  0x1F1E8 0  // 🇨
#define UC_REGIONAL_INDICATOR_D                  0x1F1E9 0  // 🇩
#define UC_REGIONAL_INDICATOR_E                  0x1F1EA 0  // 🇪
#define UC_REGIONAL_INDICATOR_F                  0x1F1EB 0  // 🇫
#define UC_REGIONAL_INDICATOR_G                  0x1F1EC 0  // 🇬
#define UC_REGIONAL_INDICATOR_H                  0x1F1ED 0  // 🇭
#define UC_REGIONAL_INDICATOR_I                  0x1F1EE 0  // 🇮
#define UC_REGIONAL_INDICATOR_J                  0x1F1EF 0  // 🇯
#define UC_REGIONAL_INDICATOR_K                  0x1F1F0 0  // 🇰
#define UC_REGIONAL_INDICATOR_L                  0x1F1F1 0  // 🇱
#define UC_REGIONAL_INDICATOR_M                  0x1F1F2 0  // 🇲
#define UC_REGIONAL_INDICATOR_N                  0x1F1F3 0  // 🇳
#define UC_REGIONAL_INDICATOR_O                  0x1F1F4 0  // 🇴
#define UC_REGIONAL_INDICATOR_P                  0x1F1F5 0  // 🇵
#define UC_REGIONAL_INDICATOR_Q                  0x1F1F6 0  // 🇶
#define UC_REGIONAL_INDICATOR_R                  0x1F1F7 0  // 🇷
#define UC_REGIONAL_INDICATOR_S                  0x1F1F8 0  // 🇸
#define UC_REGIONAL_INDICATOR_T                  0x1F1F9 0  // 🇹
#define UC_REGIONAL_INDICATOR_U                  0x1F1FA 0  // 🇺
#define UC_REGIONAL_INDICATOR_V                  0x1F1FB 0  // 🇻
#define UC_REGIONAL_INDICATOR_W                  0x1F1FC 0  // 🇼
#define UC_REGIONAL_INDICATOR_X                  0x1F1FD 0  // 🇽
#define UC_REGIONAL_INDICATOR_Y                  0x1F1FE 0  // 🇾
#define UC_REGIONAL_INDICATOR_Z                  0x1F1FF 0  // 🇿
