/* ethiopic_extended_a.h – Unicode constants for U+AB00 … U+AB2F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Ethiopic_Extended_A
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/UAB00.pdf
 
* Consistency Check:
* Total Defined Code Points: 32
* Total Significant Hex Values: 32
* Status: OK (Counts Match)

*/

#pragma once

#define UC_ETHIOPIC_SYLLABLE_TTHU                0xAB01 0  // ꬁ
#define UC_ETHIOPIC_SYLLABLE_TTHI                0xAB02 0  // ꬂ
#define UC_ETHIOPIC_SYLLABLE_TTHAA               0xAB03 0  // ꬃ
#define UC_ETHIOPIC_SYLLABLE_TTHEE               0xAB04 0  // ꬄ
#define UC_ETHIOPIC_SYLLABLE_TTHE                0xAB05 0  // ꬅ
#define UC_ETHIOPIC_SYLLABLE_TTHO                0xAB06 0  // ꬆ
#define UC_ETHIOPIC_SYLLABLE_DDHU                0xAB09 0  // ꬉ
#define UC_ETHIOPIC_SYLLABLE_DDHI                0xAB0A 0  // ꬊ
#define UC_ETHIOPIC_SYLLABLE_DDHAA               0xAB0B 0  // ꬋ
#define UC_ETHIOPIC_SYLLABLE_DDHEE               0xAB0C 0  // ꬌ
#define UC_ETHIOPIC_SYLLABLE_DDHE                0xAB0D 0  // ꬍ
#define UC_ETHIOPIC_SYLLABLE_DDHO                0xAB0E 0  // ꬎ
#define UC_ETHIOPIC_SYLLABLE_DZU                 0xAB11 0  // ꬑ
#define UC_ETHIOPIC_SYLLABLE_DZI                 0xAB12 0  // ꬒ
#define UC_ETHIOPIC_SYLLABLE_DZAA                0xAB13 0  // ꬓ
#define UC_ETHIOPIC_SYLLABLE_DZEE                0xAB14 0  // ꬔ
#define UC_ETHIOPIC_SYLLABLE_DZE                 0xAB15 0  // ꬕ
#define UC_ETHIOPIC_SYLLABLE_DZO                 0xAB16 0  // ꬖ
#define UC_ETHIOPIC_SYLLABLE_CCHHA               0xAB20 0  // ꬠ
#define UC_ETHIOPIC_SYLLABLE_CCHHU               0xAB21 0  // ꬡ
#define UC_ETHIOPIC_SYLLABLE_CCHHI               0xAB22 0  // ꬢ
#define UC_ETHIOPIC_SYLLABLE_CCHHAA              0xAB23 0  // ꬣ
#define UC_ETHIOPIC_SYLLABLE_CCHHEE              0xAB24 0  // ꬤ
#define UC_ETHIOPIC_SYLLABLE_CCHHE               0xAB25 0  // ꬥ
#define UC_ETHIOPIC_SYLLABLE_CCHHO               0xAB26 0  // ꬦ
#define UC_ETHIOPIC_SYLLABLE_BBA                 0xAB28 0  // ꬨ
#define UC_ETHIOPIC_SYLLABLE_BBU                 0xAB29 0  // ꬩ
#define UC_ETHIOPIC_SYLLABLE_BBI                 0xAB2A 0  // ꬪ
#define UC_ETHIOPIC_SYLLABLE_BBAA                0xAB2B 0  // ꬫ
#define UC_ETHIOPIC_SYLLABLE_BBEE                0xAB2C 0  // ꬬ
#define UC_ETHIOPIC_SYLLABLE_BBE                 0xAB2D 0  // ꬭ
#define UC_ETHIOPIC_SYLLABLE_BBO                 0xAB2E 0  // ꬮ
