/* glagolitic.h – Unicode constants for U+2C00 … U+2C5F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Glagolitic
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U2C00.pdf
 
* Consistency Check:
* Total Defined Code Points: 96
* Total Significant Hex Values: 96
* Status: OK (Counts Match)

*/

#pragma once

#define UC_GLAGOLITIC_AZU                        0x2C30 0x2C00  // ⰰ/Ⰰ
#define UC_GLAGOLITIC_BUKY                       0x2C31 0x2C01  // ⰱ/Ⰱ
#define UC_GLAGOLITIC_VEDE                       0x2C32 0x2C02  // ⰲ/Ⰲ
#define UC_GLAGOLITIC_GLAGOLI                    0x2C33 0x2C03  // ⰳ/Ⰳ
#define UC_GLAGOLITIC_DOBRO                      0x2C34 0x2C04  // ⰴ/Ⰴ
#define UC_GLAGOLITIC_YESTU                      0x2C35 0x2C05  // ⰵ/Ⰵ
#define UC_GLAGOLITIC_ZHIVETE                    0x2C36 0x2C06  // ⰶ/Ⰶ
#define UC_GLAGOLITIC_DZELO                      0x2C37 0x2C07  // ⰷ/Ⰷ
#define UC_GLAGOLITIC_ZEMLJA                     0x2C38 0x2C08  // ⰸ/Ⰸ
#define UC_GLAGOLITIC_IZHE                       0x2C39 0x2C09  // ⰹ/Ⰹ
#define UC_GLAGOLITIC_INITIAL_IZHE               0x2C3A 0x2C0A  // ⰺ/Ⰺ
#define UC_GLAGOLITIC_I                          0x2C3B 0x2C0B  // ⰻ/Ⰻ
#define UC_GLAGOLITIC_DJERVI                     0x2C3C 0x2C0C  // ⰼ/Ⰼ
#define UC_GLAGOLITIC_KAKO                       0x2C3D 0x2C0D  // ⰽ/Ⰽ
#define UC_GLAGOLITIC_LJUDIJE                    0x2C3E 0x2C0E  // ⰾ/Ⰾ
#define UC_GLAGOLITIC_MYSLITE                    0x2C3F 0x2C0F  // ⰿ/Ⰿ
#define UC_GLAGOLITIC_NASHI                      0x2C40 0x2C10  // ⱀ/Ⱀ
#define UC_GLAGOLITIC_ONU                        0x2C41 0x2C11  // ⱁ/Ⱁ
#define UC_GLAGOLITIC_POKOJI                     0x2C42 0x2C12  // ⱂ/Ⱂ
#define UC_GLAGOLITIC_RITSI                      0x2C43 0x2C13  // ⱃ/Ⱃ
#define UC_GLAGOLITIC_SLOVO                      0x2C44 0x2C14  // ⱄ/Ⱄ
#define UC_GLAGOLITIC_TVRIDO                     0x2C45 0x2C15  // ⱅ/Ⱅ
#define UC_GLAGOLITIC_UKU                        0x2C46 0x2C16  // ⱆ/Ⱆ
#define UC_GLAGOLITIC_FRITU                      0x2C47 0x2C17  // ⱇ/Ⱇ
#define UC_GLAGOLITIC_HERU                       0x2C48 0x2C18  // ⱈ/Ⱈ
#define UC_GLAGOLITIC_OTU                        0x2C49 0x2C19  // ⱉ/Ⱉ
#define UC_GLAGOLITIC_PE                         0x2C4A 0x2C1A  // ⱊ/Ⱊ
#define UC_GLAGOLITIC_SHTA                       0x2C4B 0x2C1B  // ⱋ/Ⱋ
#define UC_GLAGOLITIC_TSI                        0x2C4C 0x2C1C  // ⱌ/Ⱌ
#define UC_GLAGOLITIC_CHRIVI                     0x2C4D 0x2C1D  // ⱍ/Ⱍ
#define UC_GLAGOLITIC_SHA                        0x2C4E 0x2C1E  // ⱎ/Ⱎ
#define UC_GLAGOLITIC_YERU                       0x2C4F 0x2C1F  // ⱏ/Ⱏ
#define UC_GLAGOLITIC_YERI                       0x2C50 0x2C20  // ⱐ/Ⱐ
#define UC_GLAGOLITIC_YATI                       0x2C51 0x2C21  // ⱑ/Ⱑ
#define UC_GLAGOLITIC_SPIDERY_HA                 0x2C52 0x2C22  // ⱒ/Ⱒ
#define UC_GLAGOLITIC_YU                         0x2C53 0x2C23  // ⱓ/Ⱓ
#define UC_GLAGOLITIC_YUS                        0x2C54 0x2C24  // ⱔ/Ⱔ
#define UC_GLAGOLITIC_YUS_TAIL                   0x2C55 0x2C25  // ⱕ/Ⱕ
#define UC_GLAGOLITIC_YO                         0x2C56 0x2C26  // ⱖ/Ⱖ
#define UC_GLAGOLITIC_IOTATED_YUS                0x2C57 0x2C27  // ⱗ/Ⱗ
#define UC_GLAGOLITIC_BIG_YUS                    0x2C58 0x2C28  // ⱘ/Ⱘ
#define UC_GLAGOLITIC_IOTATED_BIG_YUS            0x2C59 0x2C29  // ⱙ/Ⱙ
#define UC_GLAGOLITIC_FITA                       0x2C5A 0x2C2A  // ⱚ/Ⱚ
#define UC_GLAGOLITIC_IZHITSA                    0x2C5B 0x2C2B  // ⱛ/Ⱛ
#define UC_GLAGOLITIC_SHTAPIC                    0x2C5C 0x2C2C  // ⱜ/Ⱜ
#define UC_GLAGOLITIC_TROKUTASTI_A               0x2C5D 0x2C2D  // ⱝ/Ⱝ
#define UC_GLAGOLITIC_LATINATE_MYSLITE           0x2C5E 0x2C2E  // ⱞ/Ⱞ
#define UC_GLAGOLITIC_CAUDATE_CHRIVI             0x2C5F 0x2C2F  // ⱟ/Ⱟ
