/* gunjala_gondi.h – Unicode constants for U+11D60 … U+11DAF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * The Gunjala Gondi lipi or Gunjala Gondi script is a script used to
 * write the Gondi language , a Dravidian language spoken by the Gond
 * people of northern Telangana , eastern Maharashtra , southeastern
 * Madhya Pradesh , and Chhattisgarh . Approximately a dozen manuscripts
 * in the script were recovered from Gunjala , a Gond village in Adilabad
 * district of Telangana , by a team of researchers from the University
 * of Hyderabad , led by Professor Jayadheer Tirumala Rao. The script and
 * preliminary font were unveiled in early 2014.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Gunjala_Gondi
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U11D60.pdf
 
* Consistency Check:
* Total Defined Code Points: 63
* Total Significant Hex Values: 63
* Status: OK (Counts Match)

*/

#pragma once

#define UC_GUNJALA_GONDI_A                       0x11D60 0  // 𑵠
#define UC_GUNJALA_GONDI_AA                      0x11D61 0  // 𑵡
#define UC_GUNJALA_GONDI_I                       0x11D62 0  // 𑵢
#define UC_GUNJALA_GONDI_II                      0x11D63 0  // 𑵣
#define UC_GUNJALA_GONDI_U                       0x11D64 0  // 𑵤
#define UC_GUNJALA_GONDI_UU                      0x11D65 0  // 𑵥
#define UC_GUNJALA_GONDI_EE                      0x11D67 0  // 𑵧
#define UC_GUNJALA_GONDI_AI                      0x11D68 0  // 𑵨
#define UC_GUNJALA_GONDI_OO                      0x11D6A 0  // 𑵪
#define UC_GUNJALA_GONDI_AU                      0x11D6B 0  // 𑵫
#define UC_GUNJALA_GONDI_YA                      0x11D6C 0  // 𑵬
#define UC_GUNJALA_GONDI_VA                      0x11D6D 0  // 𑵭
#define UC_GUNJALA_GONDI_BA                      0x11D6E 0  // 𑵮
#define UC_GUNJALA_GONDI_BHA                     0x11D6F 0  // 𑵯
#define UC_GUNJALA_GONDI_MA                      0x11D70 0  // 𑵰
#define UC_GUNJALA_GONDI_KA                      0x11D71 0  // 𑵱
#define UC_GUNJALA_GONDI_KHA                     0x11D72 0  // 𑵲
#define UC_GUNJALA_GONDI_TA                      0x11D73 0  // 𑵳
#define UC_GUNJALA_GONDI_THA                     0x11D74 0  // 𑵴
#define UC_GUNJALA_GONDI_LA                      0x11D75 0  // 𑵵
#define UC_GUNJALA_GONDI_GA                      0x11D76 0  // 𑵶
#define UC_GUNJALA_GONDI_GHA                     0x11D77 0  // 𑵷
#define UC_GUNJALA_GONDI_DA                      0x11D78 0  // 𑵸
#define UC_GUNJALA_GONDI_DHA                     0x11D79 0  // 𑵹
#define UC_GUNJALA_GONDI_NA                      0x11D7A 0  // 𑵺
#define UC_GUNJALA_GONDI_CA                      0x11D7B 0  // 𑵻
#define UC_GUNJALA_GONDI_CHA                     0x11D7C 0  // 𑵼
#define UC_GUNJALA_GONDI_TTA                     0x11D7D 0  // 𑵽
#define UC_GUNJALA_GONDI_TTHA                    0x11D7E 0  // 𑵾
#define UC_GUNJALA_GONDI_LLA                     0x11D7F 0  // 𑵿
#define UC_GUNJALA_GONDI_JA                      0x11D80 0  // 𑶀
#define UC_GUNJALA_GONDI_JHA                     0x11D81 0  // 𑶁
#define UC_GUNJALA_GONDI_DDA                     0x11D82 0  // 𑶂
#define UC_GUNJALA_GONDI_DDHA                    0x11D83 0  // 𑶃
#define UC_GUNJALA_GONDI_NGA                     0x11D84 0  // 𑶄
#define UC_GUNJALA_GONDI_PA                      0x11D85 0  // 𑶅
#define UC_GUNJALA_GONDI_PHA                     0x11D86 0  // 𑶆
#define UC_GUNJALA_GONDI_HA                      0x11D87 0  // 𑶇
#define UC_GUNJALA_GONDI_RA                      0x11D88 0  // 𑶈
#define UC_GUNJALA_GONDI_SA                      0x11D89 0  // 𑶉
#define UC_GUNJALA_GONDI_VOWEL_SIGN_AA           0x11D8A 0  // 𑶊
#define UC_GUNJALA_GONDI_VOWEL_SIGN_I            0x11D8B 0  // 𑶋
#define UC_GUNJALA_GONDI_VOWEL_SIGN_II           0x11D8C 0  // 𑶌
#define UC_GUNJALA_GONDI_VOWEL_SIGN_U            0x11D8D 0  // 𑶍
#define UC_GUNJALA_GONDI_VOWEL_SIGN_UU           0x11D8E 0  // 𑶎
#define UC_GUNJALA_GONDI_VOWEL_SIGN_EE           0x11D90 0  // 𑶐
#define UC_GUNJALA_GONDI_VOWEL_SIGN_AI           0x11D91 0  // 𑶑
#define UC_GUNJALA_GONDI_VOWEL_SIGN_OO           0x11D93 0  // 𑶓
#define UC_GUNJALA_GONDI_VOWEL_SIGN_AU           0x11D94 0  // 𑶔
#define UC_GUNJALA_GONDI_SIGN_ANUSVARA           0x11D95 0  // 𑶕
#define UC_GUNJALA_GONDI_SIGN_VISARGA            0x11D96 0  // 𑶖
#define UC_GUNJALA_GONDI_VIRAMA                  0x11D97 0  // 𑶗
#define UC_GUNJALA_GONDI_OM                      0x11D98 0  // 𑶘
#define UC_GUNJALA_GONDI_ZERO                    0x11DA0 0  // 𑶠
#define UC_GUNJALA_GONDI_ONE                     0x11DA1 0  // 𑶡
#define UC_GUNJALA_GONDI_TWO                     0x11DA2 0  // 𑶢
#define UC_GUNJALA_GONDI_THREE                   0x11DA3 0  // 𑶣
#define UC_GUNJALA_GONDI_FOUR                    0x11DA4 0  // 𑶤
#define UC_GUNJALA_GONDI_FIVE                    0x11DA5 0  // 𑶥
#define UC_GUNJALA_GONDI_SIX                     0x11DA6 0  // 𑶦
#define UC_GUNJALA_GONDI_SEVEN                   0x11DA7 0  // 𑶧
#define UC_GUNJALA_GONDI_EIGHT                   0x11DA8 0  // 𑶨
#define UC_GUNJALA_GONDI_NINE                    0x11DA9 0  // 𑶩
