/* gurung_khema.h – Unicode constants for U+16100 … U+1613F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * The Khema script , also known as Gurung Khema , Khema Phri , Khema
 * Lipi , is used to write the Gurung language . The Language Commission
 * of Nepal recognizes Khema as the official script of Gurung.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Gurung_Khema
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U16100.pdf
 
* Consistency Check:
* Total Defined Code Points: 58
* Total Significant Hex Values: 58
* Status: OK (Counts Match)

*/

#pragma once

#define UC_GURUNG_KHEMA_A                        0x16100 0  // 𖄀
#define UC_GURUNG_KHEMA_KA                       0x16101 0  // 𖄁
#define UC_GURUNG_KHEMA_KHA                      0x16102 0  // 𖄂
#define UC_GURUNG_KHEMA_GA                       0x16103 0  // 𖄃
#define UC_GURUNG_KHEMA_GHA                      0x16104 0  // 𖄄
#define UC_GURUNG_KHEMA_NGA                      0x16105 0  // 𖄅
#define UC_GURUNG_KHEMA_CA                       0x16106 0  // 𖄆
#define UC_GURUNG_KHEMA_CHA                      0x16107 0  // 𖄇
#define UC_GURUNG_KHEMA_JA                       0x16108 0  // 𖄈
#define UC_GURUNG_KHEMA_JHA                      0x16109 0  // 𖄉
#define UC_GURUNG_KHEMA_HA                       0x1610A 0  // 𖄊
#define UC_GURUNG_KHEMA_TTA                      0x1610B 0  // 𖄋
#define UC_GURUNG_KHEMA_TTHA                     0x1610C 0  // 𖄌
#define UC_GURUNG_KHEMA_DDA                      0x1610D 0  // 𖄍
#define UC_GURUNG_KHEMA_DDHA                     0x1610E 0  // 𖄎
#define UC_GURUNG_KHEMA_VA                       0x1610F 0  // 𖄏
#define UC_GURUNG_KHEMA_TA                       0x16110 0  // 𖄐
#define UC_GURUNG_KHEMA_THA                      0x16111 0  // 𖄑
#define UC_GURUNG_KHEMA_DA                       0x16112 0  // 𖄒
#define UC_GURUNG_KHEMA_DHA                      0x16113 0  // 𖄓
#define UC_GURUNG_KHEMA_NA                       0x16114 0  // 𖄔
#define UC_GURUNG_KHEMA_PA                       0x16115 0  // 𖄕
#define UC_GURUNG_KHEMA_PHA                      0x16116 0  // 𖄖
#define UC_GURUNG_KHEMA_BA                       0x16117 0  // 𖄗
#define UC_GURUNG_KHEMA_BHA                      0x16118 0  // 𖄘
#define UC_GURUNG_KHEMA_MA                       0x16119 0  // 𖄙
#define UC_GURUNG_KHEMA_YA                       0x1611A 0  // 𖄚
#define UC_GURUNG_KHEMA_RA                       0x1611B 0  // 𖄛
#define UC_GURUNG_KHEMA_LA                       0x1611C 0  // 𖄜
#define UC_GURUNG_KHEMA_SA                       0x1611D 0  // 𖄝
#define UC_GURUNG_KHEMA_VOWEL_SIGN_AA            0x1611E 0  // 𖄞
#define UC_GURUNG_KHEMA_VOWEL_SIGN_I             0x1611F 0  // 𖄟
#define UC_GURUNG_KHEMA_VOWEL_SIGN_II            0x16120 0  // 𖄠
#define UC_GURUNG_KHEMA_VOWEL_SIGN_U             0x16121 0  // 𖄡
#define UC_GURUNG_KHEMA_VOWEL_SIGN_UU            0x16122 0  // 𖄢
#define UC_GURUNG_KHEMA_VOWEL_SIGN_E             0x16123 0  // 𖄣
#define UC_GURUNG_KHEMA_VOWEL_SIGN_EE            0x16124 0  // 𖄤
#define UC_GURUNG_KHEMA_VOWEL_SIGN_AI            0x16125 0  // 𖄥
#define UC_GURUNG_KHEMA_VOWEL_SIGN_O             0x16126 0  // 𖄦
#define UC_GURUNG_KHEMA_VOWEL_SIGN_OO            0x16127 0  // 𖄧
#define UC_GURUNG_KHEMA_VOWEL_SIGN_AU            0x16128 0  // 𖄨
#define UC_GURUNG_KHEMA_VOWEL_LENGTH_MARK        0x16129 0  // 𖄩
#define UC_GURUNG_KHEMA_CONSONANT_SIGN_MEDIAL_YA 0x1612A 0  // 𖄪
#define UC_GURUNG_KHEMA_CONSONANT_SIGN_MEDIAL_VA 0x1612B 0  // 𖄫
#define UC_GURUNG_KHEMA_CONSONANT_SIGN_MEDIAL_HA 0x1612C 0  // 𖄬
#define UC_GURUNG_KHEMA_SIGN_ANUSVARA            0x1612D 0  // 𖄭
#define UC_GURUNG_KHEMA_CONSONANT_SIGN_MEDIAL_RA 0x1612E 0  // 𖄮
#define UC_GURUNG_KHEMA_SIGN_THOLHOMA            0x1612F 0  // 𖄯
#define UC_GURUNG_KHEMA_ZERO                     0x16130 0  // 𖄰
#define UC_GURUNG_KHEMA_ONE                      0x16131 0  // 𖄱
#define UC_GURUNG_KHEMA_TWO                      0x16132 0  // 𖄲
#define UC_GURUNG_KHEMA_THREE                    0x16133 0  // 𖄳
#define UC_GURUNG_KHEMA_FOUR                     0x16134 0  // 𖄴
#define UC_GURUNG_KHEMA_FIVE                     0x16135 0  // 𖄵
#define UC_GURUNG_KHEMA_SIX                      0x16136 0  // 𖄶
#define UC_GURUNG_KHEMA_SEVEN                    0x16137 0  // 𖄷
#define UC_GURUNG_KHEMA_EIGHT                    0x16138 0  // 𖄸
#define UC_GURUNG_KHEMA_NINE                     0x16139 0  // 𖄹
