/* hangul_jamo_extended_a.h – Unicode constants for U+A960 … U+A97F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Hangul_Jamo_Extended_A
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/UA960.pdf
 
* Consistency Check:
* Total Defined Code Points: 29
* Total Significant Hex Values: 29
* Status: OK (Counts Match)

*/

#pragma once

#define UC_HANGUL_CHOSEONG_TIKEUT_MIEUM          0xA960 0  // ꥠ
#define UC_HANGUL_CHOSEONG_TIKEUT_PIEUP          0xA961 0  // ꥡ
#define UC_HANGUL_CHOSEONG_TIKEUT_SIOS           0xA962 0  // ꥢ
#define UC_HANGUL_CHOSEONG_TIKEUT_CIEUC          0xA963 0  // ꥣ
#define UC_HANGUL_CHOSEONG_RIEUL_KIYEOK          0xA964 0  // ꥤ
#define UC_HANGUL_CHOSEONG_RIEUL_SSANGKIYEOK     0xA965 0  // ꥥ
#define UC_HANGUL_CHOSEONG_RIEUL_TIKEUT          0xA966 0  // ꥦ
#define UC_HANGUL_CHOSEONG_RIEUL_SSANGTIKEUT     0xA967 0  // ꥧ
#define UC_HANGUL_CHOSEONG_RIEUL_MIEUM           0xA968 0  // ꥨ
#define UC_HANGUL_CHOSEONG_RIEUL_PIEUP           0xA969 0  // ꥩ
#define UC_HANGUL_CHOSEONG_RIEUL_SSANGPIEUP      0xA96A 0  // ꥪ
#define UC_HANGUL_CHOSEONG_RIEUL_KAPYEOUNPIEUP   0xA96B 0  // ꥫ
#define UC_HANGUL_CHOSEONG_RIEUL_SIOS            0xA96C 0  // ꥬ
#define UC_HANGUL_CHOSEONG_RIEUL_CIEUC           0xA96D 0  // ꥭ
#define UC_HANGUL_CHOSEONG_RIEUL_KHIEUKH         0xA96E 0  // ꥮ
#define UC_HANGUL_CHOSEONG_MIEUM_KIYEOK          0xA96F 0  // ꥯ
#define UC_HANGUL_CHOSEONG_MIEUM_TIKEUT          0xA970 0  // ꥰ
#define UC_HANGUL_CHOSEONG_MIEUM_SIOS            0xA971 0  // ꥱ
#define UC_HANGUL_CHOSEONG_PIEUP_SIOS_THIEUTH    0xA972 0  // ꥲ
#define UC_HANGUL_CHOSEONG_PIEUP_KHIEUKH         0xA973 0  // ꥳ
#define UC_HANGUL_CHOSEONG_PIEUP_HIEUH           0xA974 0  // ꥴ
#define UC_HANGUL_CHOSEONG_SSANGSIOS_PIEUP       0xA975 0  // ꥵ
#define UC_HANGUL_CHOSEONG_IEUNG_RIEUL           0xA976 0  // ꥶ
#define UC_HANGUL_CHOSEONG_IEUNG_HIEUH           0xA977 0  // ꥷ
#define UC_HANGUL_CHOSEONG_SSANGCIEUC_HIEUH      0xA978 0  // ꥸ
#define UC_HANGUL_CHOSEONG_SSANGTHIEUTH          0xA979 0  // ꥹ
#define UC_HANGUL_CHOSEONG_PHIEUPH_HIEUH         0xA97A 0  // ꥺ
#define UC_HANGUL_CHOSEONG_HIEUH_SIOS            0xA97B 0  // ꥻ
#define UC_HANGUL_CHOSEONG_SSANGYEORINHIEUH      0xA97C 0  // ꥼ
