/* ideographic_symbols_and_punctuation.h – Unicode constants for U+16FE0 … U+16FFF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Ideographic Symbols and Punctuation is a Unicode block containing
 * symbols and punctuation marks used by ideographic scripts such as
 * Tangut and Nüshu , in addition to punctuation marks, symbols,
 * diacritics and modifier letters supplementing those in the CJK Symbols
 * and Punctuation block.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Ideographic Symbols and
 * Punctuation block:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Ideographic_Symbols_and_Punctuation
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U16FE0.pdf
 
* Consistency Check:
* Total Defined Code Points: 12
* Total Significant Hex Values: 12
* Status: OK (Counts Match)

*/

#pragma once

#define UC_TANGUT_ITERATION_MARK                 0x16FE0 0  // 𖿠
#define UC_NUSHU_ITERATION_MARK                  0x16FE1 0  // 𖿡
#define UC_OLD_CHINESE_HOOK_MARK                 0x16FE2 0  // 𖿢
#define UC_OLD_CHINESE_ITERATION_MARK            0x16FE3 0  // 𖿣
#define UC_KHITAN_SMALL_SC_FILLER                0x16FE4 0  // 𖿤
#define UC_VIETNAMESE_ALTERNATE_READING_MARK_CA  0x16FF0 0  // 𖿰
#define UC_VIETNAMESE_ALTERNATE_READING_MARK_NHAY 0x16FF1 0  // 𖿱
#define UC_CHINESE_SMALL_SIMPLIFIED_ER           0x16FF2 0  // 𖿲
#define UC_CHINESE_SMALL_TRADITIONAL_ER          0x16FF3 0  // 𖿳
#define UC_YANGQIN_SIGN_SLOW_ONE_BEAT            0x16FF4 0  // 𖿴
#define UC_YANGQIN_SIGN_SLOW_THREE_HALF_BEATS    0x16FF5 0  // 𖿵
#define UC_YANGQIN_SIGN_SLOW_TWO_BEATS           0x16FF6 0  // 𖿶
