/* inscriptional_pahlavi.h – Unicode constants for U+10B60 … U+10B7F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Inscriptional Pahlavi is the earliest attested form of Pahlavi scripts
 * , and is evident in clay fragments that have been dated to the reign
 * of Mithridates I ( r. 171–138 BC). Other early evidence includes the
 * Pahlavi inscriptions of Parthian coins and the rock inscriptions of
 * Sasanian emperors and other notables, such as Kartir the High Priest .
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Inscriptional_Pahlavi
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U10B60.pdf
 
* Consistency Check:
* Total Defined Code Points: 27
* Total Significant Hex Values: 27
* Status: OK (Counts Match)

*/

#pragma once

#define UC_IP_INSCIONAL_PAHLAVI_ALEPH            0x10B60 0  // 𐭠
#define UC_IP_INSCIONAL_PAHLAVI_BETH             0x10B61 0  // 𐭡
#define UC_IP_INSCIONAL_PAHLAVI_GIMEL            0x10B62 0  // 𐭢
#define UC_IP_INSCIONAL_PAHLAVI_DALETH           0x10B63 0  // 𐭣
#define UC_IP_INSCIONAL_PAHLAVI_HE               0x10B64 0  // 𐭤
#define UC_IP_INSCIONAL_PAHLAVI_WAW_AYIN_RESH    0x10B65 0  // 𐭥
#define UC_IP_INSCIONAL_PAHLAVI_ZAYIN            0x10B66 0  // 𐭦
#define UC_IP_INSCIONAL_PAHLAVI_HETH             0x10B67 0  // 𐭧
#define UC_IP_INSCIONAL_PAHLAVI_TETH             0x10B68 0  // 𐭨
#define UC_IP_INSCIONAL_PAHLAVI_YODH             0x10B69 0  // 𐭩
#define UC_IP_INSCIONAL_PAHLAVI_KAPH             0x10B6A 0  // 𐭪
#define UC_IP_INSCIONAL_PAHLAVI_LAMEDH           0x10B6B 0  // 𐭫
#define UC_IP_INSCIONAL_PAHLAVI_MEM_QOPH         0x10B6C 0  // 𐭬
#define UC_IP_INSCIONAL_PAHLAVI_NUN              0x10B6D 0  // 𐭭
#define UC_IP_INSCIONAL_PAHLAVI_SAMEKH           0x10B6E 0  // 𐭮
#define UC_IP_INSCIONAL_PAHLAVI_PE               0x10B6F 0  // 𐭯
#define UC_IP_INSCIONAL_PAHLAVI_SADHE            0x10B70 0  // 𐭰
#define UC_IP_INSCIONAL_PAHLAVI_SHIN             0x10B71 0  // 𐭱
#define UC_IP_INSCIONAL_PAHLAVI_TAW              0x10B72 0  // 𐭲
#define UC_IP_INSCIONAL_PAHLAVI_ONE              0x10B78 0  // 𐭸
#define UC_IP_INSCIONAL_PAHLAVI_TWO              0x10B79 0  // 𐭹
#define UC_IP_INSCIONAL_PAHLAVI_THREE            0x10B7A 0  // 𐭺
#define UC_IP_INSCIONAL_PAHLAVI_FOUR             0x10B7B 0  // 𐭻
#define UC_IP_INSCIONAL_PAHLAVI_TEN              0x10B7C 0  // 𐭼
#define UC_IP_INSCIONAL_PAHLAVI_TWENTY           0x10B7D 0  // 𐭽
#define UC_IP_INSCIONAL_PAHLAVI_ONE_HUNDRED      0x10B7E 0  // 𐭾
#define UC_IP_INSCIONAL_PAHLAVI_ONE_THOUSAND     0x10B7F 0  // 𐭿
