/* inscriptional_parthian.h – Unicode constants for U+10B40 … U+10B5F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Inscriptional Parthian was a script used to write the Parthian
 * language ; the majority of the text found has been from clay
 * fragments. This script was used from the 2nd century CE to the 5th
 * century CE or in the Parthian Empire to the early Sasanian Empire .
 * During the Sasanian Empire , it was mostly used for official texts.
 * Inscriptional Parthian is written right to left, and the letters are
 * not joined.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Inscriptional_Parthian
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U10B40.pdf
 
* Consistency Check:
* Total Defined Code Points: 30
* Total Significant Hex Values: 30
* Status: OK (Counts Match)

*/

#pragma once

#define UC_INSCIONAL_PARTHIAN_ALEPH              0x10B40 0  // 𐭀
#define UC_INSCIONAL_PARTHIAN_BETH               0x10B41 0  // 𐭁
#define UC_INSCIONAL_PARTHIAN_GIMEL              0x10B42 0  // 𐭂
#define UC_INSCIONAL_PARTHIAN_DALETH             0x10B43 0  // 𐭃
#define UC_INSCIONAL_PARTHIAN_HE                 0x10B44 0  // 𐭄
#define UC_INSCIONAL_PARTHIAN_WAW                0x10B45 0  // 𐭅
#define UC_INSCIONAL_PARTHIAN_ZAYIN              0x10B46 0  // 𐭆
#define UC_INSCIONAL_PARTHIAN_HETH               0x10B47 0  // 𐭇
#define UC_INSCIONAL_PARTHIAN_TETH               0x10B48 0  // 𐭈
#define UC_INSCIONAL_PARTHIAN_YODH               0x10B49 0  // 𐭉
#define UC_INSCIONAL_PARTHIAN_KAPH               0x10B4A 0  // 𐭊
#define UC_INSCIONAL_PARTHIAN_LAMEDH             0x10B4B 0  // 𐭋
#define UC_INSCIONAL_PARTHIAN_MEM                0x10B4C 0  // 𐭌
#define UC_INSCIONAL_PARTHIAN_NUN                0x10B4D 0  // 𐭍
#define UC_INSCIONAL_PARTHIAN_SAMEKH             0x10B4E 0  // 𐭎
#define UC_INSCIONAL_PARTHIAN_AYIN               0x10B4F 0  // 𐭏
#define UC_INSCIONAL_PARTHIAN_PE                 0x10B50 0  // 𐭐
#define UC_INSCIONAL_PARTHIAN_SADHE              0x10B51 0  // 𐭑
#define UC_INSCIONAL_PARTHIAN_QOPH               0x10B52 0  // 𐭒
#define UC_INSCIONAL_PARTHIAN_RESH               0x10B53 0  // 𐭓
#define UC_INSCIONAL_PARTHIAN_SHIN               0x10B54 0  // 𐭔
#define UC_INSCIONAL_PARTHIAN_TAW                0x10B55 0  // 𐭕
#define UC_INSCIONAL_PARTHIAN_ONE                0x10B58 0  // 𐭘
#define UC_INSCIONAL_PARTHIAN_TWO                0x10B59 0  // 𐭙
#define UC_INSCIONAL_PARTHIAN_THREE              0x10B5A 0  // 𐭚
#define UC_INSCIONAL_PARTHIAN_FOUR               0x10B5B 0  // 𐭛
#define UC_INSCIONAL_PARTHIAN_TEN                0x10B5C 0  // 𐭜
#define UC_INSCIONAL_PARTHIAN_TWENTY             0x10B5D 0  // 𐭝
#define UC_INSCIONAL_PARTHIAN_ONE_HUNDRED        0x10B5E 0  // 𐭞
#define UC_INSCIONAL_PARTHIAN_ONE_THOUSAND       0x10B5F 0  // 𐭟
