/* kana_extended_a.h – Unicode constants for U+1B100 … U+1B12F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Kana_Extended_A
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1B100.pdf
 
* Consistency Check:
* Total Defined Code Points: 35
* Total Significant Hex Values: 35
* Status: OK (Counts Match)

*/

#pragma once

#define UC_HENTAIGANA_RE_3                       0x1B100 0  // 𛄀
#define UC_HENTAIGANA_RE_4                       0x1B101 0  // 𛄁
#define UC_HENTAIGANA_RO_1                       0x1B102 0  // 𛄂
#define UC_HENTAIGANA_RO_2                       0x1B103 0  // 𛄃
#define UC_HENTAIGANA_RO_3                       0x1B104 0  // 𛄄
#define UC_HENTAIGANA_RO_4                       0x1B105 0  // 𛄅
#define UC_HENTAIGANA_RO_5                       0x1B106 0  // 𛄆
#define UC_HENTAIGANA_RO_6                       0x1B107 0  // 𛄇
#define UC_HENTAIGANA_WA_1                       0x1B108 0  // 𛄈
#define UC_HENTAIGANA_WA_2                       0x1B109 0  // 𛄉
#define UC_HENTAIGANA_WA_3                       0x1B10A 0  // 𛄊
#define UC_HENTAIGANA_WA_4                       0x1B10B 0  // 𛄋
#define UC_HENTAIGANA_WA_5                       0x1B10C 0  // 𛄌
#define UC_HENTAIGANA_WI_1                       0x1B10D 0  // 𛄍
#define UC_HENTAIGANA_WI_2                       0x1B10E 0  // 𛄎
#define UC_HENTAIGANA_WI_3                       0x1B10F 0  // 𛄏
#define UC_HENTAIGANA_WI_4                       0x1B110 0  // 𛄐
#define UC_HENTAIGANA_WI_5                       0x1B111 0  // 𛄑
#define UC_HENTAIGANA_WE_1                       0x1B112 0  // 𛄒
#define UC_HENTAIGANA_WE_2                       0x1B113 0  // 𛄓
#define UC_HENTAIGANA_WE_3                       0x1B114 0  // 𛄔
#define UC_HENTAIGANA_WE_4                       0x1B115 0  // 𛄕
#define UC_HENTAIGANA_WO_1                       0x1B116 0  // 𛄖
#define UC_HENTAIGANA_WO_2                       0x1B117 0  // 𛄗
#define UC_HENTAIGANA_WO_3                       0x1B118 0  // 𛄘
#define UC_HENTAIGANA_WO_4                       0x1B119 0  // 𛄙
#define UC_HENTAIGANA_WO_5                       0x1B11A 0  // 𛄚
#define UC_HENTAIGANA_WO_6                       0x1B11B 0  // 𛄛
#define UC_HENTAIGANA_WO_7                       0x1B11C 0  // 𛄜
#define UC_HENTAIGANA_N_MU_MO_1                  0x1B11D 0  // 𛄝
#define UC_HENTAIGANA_N_MU_MO_2                  0x1B11E 0  // 𛄞
#define UC_HIRAGANA_ARCHAIC_WU                   0x1B11F 0  // 𛄟
#define UC_KATAKANA_ARCHAIC_YI                   0x1B120 0  // 𛄠
#define UC_KATAKANA_ARCHAIC_YE                   0x1B121 0  // 𛄡
#define UC_KATAKANA_ARCHAIC_WU                   0x1B122 0  // 𛄢
