/* kayah_li.h – Unicode constants for U+A900 … U+A92F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * The Kayah Li alphabet (Kayah Li: ꤊꤢꤛꤢ꤭ ꤜꤟꤤ꤬ ) is used to write the
 * Kayah languages Eastern Kayah Li and Western Kayah Li , which are
 * members of Karenic branch of the Sino-Tibetan language family . They
 * are also known as Red Karen and Karenni . Eastern Kayah Li is spoken
 * by about 26,000 people, and Western Kayah Li by about 100,000 people,
 * mostly in the Kayah and Karen states of Myanmar , but also by people
 * living in Thailand .
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Kayah_Li
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/UA900.pdf
 
* Consistency Check:
* Total Defined Code Points: 48
* Total Significant Hex Values: 48
* Status: OK (Counts Match)

*/

#pragma once

#define UC_KAYAH_LI_ZERO                         0xA900 0  // ꤀
#define UC_KAYAH_LI_ONE                          0xA901 0  // ꤁
#define UC_KAYAH_LI_TWO                          0xA902 0  // ꤂
#define UC_KAYAH_LI_THREE                        0xA903 0  // ꤃
#define UC_KAYAH_LI_FOUR                         0xA904 0  // ꤄
#define UC_KAYAH_LI_FIVE                         0xA905 0  // ꤅
#define UC_KAYAH_LI_SIX                          0xA906 0  // ꤆
#define UC_KAYAH_LI_SEVEN                        0xA907 0  // ꤇
#define UC_KAYAH_LI_EIGHT                        0xA908 0  // ꤈
#define UC_KAYAH_LI_NINE                         0xA909 0  // ꤉
#define UC_KAYAH_LI_KA                           0xA90A 0  // ꤊ
#define UC_KAYAH_LI_KHA                          0xA90B 0  // ꤋ
#define UC_KAYAH_LI_GA                           0xA90C 0  // ꤌ
#define UC_KAYAH_LI_NGA                          0xA90D 0  // ꤍ
#define UC_KAYAH_LI_SA                           0xA90E 0  // ꤎ
#define UC_KAYAH_LI_SHA                          0xA90F 0  // ꤏ
#define UC_KAYAH_LI_ZA                           0xA910 0  // ꤐ
#define UC_KAYAH_LI_NYA                          0xA911 0  // ꤑ
#define UC_KAYAH_LI_TA                           0xA912 0  // ꤒ
#define UC_KAYAH_LI_HTA                          0xA913 0  // ꤓ
#define UC_KAYAH_LI_NA                           0xA914 0  // ꤔ
#define UC_KAYAH_LI_PA                           0xA915 0  // ꤕ
#define UC_KAYAH_LI_PHA                          0xA916 0  // ꤖ
#define UC_KAYAH_LI_MA                           0xA917 0  // ꤗ
#define UC_KAYAH_LI_DA                           0xA918 0  // ꤘ
#define UC_KAYAH_LI_BA                           0xA919 0  // ꤙ
#define UC_KAYAH_LI_RA                           0xA91A 0  // ꤚ
#define UC_KAYAH_LI_YA                           0xA91B 0  // ꤛ
#define UC_KAYAH_LI_LA                           0xA91C 0  // ꤜ
#define UC_KAYAH_LI_WA                           0xA91D 0  // ꤝ
#define UC_KAYAH_LI_THA                          0xA91E 0  // ꤞ
#define UC_KAYAH_LI_HA                           0xA91F 0  // ꤟ
#define UC_KAYAH_LI_VA                           0xA920 0  // ꤠ
#define UC_KAYAH_LI_CA                           0xA921 0  // ꤡ
#define UC_KAYAH_LI_A                            0xA922 0  // ꤢ
#define UC_KAYAH_LI_OE                           0xA923 0  // ꤣ
#define UC_KAYAH_LI_I                            0xA924 0  // ꤤ
#define UC_KAYAH_LI_OO                           0xA925 0  // ꤥ
#define UC_KAYAH_LI_VOWEL_UE                     0xA926 0  // ꤦ
#define UC_KAYAH_LI_VOWEL_E                      0xA927 0  // ꤧ
#define UC_KAYAH_LI_VOWEL_U                      0xA928 0  // ꤨ
#define UC_KAYAH_LI_VOWEL_EE                     0xA929 0  // ꤩ
#define UC_KAYAH_LI_VOWEL_O                      0xA92A 0  // ꤪ
#define UC_KAYAH_LI_TONE_PLOPHU                  0xA92B 0  // ꤫
#define UC_KAYAH_LI_TONE_CALYA                   0xA92C 0  // ꤬
#define UC_KAYAH_LI_TONE_CALYA_PLOPHU            0xA92D 0  // ꤭
#define UC_KAYAH_LI_SIGN_CWI                     0xA92E 0  // ꤮
#define UC_KAYAH_LI_SIGN_SHYA                    0xA92F 0  // ꤯
