/* khojki.h – Unicode constants for U+11200 … U+1124F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Khojki
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U11200.pdf
 
* Consistency Check:
* Total Defined Code Points: 65
* Total Significant Hex Values: 65
* Status: OK (Counts Match)

*/

#pragma once

#define UC_KHOJKI_A                              0x11200 0  // 𑈀
#define UC_KHOJKI_AA                             0x11201 0  // 𑈁
#define UC_KHOJKI_I                              0x11202 0  // 𑈂
#define UC_KHOJKI_U                              0x11203 0  // 𑈃
#define UC_KHOJKI_E                              0x11204 0  // 𑈄
#define UC_KHOJKI_AI                             0x11205 0  // 𑈅
#define UC_KHOJKI_O                              0x11206 0  // 𑈆
#define UC_KHOJKI_AU                             0x11207 0  // 𑈇
#define UC_KHOJKI_KA                             0x11208 0  // 𑈈
#define UC_KHOJKI_KHA                            0x11209 0  // 𑈉
#define UC_KHOJKI_GA                             0x1120A 0  // 𑈊
#define UC_KHOJKI_GGA                            0x1120B 0  // 𑈋
#define UC_KHOJKI_GHA                            0x1120C 0  // 𑈌
#define UC_KHOJKI_NGA                            0x1120D 0  // 𑈍
#define UC_KHOJKI_CA                             0x1120E 0  // 𑈎
#define UC_KHOJKI_CHA                            0x1120F 0  // 𑈏
#define UC_KHOJKI_JA                             0x11210 0  // 𑈐
#define UC_KHOJKI_JJA                            0x11211 0  // 𑈑
#define UC_KHOJKI_NYA                            0x11213 0  // 𑈓
#define UC_KHOJKI_TTA                            0x11214 0  // 𑈔
#define UC_KHOJKI_TTHA                           0x11215 0  // 𑈕
#define UC_KHOJKI_DDA                            0x11216 0  // 𑈖
#define UC_KHOJKI_DDHA                           0x11217 0  // 𑈗
#define UC_KHOJKI_NNA                            0x11218 0  // 𑈘
#define UC_KHOJKI_TA                             0x11219 0  // 𑈙
#define UC_KHOJKI_THA                            0x1121A 0  // 𑈚
#define UC_KHOJKI_DA                             0x1121B 0  // 𑈛
#define UC_KHOJKI_DDDA                           0x1121C 0  // 𑈜
#define UC_KHOJKI_DHA                            0x1121D 0  // 𑈝
#define UC_KHOJKI_NA                             0x1121E 0  // 𑈞
#define UC_KHOJKI_PA                             0x1121F 0  // 𑈟
#define UC_KHOJKI_PHA                            0x11220 0  // 𑈠
#define UC_KHOJKI_BA                             0x11221 0  // 𑈡
#define UC_KHOJKI_BBA                            0x11222 0  // 𑈢
#define UC_KHOJKI_BHA                            0x11223 0  // 𑈣
#define UC_KHOJKI_MA                             0x11224 0  // 𑈤
#define UC_KHOJKI_YA                             0x11225 0  // 𑈥
#define UC_KHOJKI_RA                             0x11226 0  // 𑈦
#define UC_KHOJKI_LA                             0x11227 0  // 𑈧
#define UC_KHOJKI_VA                             0x11228 0  // 𑈨
#define UC_KHOJKI_SA                             0x11229 0  // 𑈩
#define UC_KHOJKI_HA                             0x1122A 0  // 𑈪
#define UC_KHOJKI_LLA                            0x1122B 0  // 𑈫
#define UC_KHOJKI_VOWEL_SIGN_AA                  0x1122C 0  // 𑈬
#define UC_KHOJKI_VOWEL_SIGN_I                   0x1122D 0  // 𑈭
#define UC_KHOJKI_VOWEL_SIGN_II                  0x1122E 0  // 𑈮
#define UC_KHOJKI_VOWEL_SIGN_U                   0x1122F 0  // 𑈯
#define UC_KHOJKI_VOWEL_SIGN_E                   0x11230 0  // 𑈰
#define UC_KHOJKI_VOWEL_SIGN_AI                  0x11231 0  // 𑈱
#define UC_KHOJKI_VOWEL_SIGN_O                   0x11232 0  // 𑈲
#define UC_KHOJKI_VOWEL_SIGN_AU                  0x11233 0  // 𑈳
#define UC_KHOJKI_SIGN_ANUSVARA                  0x11234 0  // 𑈴
#define UC_KHOJKI_SIGN_VIRAMA                    0x11235 0  // 𑈵
#define UC_KHOJKI_SIGN_NUKTA                     0x11236 0  // 𑈶
#define UC_KHOJKI_SIGN_SHADDA                    0x11237 0  // 𑈷
#define UC_KHOJKI_DANDA                          0x11238 0  // 𑈸
#define UC_KHOJKI_DOUBLE_DANDA                   0x11239 0  // 𑈹
#define UC_KHOJKI_WORD_SEPARATOR                 0x1123A 0  // 𑈺
#define UC_KHOJKI_SECTION_MARK                   0x1123B 0  // 𑈻
#define UC_KHOJKI_DOUBLE_SECTION_MARK            0x1123C 0  // 𑈼
#define UC_KHOJKI_ABBREVIATION_SIGN              0x1123D 0  // 𑈽
#define UC_KHOJKI_SIGN_SUKUN                     0x1123E 0  // 𑈾
#define UC_KHOJKI_QA                             0x1123F 0  // 𑈿
#define UC_KHOJKI_SHORT_I                        0x11240 0  // 𑉀
#define UC_KHOJKI_VOWEL_SIGN_VOCALIC_R           0x11241 0  // 𑉁
