/* khudawadi.h – Unicode constants for U+112B0 … U+112FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Khudabadi (also Khudawadi ) is a script used to write the Sindhi
 * language , sometimes used by some Sindhi Hindus even in the
 * present-day. The script originates from Khudabad , a city in Sindh ,
 * and is named after it. Khudabadi is one of the four scripts used for
 * writing Sindhi, the others being Perso-Arabic , Khojki and Devanagari
 * script. It was used by Sindhi Workies (traders and merchants) to
 * record their information and rose to importance as the script began to
 * be used to record information kept secret from other non-Sindhi
 * groups.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Khudawadi
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U112B0.pdf
 
* Consistency Check:
* Total Defined Code Points: 69
* Total Significant Hex Values: 69
* Status: OK (Counts Match)

*/

#pragma once

#define UC_KHUDAWADI_A                           0x112B0 0  // 𑊰
#define UC_KHUDAWADI_AA                          0x112B1 0  // 𑊱
#define UC_KHUDAWADI_I                           0x112B2 0  // 𑊲
#define UC_KHUDAWADI_II                          0x112B3 0  // 𑊳
#define UC_KHUDAWADI_U                           0x112B4 0  // 𑊴
#define UC_KHUDAWADI_UU                          0x112B5 0  // 𑊵
#define UC_KHUDAWADI_E                           0x112B6 0  // 𑊶
#define UC_KHUDAWADI_AI                          0x112B7 0  // 𑊷
#define UC_KHUDAWADI_O                           0x112B8 0  // 𑊸
#define UC_KHUDAWADI_AU                          0x112B9 0  // 𑊹
#define UC_KHUDAWADI_KA                          0x112BA 0  // 𑊺
#define UC_KHUDAWADI_KHA                         0x112BB 0  // 𑊻
#define UC_KHUDAWADI_GA                          0x112BC 0  // 𑊼
#define UC_KHUDAWADI_GGA                         0x112BD 0  // 𑊽
#define UC_KHUDAWADI_GHA                         0x112BE 0  // 𑊾
#define UC_KHUDAWADI_NGA                         0x112BF 0  // 𑊿
#define UC_KHUDAWADI_CA                          0x112C0 0  // 𑋀
#define UC_KHUDAWADI_CHA                         0x112C1 0  // 𑋁
#define UC_KHUDAWADI_JA                          0x112C2 0  // 𑋂
#define UC_KHUDAWADI_JJA                         0x112C3 0  // 𑋃
#define UC_KHUDAWADI_JHA                         0x112C4 0  // 𑋄
#define UC_KHUDAWADI_NYA                         0x112C5 0  // 𑋅
#define UC_KHUDAWADI_TTA                         0x112C6 0  // 𑋆
#define UC_KHUDAWADI_TTHA                        0x112C7 0  // 𑋇
#define UC_KHUDAWADI_DDA                         0x112C8 0  // 𑋈
#define UC_KHUDAWADI_DDDA                        0x112C9 0  // 𑋉
#define UC_KHUDAWADI_RRA                         0x112CA 0  // 𑋊
#define UC_KHUDAWADI_DDHA                        0x112CB 0  // 𑋋
#define UC_KHUDAWADI_NNA                         0x112CC 0  // 𑋌
#define UC_KHUDAWADI_TA                          0x112CD 0  // 𑋍
#define UC_KHUDAWADI_THA                         0x112CE 0  // 𑋎
#define UC_KHUDAWADI_DA                          0x112CF 0  // 𑋏
#define UC_KHUDAWADI_DHA                         0x112D0 0  // 𑋐
#define UC_KHUDAWADI_NA                          0x112D1 0  // 𑋑
#define UC_KHUDAWADI_PA                          0x112D2 0  // 𑋒
#define UC_KHUDAWADI_PHA                         0x112D3 0  // 𑋓
#define UC_KHUDAWADI_BA                          0x112D4 0  // 𑋔
#define UC_KHUDAWADI_BBA                         0x112D5 0  // 𑋕
#define UC_KHUDAWADI_BHA                         0x112D6 0  // 𑋖
#define UC_KHUDAWADI_MA                          0x112D7 0  // 𑋗
#define UC_KHUDAWADI_YA                          0x112D8 0  // 𑋘
#define UC_KHUDAWADI_RA                          0x112D9 0  // 𑋙
#define UC_KHUDAWADI_LA                          0x112DA 0  // 𑋚
#define UC_KHUDAWADI_VA                          0x112DB 0  // 𑋛
#define UC_KHUDAWADI_SHA                         0x112DC 0  // 𑋜
#define UC_KHUDAWADI_SA                          0x112DD 0  // 𑋝
#define UC_KHUDAWADI_HA                          0x112DE 0  // 𑋞
#define UC_KHUDAWADI_SIGN_ANUSVARA               0x112DF 0  // 𑋟
#define UC_KHUDAWADI_VOWEL_SIGN_AA               0x112E0 0  // 𑋠
#define UC_KHUDAWADI_VOWEL_SIGN_I                0x112E1 0  // 𑋡
#define UC_KHUDAWADI_VOWEL_SIGN_II               0x112E2 0  // 𑋢
#define UC_KHUDAWADI_VOWEL_SIGN_U                0x112E3 0  // 𑋣
#define UC_KHUDAWADI_VOWEL_SIGN_UU               0x112E4 0  // 𑋤
#define UC_KHUDAWADI_VOWEL_SIGN_E                0x112E5 0  // 𑋥
#define UC_KHUDAWADI_VOWEL_SIGN_AI               0x112E6 0  // 𑋦
#define UC_KHUDAWADI_VOWEL_SIGN_O                0x112E7 0  // 𑋧
#define UC_KHUDAWADI_VOWEL_SIGN_AU               0x112E8 0  // 𑋨
#define UC_KHUDAWADI_SIGN_NUKTA                  0x112E9 0  // 𑋩
#define UC_KHUDAWADI_SIGN_VIRAMA                 0x112EA 0  // 𑋪
#define UC_KHUDAWADI_ZERO                        0x112F0 0  // 𑋰
#define UC_KHUDAWADI_ONE                         0x112F1 0  // 𑋱
#define UC_KHUDAWADI_TWO                         0x112F2 0  // 𑋲
#define UC_KHUDAWADI_THREE                       0x112F3 0  // 𑋳
#define UC_KHUDAWADI_FOUR                        0x112F4 0  // 𑋴
#define UC_KHUDAWADI_FIVE                        0x112F5 0  // 𑋵
#define UC_KHUDAWADI_SIX                         0x112F6 0  // 𑋶
#define UC_KHUDAWADI_SEVEN                       0x112F7 0  // 𑋷
#define UC_KHUDAWADI_EIGHT                       0x112F8 0  // 𑋸
#define UC_KHUDAWADI_NINE                        0x112F9 0  // 𑋹
