/* latin_extended_d.h – Unicode constants for U+A720 … U+A7FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Latin Extended-D is a Unicode block containing Latin characters for
 * phonetic, Mayanist , and Medieval transcription and notation systems.
 * 89 of the characters in this block are for medieval characters
 * proposed by the Medieval Unicode Font Initiative , many of which are
 * representative of scribal abbreviations used in Medieval manuscript
 * texts .
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Latin_Extended_D
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/UA720.pdf
 
* Consistency Check:
* Total Defined Code Points: 204
* Total Significant Hex Values: 204
* Status: OK (Counts Match)

*/

#pragma once

#define UC_LTD_MODIFIER_STRESS_AND_HIGH_TONE     0xA720 0  // ꜠
#define UC_LTD_MODIFIER_STRESS_AND_LOW_TONE      0xA721 0  // ꜡
#define UC_LTD_EGYPTOLOGICAL_ALEF                0xA723 0xA722  // ꜣ/Ꜣ
#define UC_LTD_EGYPTOLOGICAL_AIN                 0xA725 0xA724  // ꜥ/Ꜥ
#define UC_LTD_HENG                              0xA727 0xA726  // ꜧ/Ꜧ
#define UC_LTD_TZ                                0xA729 0xA728  // ꜩ/Ꜩ
#define UC_LTD_TRESILLO                          0xA72B 0xA72A  // ꜫ/Ꜫ
#define UC_LTD_CUATRILLO                         0xA72D 0xA72C  // ꜭ/Ꜭ
#define UC_LATIN_SMALL_LETTER_CUATRILLO_WITH_COMMA 0xA72F 0xA72E  // ꜯ/Ꜯ
#define UC_LTD_SMALL_CAPITAL_F                   0xA730 0  // ꜰ
#define UC_LTD_SMALL_CAPITAL_S                   0xA731 0  // ꜱ
#define UC_LTD_AA                                0xA733 0xA732  // ꜳ/Ꜳ
#define UC_LTD_AO                                0xA735 0xA734  // ꜵ/Ꜵ
#define UC_LTD_AU                                0xA737 0xA736  // ꜷ/Ꜷ
#define UC_LTD_AV                                0xA739 0xA738  // ꜹ/Ꜹ
#define UC_LTD_AV_HORIZONTAL_BAR                 0xA73B 0xA73A  // ꜻ/Ꜻ
#define UC_LTD_AY                                0xA73D 0xA73C  // ꜽ/Ꜽ
#define UC_LTD_REVERSED_C_DOT                    0xA73F 0xA73E  // ꜿ/Ꜿ
#define UC_LTD_K_STROKE                          0xA741 0xA740  // ꝁ/Ꝁ
#define UC_LTD_K_DIAGONAL_STROKE                 0xA743 0xA742  // ꝃ/Ꝃ
#define UC_LTD_K_STROKE_AND_DIAGONAL_STROKE      0xA745 0xA744  // ꝅ/Ꝅ
#define UC_LTD_BROKEN_L                          0xA747 0xA746  // ꝇ/Ꝇ
#define UC_LTD_L_HIGH_STROKE                     0xA749 0xA748  // ꝉ/Ꝉ
#define UC_LTD_O_LONG_STROKE_OVERLAY             0xA74B 0xA74A  // ꝋ/Ꝋ
#define UC_LTD_O_LOOP                            0xA74D 0xA74C  // ꝍ/Ꝍ
#define UC_LTD_OO                                0xA74F 0xA74E  // ꝏ/Ꝏ
#define UC_LTD_P_STROKE_THROUGH_DESCENDER        0xA751 0xA750  // ꝑ/Ꝑ
#define UC_LTD_P_FLOURISH                        0xA753 0xA752  // ꝓ/Ꝓ
#define UC_LTD_P_SQUIRREL_TAIL                   0xA755 0xA754  // ꝕ/Ꝕ
#define UC_LTD_Q_STROKE_THROUGH_DESCENDER        0xA757 0xA756  // ꝗ/Ꝗ
#define UC_LTD_Q_DIAGONAL_STROKE                 0xA759 0xA758  // ꝙ/Ꝙ
#define UC_LTD_R_ROTUNDA                         0xA75B 0xA75A  // ꝛ/Ꝛ
#define UC_LTD_RUM_ROTUNDA                       0xA75D 0xA75C  // ꝝ/Ꝝ
#define UC_LTD_V_DIAGONAL_STROKE                 0xA75F 0xA75E  // ꝟ/Ꝟ
#define UC_LTD_VY                                0xA761 0xA760  // ꝡ/Ꝡ
#define UC_LTD_VISIGOTHIC_Z                      0xA763 0xA762  // ꝣ/Ꝣ
#define UC_LTD_THORN_STROKE                      0xA765 0xA764  // ꝥ/Ꝥ
#define UC_LTD_THORN_STROKE_THROUGH_DESCENDER    0xA767 0xA766  // ꝧ/Ꝧ
#define UC_LTD_VEND                              0xA769 0xA768  // ꝩ/Ꝩ
#define UC_LTD_ET                                0xA76B 0xA76A  // ꝫ/Ꝫ
#define UC_LTD_IS                                0xA76D 0xA76C  // ꝭ/Ꝭ
#define UC_LTD_CON                               0xA76F 0xA76E  // ꝯ/Ꝯ
#define UC_LTD_MODIFIER_US                       0xA770 0  // ꝰ
#define UC_LTD_SMALL_DUM                         0xA771 0  // ꝱ
#define UC_LTD_SMALL_LUM                         0xA772 0  // ꝲ
#define UC_LTD_SMALL_MUM                         0xA773 0  // ꝳ
#define UC_LTD_SMALL_NUM                         0xA774 0  // ꝴ
#define UC_LTD_SMALL_RUM                         0xA775 0  // ꝵ
#define UC_LTD_SMALL_CAPITAL_RUM                 0xA776 0  // ꝶ
#define UC_LTD_SMALL_TUM                         0xA777 0  // ꝷ
#define UC_LTD_SMALL_UM                          0xA778 0  // ꝸ
#define UC_LTD_INSULAR_D                         0xA77A 0xA779  // ꝺ/Ꝺ
#define UC_LTD_INSULAR_F                         0xA77C 0xA77B  // ꝼ/Ꝼ
#define UC_LTD_CAPITAL_INSULAR_G                 0xA77D 0  // Ᵹ
#define UC_LTD_TURNED_INSULAR_G                  0xA77F 0xA77E  // ꝿ/Ꝿ
#define UC_LTD_TURNED_L                          0xA781 0xA780  // ꞁ/Ꞁ
#define UC_LTD_INSULAR_R                         0xA783 0xA782  // ꞃ/Ꞃ
#define UC_LTD_INSULAR_S                         0xA785 0xA784  // ꞅ/Ꞅ
#define UC_LTD_INSULAR_T                         0xA787 0xA786  // ꞇ/Ꞇ
#define UC_LTD_MODIFIER_LOW_CIRCUMFLEX_ACCENT    0xA788 0  // ꞈ
#define UC_LTD_MODIFIER_COLON                    0xA789 0  // ꞉
#define UC_LTD_MODIFIER_SHORT_EQUALS_SIGN        0xA78A 0  // ꞊
#define UC_LTD_SALTILLO                          0xA78C 0xA78B  // ꞌ/Ꞌ
#define UC_LTD_CAPITAL_TURNED_H                  0xA78D 0  // Ɥ
#define UC_LTD_SMALL_L_RETROFLEX_HOOK_AND_BELT   0xA78E 0  // ꞎ
#define UC_LTD_SINOLOGICAL_DOT                   0xA78F 0  // ꞏ
#define UC_LTD_N_DESCENDER                       0xA791 0xA790  // ꞑ/Ꞑ
#define UC_LTD_C_BAR                             0xA793 0xA792  // ꞓ/Ꞓ
#define UC_LTD_C_PALATAL_HOOK                    0xA794 0xA7C4  // ꞔ/Ꞔ
#define UC_LTD_SMALL_H_PALATAL_HOOK              0xA795 0  // ꞕ
#define UC_LTD_B_FLOURISH                        0xA797 0xA796  // ꞗ/Ꞗ
#define UC_LTD_F_STROKE                          0xA799 0xA798  // ꞙ/Ꞙ
#define UC_LTD_VOLAPUK_AE                        0xA79B 0xA79A  // ꞛ/Ꞛ
#define UC_LTD_VOLAPUK_OE                        0xA79D 0xA79C  // ꞝ/Ꞝ
#define UC_LTD_VOLAPUK_UE                        0xA79F 0xA79E  // ꞟ/Ꞟ
#define UC_LTD_G_OBLIQUE_STROKE                  0xA7A1 0xA7A0  // ꞡ/Ꞡ
#define UC_LTD_K_OBLIQUE_STROKE                  0xA7A3 0xA7A2  // ꞣ/Ꞣ
#define UC_LTD_N_OBLIQUE_STROKE                  0xA7A5 0xA7A4  // ꞥ/Ꞥ
#define UC_LTD_R_OBLIQUE_STROKE                  0xA7A7 0xA7A6  // ꞧ/Ꞧ
#define UC_LTD_S_OBLIQUE_STROKE                  0xA7A9 0xA7A8  // ꞩ/Ꞩ
#define UC_LTD_CAPITAL_H_HOOK                    0xA7AA 0  // Ɦ
#define UC_LTD_CAPITAL_REVERSED_OPEN_E           0xA7AB 0  // Ɜ
#define UC_LTD_CAPITAL_SC_G                      0xA7AC 0  // Ɡ
#define UC_LTD_CAPITAL_L_BELT                    0xA7AD 0  // Ɬ
#define UC_LTD_CAPITAL_SMALL_CAPITAL_I           0xA7AE 0  // Ɪ
#define UC_LTD_SMALL_CAPITAL_Q                   0xA7AF 0  // ꞯ
#define UC_LTD_CAPITAL_TURNED_K                  0xA7B0 0  // Ʞ
#define UC_LTD_CAPITAL_TURNED_T                  0xA7B1 0  // Ʇ
#define UC_LTD_CAPITAL_J_CROSSED_TAIL            0xA7B2 0  // Ʝ
#define UC_LTD_CAPITAL_CHI                       0xA7B3 0  // Ꭓ
#define UC_LTD_BETA                              0xA7B5 0xA7B4  // ꞵ/Ꞵ
#define UC_LTD_OMEGA                             0xA7B7 0xA7B6  // ꞷ/Ꞷ
#define UC_LTD_U_STROKE                          0xA7B9 0xA7B8  // ꞹ/Ꞹ
#define UC_LTD_GLOTTAL_A                         0xA7BB 0xA7BA  // ꞻ/Ꞻ
#define UC_LTD_GLOTTAL_I                         0xA7BD 0xA7BC  // ꞽ/Ꞽ
#define UC_LTD_GLOTTAL_U                         0xA7BF 0xA7BE  // ꞿ/Ꞿ
#define UC_LTD_OLD_POLISH_O                      0xA7C1 0xA7C0  // ꟁ/Ꟁ
#define UC_LTD_ANGLICANA_W                       0xA7C3 0xA7C2  // ꟃ/Ꟃ
#define UC_LTD_CAPITAL_S_HOOK                    0xA7C5 0  // Ʂ
#define UC_LTD_CAPITAL_Z_PALATAL_HOOK            0xA7C6 0  // Ᶎ
#define UC_LTD_D_SHORT_STROKE_OVERLAY            0xA7C8 0xA7C7  // ꟈ/Ꟈ
#define UC_LTD_S_SHORT_STROKE_OVERLAY            0xA7CA 0xA7C9  // ꟊ/Ꟊ
#define UC_LTD_CAPITAL_RAMS_HORN                 0xA7CB 0  // Ɤ
#define UC_LTD_S_DIAGONAL_STROKE                 0xA7CD 0xA7CC  // ꟍ/Ꟍ
#define UC_LTD_PHARYNGEAL_VOICED_FRICATIVE       0xA7CF 0xA7CE  // ꟏/꟎
#define UC_LTD_CLOSED_INSULAR_G                  0xA7D1 0xA7D0  // ꟑ/Ꟑ
#define UC_LTD_DOUBLE_THORN                      0xA7D3 0xA7D2  // ꟓ/꟒
#define UC_LTD_DOUBLE_WYNN                       0xA7D5 0xA7D4  // ꟕ/꟔
#define UC_LTD_MIDDLE_SCOTS_S                    0xA7D7 0xA7D6  // ꟗ/Ꟗ
#define UC_LTD_SIGMOID_S                         0xA7D9 0xA7D8  // ꟙ/Ꟙ
#define UC_LTD_LAMBDA                            0xA7DB 0xA7DA  // ꟛ/Ꟛ
#define UC_LTD_CAPITAL_LAMBDA_STROKE             0xA7DC 0  // Ƛ
#define UC_LTD_MODIFIER_CAPITAL_S                0xA7F1 0  // ꟱
#define UC_LTD_MODIFIER_CAPITAL_C                0xA7F2 0  // ꟲ
#define UC_LTD_MODIFIER_CAPITAL_F                0xA7F3 0  // ꟳ
#define UC_LTD_MODIFIER_CAPITAL_Q                0xA7F4 0  // ꟴ
#define UC_LTD_REVERSED_HALF_H                   0xA7F6 0xA7F5  // ꟶ/Ꟶ
#define UC_LTD_EPIGRAPHIC_SIDEWAYS_I             0xA7F7 0  // ꟷ
#define UC_LTD_MODIFIER_CAPITAL_H_STROKE         0xA7F8 0  // ꟸ
#define UC_LTD_MODIFIER_SMALL_LIGATURE_OE        0xA7F9 0  // ꟹ
#define UC_LTD_SMALL_CAPITAL_TURNED_M            0xA7FA 0  // ꟺ
#define UC_LTD_EPIGRAPHIC_REVERSED_F             0xA7FB 0  // ꟻ
#define UC_LTD_EPIGRAPHIC_REVERSED_P             0xA7FC 0  // ꟼ
#define UC_LTD_EPIGRAPHIC_INVERTED_M             0xA7FD 0  // ꟽ
#define UC_LTD_EPIGRAPHIC_I_LONGA                0xA7FE 0  // ꟾ
#define UC_LTD_EPIGRAPHIC_ARCHAIC_M              0xA7FF 0  // ꟿ
