/* latin_extended_f.h – Unicode constants for U+10780 … U+107BF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Latin_Extended_F
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U10780.pdf
 
* Consistency Check:
* Total Defined Code Points: 57
* Total Significant Hex Values: 57
* Status: OK (Counts Match)

*/

#pragma once

#define UC_MODIFIER_SMALL_CAPITAL_AA             0x10780 0  // 𐞀
#define UC_MODIFIER_SUPERSC_TRIANGULAR_COLON     0x10781 0  // 𐞁
#define UC_MODIFIER_SUPERSC_HALF_TRIANGULAR_COLON 0x10782 0  // 𐞂
#define UC_MODIFIER_SMALL_AE                     0x10783 0  // 𐞃
#define UC_MODIFIER_SMALL_CAPITAL_B              0x10784 0  // 𐞄
#define UC_MODIFIER_SMALL_B_HOOK                 0x10785 0  // 𐞅
#define UC_MODIFIER_SMALL_DZ_DIGRAPH             0x10787 0  // 𐞇
#define UC_MODIFIER_SMALL_DZ_DIGRAPH_RETROFLEX_HOOK 0x10788 0  // 𐞈
#define UC_MODIFIER_SMALL_DZ_DIGRAPH_CURL        0x10789 0  // 𐞉
#define UC_MODIFIER_SMALL_DEZH_DIGRAPH           0x1078A 0  // 𐞊
#define UC_MODIFIER_SMALL_D_TAIL                 0x1078B 0  // 𐞋
#define UC_MODIFIER_SMALL_D_HOOK                 0x1078C 0  // 𐞌
#define UC_MODIFIER_SMALL_D_HOOK_AND_TAIL        0x1078D 0  // 𐞍
#define UC_MODIFIER_SMALL_REVERSED_E             0x1078E 0  // 𐞎
#define UC_MODIFIER_SMALL_CLOSED_REVERSED_OPEN_E 0x1078F 0  // 𐞏
#define UC_MODIFIER_SMALL_FENG_DIGRAPH           0x10790 0  // 𐞐
#define UC_MODIFIER_SMALL_RAMS_HORN              0x10791 0  // 𐞑
#define UC_MODIFIER_SMALL_CAPITAL_G              0x10792 0  // 𐞒
#define UC_MODIFIER_SMALL_G_HOOK                 0x10793 0  // 𐞓
#define UC_MODIFIER_SMALL_CAPITAL_G_HOOK         0x10794 0  // 𐞔
#define UC_MODIFIER_SMALL_H_STROKE               0x10795 0  // 𐞕
#define UC_MODIFIER_SMALL_CAPITAL_H              0x10796 0  // 𐞖
#define UC_MODIFIER_SMALL_HENG_HOOK              0x10797 0  // 𐞗
#define UC_MODIFIER_SMALL_DOTLESS_J_STROKE_AND_HOOK 0x10798 0  // 𐞘
#define UC_MODIFIER_SMALL_LS_DIGRAPH             0x10799 0  // 𐞙
#define UC_MODIFIER_SMALL_LZ_DIGRAPH             0x1079A 0  // 𐞚
#define UC_MODIFIER_SMALL_L_BELT                 0x1079B 0  // 𐞛
#define UC_MODIFIER_SMALL_CAPITAL_L_BELT         0x1079C 0  // 𐞜
#define UC_MODIFIER_SMALL_L_RETROFLEX_HOOK_AND_BELT 0x1079D 0  // 𐞝
#define UC_MODIFIER_SMALL_LEZH                   0x1079E 0  // 𐞞
#define UC_MODIFIER_SMALL_LEZH_RETROFLEX_HOOK    0x1079F 0  // 𐞟
#define UC_MODIFIER_SMALL_TURNED_Y               0x107A0 0  // 𐞠
#define UC_MODIFIER_SMALL_TURNED_Y_BELT          0x107A1 0  // 𐞡
#define UC_MODIFIER_SMALL_O_STROKE               0x107A2 0  // 𐞢
#define UC_MODIFIER_SMALL_CAPITAL_OE             0x107A3 0  // 𐞣
#define UC_MODIFIER_SMALL_CLOSED_OMEGA           0x107A4 0  // 𐞤
#define UC_MODIFIER_SMALL_Q                      0x107A5 0  // 𐞥
#define UC_MODIFIER_SMALL_TURNED_R_LONG_LEG      0x107A6 0  // 𐞦
#define UC_MODIFIER_SMALL_TURNED_R_LONG_LEG_AND_RETROFLEX_HOOK 0x107A7 0  // 𐞧
#define UC_MODIFIER_SMALL_R_TAIL                 0x107A8 0  // 𐞨
#define UC_MODIFIER_SMALL_R_FISHHOOK             0x107A9 0  // 𐞩
#define UC_MODIFIER_SMALL_CAPITAL_R              0x107AA 0  // 𐞪
#define UC_MODIFIER_SMALL_TC_DIGRAPH_CURL        0x107AB 0  // 𐞫
#define UC_MODIFIER_SMALL_TS_DIGRAPH             0x107AC 0  // 𐞬
#define UC_MODIFIER_SMALL_TS_DIGRAPH_RETROFLEX_HOOK 0x107AD 0  // 𐞭
#define UC_MODIFIER_SMALL_TESH_DIGRAPH           0x107AE 0  // 𐞮
#define UC_MODIFIER_SMALL_T_RETROFLEX_HOOK       0x107AF 0  // 𐞯
#define UC_MODIFIER_SMALL_V_RIGHT_HOOK           0x107B0 0  // 𐞰
#define UC_MODIFIER_SMALL_CAPITAL_Y              0x107B2 0  // 𐞲
#define UC_MODIFIER_GLOTTAL_STOP_STROKE          0x107B3 0  // 𐞳
#define UC_MODIFIER_REVERSED_GLOTTAL_STOP_STROKE 0x107B4 0  // 𐞴
#define UC_MODIFIER_BILABIAL_CLICK               0x107B5 0  // 𐞵
#define UC_MODIFIER_DENTAL_CLICK                 0x107B6 0  // 𐞶
#define UC_MODIFIER_LATERAL_CLICK                0x107B7 0  // 𐞷
#define UC_MODIFIER_ALVEOLAR_CLICK               0x107B8 0  // 𐞸
#define UC_MODIFIER_RETROFLEX_CLICK_RETROFLEX_HOOK 0x107B9 0  // 𐞹
#define UC_MODIFIER_SMALL_S_CURL                 0x107BA 0  // 𐞺
