/* linear_a.h – Unicode constants for U+10600 … U+1077F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Linear A is a writing system that was used by the Minoans of Crete
 * from 1800 BC to 1450 BC. Linear A was the primary script used in
 * palace and religious writings of the Minoan civilization. It evolved
 * into Linear B , which was used by the Mycenaeans to write an early
 * form of Greek . It was discovered by the archaeologist Sir Arthur
 * Evans in 1900. No texts in Linear A have yet been deciphered . Evans
 * named the script "Linear" because its characters consisted simply of
 * lines inscribed in clay, in contrast to the more pictographic
 * characters in Cretan hieroglyphs – likewise undeciphered – that were
 * used during the same period.
 * Linear A belongs to a group of scripts that evolved independently of
 * the Egyptian and Mesopotamian systems. During the second millennium
 * BC, there were four major branches: Linear A, Linear B , Cypro-Minoan
 * , and Cretan hieroglyphic . In the 1950s, Linear B was deciphered and
 * found to have an underlying language of Mycenaean Greek . Linear A
 * shares many glyphs and alloglyphs with Linear B, and the syllabic
 * glyphs are thought to notate similar syllabic values, but none of the
 * proposed readings lead to a language that scholars can understand.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Linear_A
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U10600.pdf
 
* Consistency Check:
* Total Defined Code Points: 341
* Total Significant Hex Values: 341
* Status: OK (Counts Match)

*/

#pragma once

#define UC_LINEAR_A_SIGN_AB001                   0x10600 0  // 𐘀
#define UC_LINEAR_A_SIGN_AB002                   0x10601 0  // 𐘁
#define UC_LINEAR_A_SIGN_AB003                   0x10602 0  // 𐘂
#define UC_LINEAR_A_SIGN_AB004                   0x10603 0  // 𐘃
#define UC_LINEAR_A_SIGN_AB005                   0x10604 0  // 𐘄
#define UC_LINEAR_A_SIGN_AB006                   0x10605 0  // 𐘅
#define UC_LINEAR_A_SIGN_AB007                   0x10606 0  // 𐘆
#define UC_LINEAR_A_SIGN_AB008                   0x10607 0  // 𐘇
#define UC_LINEAR_A_SIGN_AB009                   0x10608 0  // 𐘈
#define UC_LINEAR_A_SIGN_AB010                   0x10609 0  // 𐘉
#define UC_LINEAR_A_SIGN_AB011                   0x1060A 0  // 𐘊
#define UC_LINEAR_A_SIGN_AB013                   0x1060B 0  // 𐘋
#define UC_LINEAR_A_SIGN_AB016                   0x1060C 0  // 𐘌
#define UC_LINEAR_A_SIGN_AB017                   0x1060D 0  // 𐘍
#define UC_LINEAR_A_SIGN_AB020                   0x1060E 0  // 𐘎
#define UC_LINEAR_A_SIGN_AB021                   0x1060F 0  // 𐘏
#define UC_LINEAR_A_SIGN_AB021F                  0x10610 0  // 𐘐
#define UC_LINEAR_A_SIGN_AB021M                  0x10611 0  // 𐘑
#define UC_LINEAR_A_SIGN_AB022                   0x10612 0  // 𐘒
#define UC_LINEAR_A_SIGN_AB022F                  0x10613 0  // 𐘓
#define UC_LINEAR_A_SIGN_AB022M                  0x10614 0  // 𐘔
#define UC_LINEAR_A_SIGN_AB023                   0x10615 0  // 𐘕
#define UC_LINEAR_A_SIGN_AB023M                  0x10616 0  // 𐘖
#define UC_LINEAR_A_SIGN_AB024                   0x10617 0  // 𐘗
#define UC_LINEAR_A_SIGN_AB026                   0x10618 0  // 𐘘
#define UC_LINEAR_A_SIGN_AB027                   0x10619 0  // 𐘙
#define UC_LINEAR_A_SIGN_AB028                   0x1061A 0  // 𐘚
#define UC_LINEAR_A_SIGN_A028B                   0x1061B 0  // 𐘛
#define UC_LINEAR_A_SIGN_AB029                   0x1061C 0  // 𐘜
#define UC_LINEAR_A_SIGN_AB030                   0x1061D 0  // 𐘝
#define UC_LINEAR_A_SIGN_AB031                   0x1061E 0  // 𐘞
#define UC_LINEAR_A_SIGN_AB034                   0x1061F 0  // 𐘟
#define UC_LINEAR_A_SIGN_AB037                   0x10620 0  // 𐘠
#define UC_LINEAR_A_SIGN_AB038                   0x10621 0  // 𐘡
#define UC_LINEAR_A_SIGN_AB039                   0x10622 0  // 𐘢
#define UC_LINEAR_A_SIGN_AB040                   0x10623 0  // 𐘣
#define UC_LINEAR_A_SIGN_AB041                   0x10624 0  // 𐘤
#define UC_LINEAR_A_SIGN_AB044                   0x10625 0  // 𐘥
#define UC_LINEAR_A_SIGN_AB045                   0x10626 0  // 𐘦
#define UC_LINEAR_A_SIGN_AB046                   0x10627 0  // 𐘧
#define UC_LINEAR_A_SIGN_AB047                   0x10628 0  // 𐘨
#define UC_LINEAR_A_SIGN_AB048                   0x10629 0  // 𐘩
#define UC_LINEAR_A_SIGN_AB049                   0x1062A 0  // 𐘪
#define UC_LINEAR_A_SIGN_AB050                   0x1062B 0  // 𐘫
#define UC_LINEAR_A_SIGN_AB051                   0x1062C 0  // 𐘬
#define UC_LINEAR_A_SIGN_AB053                   0x1062D 0  // 𐘭
#define UC_LINEAR_A_SIGN_AB054                   0x1062E 0  // 𐘮
#define UC_LINEAR_A_SIGN_AB055                   0x1062F 0  // 𐘯
#define UC_LINEAR_A_SIGN_AB056                   0x10630 0  // 𐘰
#define UC_LINEAR_A_SIGN_AB057                   0x10631 0  // 𐘱
#define UC_LINEAR_A_SIGN_AB058                   0x10632 0  // 𐘲
#define UC_LINEAR_A_SIGN_AB059                   0x10633 0  // 𐘳
#define UC_LINEAR_A_SIGN_AB060                   0x10634 0  // 𐘴
#define UC_LINEAR_A_SIGN_AB061                   0x10635 0  // 𐘵
#define UC_LINEAR_A_SIGN_AB065                   0x10636 0  // 𐘶
#define UC_LINEAR_A_SIGN_AB066                   0x10637 0  // 𐘷
#define UC_LINEAR_A_SIGN_AB067                   0x10638 0  // 𐘸
#define UC_LINEAR_A_SIGN_AB069                   0x10639 0  // 𐘹
#define UC_LINEAR_A_SIGN_AB070                   0x1063A 0  // 𐘺
#define UC_LINEAR_A_SIGN_AB073                   0x1063B 0  // 𐘻
#define UC_LINEAR_A_SIGN_AB074                   0x1063C 0  // 𐘼
#define UC_LINEAR_A_SIGN_AB076                   0x1063D 0  // 𐘽
#define UC_LINEAR_A_SIGN_AB077                   0x1063E 0  // 𐘾
#define UC_LINEAR_A_SIGN_AB078                   0x1063F 0  // 𐘿
#define UC_LINEAR_A_SIGN_AB079                   0x10640 0  // 𐙀
#define UC_LINEAR_A_SIGN_AB080                   0x10641 0  // 𐙁
#define UC_LINEAR_A_SIGN_AB081                   0x10642 0  // 𐙂
#define UC_LINEAR_A_SIGN_AB082                   0x10643 0  // 𐙃
#define UC_LINEAR_A_SIGN_AB085                   0x10644 0  // 𐙄
#define UC_LINEAR_A_SIGN_AB086                   0x10645 0  // 𐙅
#define UC_LINEAR_A_SIGN_AB087                   0x10646 0  // 𐙆
#define UC_LINEAR_A_SIGN_A100_102                0x10647 0  // 𐙇
#define UC_LINEAR_A_SIGN_AB118                   0x10648 0  // 𐙈
#define UC_LINEAR_A_SIGN_AB120                   0x10649 0  // 𐙉
#define UC_LINEAR_A_SIGN_A120B                   0x1064A 0  // 𐙊
#define UC_LINEAR_A_SIGN_AB122                   0x1064B 0  // 𐙋
#define UC_LINEAR_A_SIGN_AB123                   0x1064C 0  // 𐙌
#define UC_LINEAR_A_SIGN_AB131A                  0x1064D 0  // 𐙍
#define UC_LINEAR_A_SIGN_AB131B                  0x1064E 0  // 𐙎
#define UC_LINEAR_A_SIGN_A131C                   0x1064F 0  // 𐙏
#define UC_LINEAR_A_SIGN_AB164                   0x10650 0  // 𐙐
#define UC_LINEAR_A_SIGN_AB171                   0x10651 0  // 𐙑
#define UC_LINEAR_A_SIGN_AB180                   0x10652 0  // 𐙒
#define UC_LINEAR_A_SIGN_AB188                   0x10653 0  // 𐙓
#define UC_LINEAR_A_SIGN_AB191                   0x10654 0  // 𐙔
#define UC_LINEAR_A_SIGN_A301                    0x10655 0  // 𐙕
#define UC_LINEAR_A_SIGN_A302                    0x10656 0  // 𐙖
#define UC_LINEAR_A_SIGN_A303                    0x10657 0  // 𐙗
#define UC_LINEAR_A_SIGN_A304                    0x10658 0  // 𐙘
#define UC_LINEAR_A_SIGN_A305                    0x10659 0  // 𐙙
#define UC_LINEAR_A_SIGN_A306                    0x1065A 0  // 𐙚
#define UC_LINEAR_A_SIGN_A307                    0x1065B 0  // 𐙛
#define UC_LINEAR_A_SIGN_A308                    0x1065C 0  // 𐙜
#define UC_LINEAR_A_SIGN_A309A                   0x1065D 0  // 𐙝
#define UC_LINEAR_A_SIGN_A309B                   0x1065E 0  // 𐙞
#define UC_LINEAR_A_SIGN_A309C                   0x1065F 0  // 𐙟
#define UC_LINEAR_A_SIGN_A310                    0x10660 0  // 𐙠
#define UC_LINEAR_A_SIGN_A311                    0x10661 0  // 𐙡
#define UC_LINEAR_A_SIGN_A312                    0x10662 0  // 𐙢
#define UC_LINEAR_A_SIGN_A313A                   0x10663 0  // 𐙣
#define UC_LINEAR_A_SIGN_A313B                   0x10664 0  // 𐙤
#define UC_LINEAR_A_SIGN_A313C                   0x10665 0  // 𐙥
#define UC_LINEAR_A_SIGN_A314                    0x10666 0  // 𐙦
#define UC_LINEAR_A_SIGN_A315                    0x10667 0  // 𐙧
#define UC_LINEAR_A_SIGN_A316                    0x10668 0  // 𐙨
#define UC_LINEAR_A_SIGN_A317                    0x10669 0  // 𐙩
#define UC_LINEAR_A_SIGN_A318                    0x1066A 0  // 𐙪
#define UC_LINEAR_A_SIGN_A319                    0x1066B 0  // 𐙫
#define UC_LINEAR_A_SIGN_A320                    0x1066C 0  // 𐙬
#define UC_LINEAR_A_SIGN_A321                    0x1066D 0  // 𐙭
#define UC_LINEAR_A_SIGN_A322                    0x1066E 0  // 𐙮
#define UC_LINEAR_A_SIGN_A323                    0x1066F 0  // 𐙯
#define UC_LINEAR_A_SIGN_A324                    0x10670 0  // 𐙰
#define UC_LINEAR_A_SIGN_A325                    0x10671 0  // 𐙱
#define UC_LINEAR_A_SIGN_A326                    0x10672 0  // 𐙲
#define UC_LINEAR_A_SIGN_A327                    0x10673 0  // 𐙳
#define UC_LINEAR_A_SIGN_A328                    0x10674 0  // 𐙴
#define UC_LINEAR_A_SIGN_A329                    0x10675 0  // 𐙵
#define UC_LINEAR_A_SIGN_A330                    0x10676 0  // 𐙶
#define UC_LINEAR_A_SIGN_A331                    0x10677 0  // 𐙷
#define UC_LINEAR_A_SIGN_A332                    0x10678 0  // 𐙸
#define UC_LINEAR_A_SIGN_A333                    0x10679 0  // 𐙹
#define UC_LINEAR_A_SIGN_A334                    0x1067A 0  // 𐙺
#define UC_LINEAR_A_SIGN_A335                    0x1067B 0  // 𐙻
#define UC_LINEAR_A_SIGN_A336                    0x1067C 0  // 𐙼
#define UC_LINEAR_A_SIGN_A337                    0x1067D 0  // 𐙽
#define UC_LINEAR_A_SIGN_A338                    0x1067E 0  // 𐙾
#define UC_LINEAR_A_SIGN_A339                    0x1067F 0  // 𐙿
#define UC_LINEAR_A_SIGN_A340                    0x10680 0  // 𐚀
#define UC_LINEAR_A_SIGN_A341                    0x10681 0  // 𐚁
#define UC_LINEAR_A_SIGN_A342                    0x10682 0  // 𐚂
#define UC_LINEAR_A_SIGN_A343                    0x10683 0  // 𐚃
#define UC_LINEAR_A_SIGN_A344                    0x10684 0  // 𐚄
#define UC_LINEAR_A_SIGN_A345                    0x10685 0  // 𐚅
#define UC_LINEAR_A_SIGN_A346                    0x10686 0  // 𐚆
#define UC_LINEAR_A_SIGN_A347                    0x10687 0  // 𐚇
#define UC_LINEAR_A_SIGN_A348                    0x10688 0  // 𐚈
#define UC_LINEAR_A_SIGN_A349                    0x10689 0  // 𐚉
#define UC_LINEAR_A_SIGN_A350                    0x1068A 0  // 𐚊
#define UC_LINEAR_A_SIGN_A351                    0x1068B 0  // 𐚋
#define UC_LINEAR_A_SIGN_A352                    0x1068C 0  // 𐚌
#define UC_LINEAR_A_SIGN_A353                    0x1068D 0  // 𐚍
#define UC_LINEAR_A_SIGN_A354                    0x1068E 0  // 𐚎
#define UC_LINEAR_A_SIGN_A355                    0x1068F 0  // 𐚏
#define UC_LINEAR_A_SIGN_A356                    0x10690 0  // 𐚐
#define UC_LINEAR_A_SIGN_A357                    0x10691 0  // 𐚑
#define UC_LINEAR_A_SIGN_A358                    0x10692 0  // 𐚒
#define UC_LINEAR_A_SIGN_A359                    0x10693 0  // 𐚓
#define UC_LINEAR_A_SIGN_A360                    0x10694 0  // 𐚔
#define UC_LINEAR_A_SIGN_A361                    0x10695 0  // 𐚕
#define UC_LINEAR_A_SIGN_A362                    0x10696 0  // 𐚖
#define UC_LINEAR_A_SIGN_A363                    0x10697 0  // 𐚗
#define UC_LINEAR_A_SIGN_A364                    0x10698 0  // 𐚘
#define UC_LINEAR_A_SIGN_A365                    0x10699 0  // 𐚙
#define UC_LINEAR_A_SIGN_A366                    0x1069A 0  // 𐚚
#define UC_LINEAR_A_SIGN_A367                    0x1069B 0  // 𐚛
#define UC_LINEAR_A_SIGN_A368                    0x1069C 0  // 𐚜
#define UC_LINEAR_A_SIGN_A369                    0x1069D 0  // 𐚝
#define UC_LINEAR_A_SIGN_A370                    0x1069E 0  // 𐚞
#define UC_LINEAR_A_SIGN_A371                    0x1069F 0  // 𐚟
#define UC_LINEAR_A_SIGN_A400_VAS                0x106A0 0  // 𐚠
#define UC_LINEAR_A_SIGN_A401_VAS                0x106A1 0  // 𐚡
#define UC_LINEAR_A_SIGN_A402_VAS                0x106A2 0  // 𐚢
#define UC_LINEAR_A_SIGN_A403_VAS                0x106A3 0  // 𐚣
#define UC_LINEAR_A_SIGN_A404_VAS                0x106A4 0  // 𐚤
#define UC_LINEAR_A_SIGN_A405_VAS                0x106A5 0  // 𐚥
#define UC_LINEAR_A_SIGN_A406_VAS                0x106A6 0  // 𐚦
#define UC_LINEAR_A_SIGN_A407_VAS                0x106A7 0  // 𐚧
#define UC_LINEAR_A_SIGN_A408_VAS                0x106A8 0  // 𐚨
#define UC_LINEAR_A_SIGN_A409_VAS                0x106A9 0  // 𐚩
#define UC_LINEAR_A_SIGN_A410_VAS                0x106AA 0  // 𐚪
#define UC_LINEAR_A_SIGN_A411_VAS                0x106AB 0  // 𐚫
#define UC_LINEAR_A_SIGN_A412_VAS                0x106AC 0  // 𐚬
#define UC_LINEAR_A_SIGN_A413_VAS                0x106AD 0  // 𐚭
#define UC_LINEAR_A_SIGN_A414_VAS                0x106AE 0  // 𐚮
#define UC_LINEAR_A_SIGN_A415_VAS                0x106AF 0  // 𐚯
#define UC_LINEAR_A_SIGN_A416_VAS                0x106B0 0  // 𐚰
#define UC_LINEAR_A_SIGN_A417_VAS                0x106B1 0  // 𐚱
#define UC_LINEAR_A_SIGN_A418_VAS                0x106B2 0  // 𐚲
#define UC_LINEAR_A_SIGN_A501                    0x106B3 0  // 𐚳
#define UC_LINEAR_A_SIGN_A502                    0x106B4 0  // 𐚴
#define UC_LINEAR_A_SIGN_A503                    0x106B5 0  // 𐚵
#define UC_LINEAR_A_SIGN_A504                    0x106B6 0  // 𐚶
#define UC_LINEAR_A_SIGN_A505                    0x106B7 0  // 𐚷
#define UC_LINEAR_A_SIGN_A506                    0x106B8 0  // 𐚸
#define UC_LINEAR_A_SIGN_A508                    0x106B9 0  // 𐚹
#define UC_LINEAR_A_SIGN_A509                    0x106BA 0  // 𐚺
#define UC_LINEAR_A_SIGN_A510                    0x106BB 0  // 𐚻
#define UC_LINEAR_A_SIGN_A511                    0x106BC 0  // 𐚼
#define UC_LINEAR_A_SIGN_A512                    0x106BD 0  // 𐚽
#define UC_LINEAR_A_SIGN_A513                    0x106BE 0  // 𐚾
#define UC_LINEAR_A_SIGN_A515                    0x106BF 0  // 𐚿
#define UC_LINEAR_A_SIGN_A516                    0x106C0 0  // 𐛀
#define UC_LINEAR_A_SIGN_A520                    0x106C1 0  // 𐛁
#define UC_LINEAR_A_SIGN_A521                    0x106C2 0  // 𐛂
#define UC_LINEAR_A_SIGN_A523                    0x106C3 0  // 𐛃
#define UC_LINEAR_A_SIGN_A524                    0x106C4 0  // 𐛄
#define UC_LINEAR_A_SIGN_A525                    0x106C5 0  // 𐛅
#define UC_LINEAR_A_SIGN_A526                    0x106C6 0  // 𐛆
#define UC_LINEAR_A_SIGN_A527                    0x106C7 0  // 𐛇
#define UC_LINEAR_A_SIGN_A528                    0x106C8 0  // 𐛈
#define UC_LINEAR_A_SIGN_A529                    0x106C9 0  // 𐛉
#define UC_LINEAR_A_SIGN_A530                    0x106CA 0  // 𐛊
#define UC_LINEAR_A_SIGN_A531                    0x106CB 0  // 𐛋
#define UC_LINEAR_A_SIGN_A532                    0x106CC 0  // 𐛌
#define UC_LINEAR_A_SIGN_A534                    0x106CD 0  // 𐛍
#define UC_LINEAR_A_SIGN_A535                    0x106CE 0  // 𐛎
#define UC_LINEAR_A_SIGN_A536                    0x106CF 0  // 𐛏
#define UC_LINEAR_A_SIGN_A537                    0x106D0 0  // 𐛐
#define UC_LINEAR_A_SIGN_A538                    0x106D1 0  // 𐛑
#define UC_LINEAR_A_SIGN_A539                    0x106D2 0  // 𐛒
#define UC_LINEAR_A_SIGN_A540                    0x106D3 0  // 𐛓
#define UC_LINEAR_A_SIGN_A541                    0x106D4 0  // 𐛔
#define UC_LINEAR_A_SIGN_A542                    0x106D5 0  // 𐛕
#define UC_LINEAR_A_SIGN_A545                    0x106D6 0  // 𐛖
#define UC_LINEAR_A_SIGN_A547                    0x106D7 0  // 𐛗
#define UC_LINEAR_A_SIGN_A548                    0x106D8 0  // 𐛘
#define UC_LINEAR_A_SIGN_A549                    0x106D9 0  // 𐛙
#define UC_LINEAR_A_SIGN_A550                    0x106DA 0  // 𐛚
#define UC_LINEAR_A_SIGN_A551                    0x106DB 0  // 𐛛
#define UC_LINEAR_A_SIGN_A552                    0x106DC 0  // 𐛜
#define UC_LINEAR_A_SIGN_A553                    0x106DD 0  // 𐛝
#define UC_LINEAR_A_SIGN_A554                    0x106DE 0  // 𐛞
#define UC_LINEAR_A_SIGN_A555                    0x106DF 0  // 𐛟
#define UC_LINEAR_A_SIGN_A556                    0x106E0 0  // 𐛠
#define UC_LINEAR_A_SIGN_A557                    0x106E1 0  // 𐛡
#define UC_LINEAR_A_SIGN_A559                    0x106E2 0  // 𐛢
#define UC_LINEAR_A_SIGN_A563                    0x106E3 0  // 𐛣
#define UC_LINEAR_A_SIGN_A564                    0x106E4 0  // 𐛤
#define UC_LINEAR_A_SIGN_A565                    0x106E5 0  // 𐛥
#define UC_LINEAR_A_SIGN_A566                    0x106E6 0  // 𐛦
#define UC_LINEAR_A_SIGN_A568                    0x106E7 0  // 𐛧
#define UC_LINEAR_A_SIGN_A569                    0x106E8 0  // 𐛨
#define UC_LINEAR_A_SIGN_A570                    0x106E9 0  // 𐛩
#define UC_LINEAR_A_SIGN_A571                    0x106EA 0  // 𐛪
#define UC_LINEAR_A_SIGN_A572                    0x106EB 0  // 𐛫
#define UC_LINEAR_A_SIGN_A573                    0x106EC 0  // 𐛬
#define UC_LINEAR_A_SIGN_A574                    0x106ED 0  // 𐛭
#define UC_LINEAR_A_SIGN_A575                    0x106EE 0  // 𐛮
#define UC_LINEAR_A_SIGN_A576                    0x106EF 0  // 𐛯
#define UC_LINEAR_A_SIGN_A577                    0x106F0 0  // 𐛰
#define UC_LINEAR_A_SIGN_A578                    0x106F1 0  // 𐛱
#define UC_LINEAR_A_SIGN_A579                    0x106F2 0  // 𐛲
#define UC_LINEAR_A_SIGN_A580                    0x106F3 0  // 𐛳
#define UC_LINEAR_A_SIGN_A581                    0x106F4 0  // 𐛴
#define UC_LINEAR_A_SIGN_A582                    0x106F5 0  // 𐛵
#define UC_LINEAR_A_SIGN_A583                    0x106F6 0  // 𐛶
#define UC_LINEAR_A_SIGN_A584                    0x106F7 0  // 𐛷
#define UC_LINEAR_A_SIGN_A585                    0x106F8 0  // 𐛸
#define UC_LINEAR_A_SIGN_A586                    0x106F9 0  // 𐛹
#define UC_LINEAR_A_SIGN_A587                    0x106FA 0  // 𐛺
#define UC_LINEAR_A_SIGN_A588                    0x106FB 0  // 𐛻
#define UC_LINEAR_A_SIGN_A589                    0x106FC 0  // 𐛼
#define UC_LINEAR_A_SIGN_A591                    0x106FD 0  // 𐛽
#define UC_LINEAR_A_SIGN_A592                    0x106FE 0  // 𐛾
#define UC_LINEAR_A_SIGN_A594                    0x106FF 0  // 𐛿
#define UC_LINEAR_A_SIGN_A595                    0x10700 0  // 𐜀
#define UC_LINEAR_A_SIGN_A596                    0x10701 0  // 𐜁
#define UC_LINEAR_A_SIGN_A598                    0x10702 0  // 𐜂
#define UC_LINEAR_A_SIGN_A600                    0x10703 0  // 𐜃
#define UC_LINEAR_A_SIGN_A601                    0x10704 0  // 𐜄
#define UC_LINEAR_A_SIGN_A602                    0x10705 0  // 𐜅
#define UC_LINEAR_A_SIGN_A603                    0x10706 0  // 𐜆
#define UC_LINEAR_A_SIGN_A604                    0x10707 0  // 𐜇
#define UC_LINEAR_A_SIGN_A606                    0x10708 0  // 𐜈
#define UC_LINEAR_A_SIGN_A608                    0x10709 0  // 𐜉
#define UC_LINEAR_A_SIGN_A609                    0x1070A 0  // 𐜊
#define UC_LINEAR_A_SIGN_A610                    0x1070B 0  // 𐜋
#define UC_LINEAR_A_SIGN_A611                    0x1070C 0  // 𐜌
#define UC_LINEAR_A_SIGN_A612                    0x1070D 0  // 𐜍
#define UC_LINEAR_A_SIGN_A613                    0x1070E 0  // 𐜎
#define UC_LINEAR_A_SIGN_A614                    0x1070F 0  // 𐜏
#define UC_LINEAR_A_SIGN_A615                    0x10710 0  // 𐜐
#define UC_LINEAR_A_SIGN_A616                    0x10711 0  // 𐜑
#define UC_LINEAR_A_SIGN_A617                    0x10712 0  // 𐜒
#define UC_LINEAR_A_SIGN_A618                    0x10713 0  // 𐜓
#define UC_LINEAR_A_SIGN_A619                    0x10714 0  // 𐜔
#define UC_LINEAR_A_SIGN_A620                    0x10715 0  // 𐜕
#define UC_LINEAR_A_SIGN_A621                    0x10716 0  // 𐜖
#define UC_LINEAR_A_SIGN_A622                    0x10717 0  // 𐜗
#define UC_LINEAR_A_SIGN_A623                    0x10718 0  // 𐜘
#define UC_LINEAR_A_SIGN_A624                    0x10719 0  // 𐜙
#define UC_LINEAR_A_SIGN_A626                    0x1071A 0  // 𐜚
#define UC_LINEAR_A_SIGN_A627                    0x1071B 0  // 𐜛
#define UC_LINEAR_A_SIGN_A628                    0x1071C 0  // 𐜜
#define UC_LINEAR_A_SIGN_A629                    0x1071D 0  // 𐜝
#define UC_LINEAR_A_SIGN_A634                    0x1071E 0  // 𐜞
#define UC_LINEAR_A_SIGN_A637                    0x1071F 0  // 𐜟
#define UC_LINEAR_A_SIGN_A638                    0x10720 0  // 𐜠
#define UC_LINEAR_A_SIGN_A640                    0x10721 0  // 𐜡
#define UC_LINEAR_A_SIGN_A642                    0x10722 0  // 𐜢
#define UC_LINEAR_A_SIGN_A643                    0x10723 0  // 𐜣
#define UC_LINEAR_A_SIGN_A644                    0x10724 0  // 𐜤
#define UC_LINEAR_A_SIGN_A645                    0x10725 0  // 𐜥
#define UC_LINEAR_A_SIGN_A646                    0x10726 0  // 𐜦
#define UC_LINEAR_A_SIGN_A648                    0x10727 0  // 𐜧
#define UC_LINEAR_A_SIGN_A649                    0x10728 0  // 𐜨
#define UC_LINEAR_A_SIGN_A651                    0x10729 0  // 𐜩
#define UC_LINEAR_A_SIGN_A652                    0x1072A 0  // 𐜪
#define UC_LINEAR_A_SIGN_A653                    0x1072B 0  // 𐜫
#define UC_LINEAR_A_SIGN_A654                    0x1072C 0  // 𐜬
#define UC_LINEAR_A_SIGN_A655                    0x1072D 0  // 𐜭
#define UC_LINEAR_A_SIGN_A656                    0x1072E 0  // 𐜮
#define UC_LINEAR_A_SIGN_A657                    0x1072F 0  // 𐜯
#define UC_LINEAR_A_SIGN_A658                    0x10730 0  // 𐜰
#define UC_LINEAR_A_SIGN_A659                    0x10731 0  // 𐜱
#define UC_LINEAR_A_SIGN_A660                    0x10732 0  // 𐜲
#define UC_LINEAR_A_SIGN_A661                    0x10733 0  // 𐜳
#define UC_LINEAR_A_SIGN_A662                    0x10734 0  // 𐜴
#define UC_LINEAR_A_SIGN_A663                    0x10735 0  // 𐜵
#define UC_LINEAR_A_SIGN_A664                    0x10736 0  // 𐜶
#define UC_LINEAR_A_SIGN_A701_A                  0x10740 0  // 𐝀
#define UC_LINEAR_A_SIGN_A702_B                  0x10741 0  // 𐝁
#define UC_LINEAR_A_SIGN_A703_D                  0x10742 0  // 𐝂
#define UC_LINEAR_A_SIGN_A704_E                  0x10743 0  // 𐝃
#define UC_LINEAR_A_SIGN_A705_F                  0x10744 0  // 𐝄
#define UC_LINEAR_A_SIGN_A706_H                  0x10745 0  // 𐝅
#define UC_LINEAR_A_SIGN_A707_J                  0x10746 0  // 𐝆
#define UC_LINEAR_A_SIGN_A708_K                  0x10747 0  // 𐝇
#define UC_LINEAR_A_SIGN_A709_L                  0x10748 0  // 𐝈
#define UC_LINEAR_A_SIGN_A709_2_L2               0x10749 0  // 𐝉
#define UC_LINEAR_A_SIGN_A709_3_L3               0x1074A 0  // 𐝊
#define UC_LINEAR_A_SIGN_A709_4_L4               0x1074B 0  // 𐝋
#define UC_LINEAR_A_SIGN_A709_6_L6               0x1074C 0  // 𐝌
#define UC_LINEAR_A_SIGN_A710_W                  0x1074D 0  // 𐝍
#define UC_LINEAR_A_SIGN_A711_X                  0x1074E 0  // 𐝎
#define UC_LINEAR_A_SIGN_A712_Y                  0x1074F 0  // 𐝏
#define UC_LINEAR_A_SIGN_A713_OMEGA              0x10750 0  // 𐝐
#define UC_LINEAR_A_SIGN_A714_ABB                0x10751 0  // 𐝑
#define UC_LINEAR_A_SIGN_A715_BB                 0x10752 0  // 𐝒
#define UC_LINEAR_A_SIGN_A717_DD                 0x10753 0  // 𐝓
#define UC_LINEAR_A_SIGN_A726_EYYY               0x10754 0  // 𐝔
#define UC_LINEAR_A_SIGN_A732_JE                 0x10755 0  // 𐝕
#define UC_LINEAR_A_SIGN_A800                    0x10760 0  // 𐝠
#define UC_LINEAR_A_SIGN_A801                    0x10761 0  // 𐝡
#define UC_LINEAR_A_SIGN_A802                    0x10762 0  // 𐝢
#define UC_LINEAR_A_SIGN_A803                    0x10763 0  // 𐝣
#define UC_LINEAR_A_SIGN_A804                    0x10764 0  // 𐝤
#define UC_LINEAR_A_SIGN_A805                    0x10765 0  // 𐝥
#define UC_LINEAR_A_SIGN_A806                    0x10766 0  // 𐝦
#define UC_LINEAR_A_SIGN_A807                    0x10767 0  // 𐝧
