/* linear_b_ideograms.h – Unicode constants for U+10080 … U+100FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Linear B Ideograms is a Unicode block containing ideographic
 * characters for writing Mycenaean Greek and Minoan . Several Linear B
 * ideographs double as syllabic letters, and are encoded in the Linear B
 * Syllabary block.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Linear B Ideograms block:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Linear_B_Ideograms
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U10080.pdf
 
* Consistency Check:
* Total Defined Code Points: 123
* Total Significant Hex Values: 123
* Status: OK (Counts Match)

*/

#pragma once

#define UC_LINEAR_B_IDEOGRAM_B100_MAN            0x10080 0  // 𐂀
#define UC_LINEAR_B_IDEOGRAM_B102_WOMAN          0x10081 0  // 𐂁
#define UC_LINEAR_B_IDEOGRAM_B104_DEER           0x10082 0  // 𐂂
#define UC_LINEAR_B_IDEOGRAM_B105_EQUID          0x10083 0  // 𐂃
#define UC_LINEAR_B_IDEOGRAM_B105F_MARE          0x10084 0  // 𐂄
#define UC_LINEAR_B_IDEOGRAM_B105M_STALLION      0x10085 0  // 𐂅
#define UC_LINEAR_B_IDEOGRAM_B106F_EWE           0x10086 0  // 𐂆
#define UC_LINEAR_B_IDEOGRAM_B106M_RAM           0x10087 0  // 𐂇
#define UC_LINEAR_B_IDEOGRAM_B107F_SHE_GOAT      0x10088 0  // 𐂈
#define UC_LINEAR_B_IDEOGRAM_B107M_HE_GOAT       0x10089 0  // 𐂉
#define UC_LINEAR_B_IDEOGRAM_B108F_SOW           0x1008A 0  // 𐂊
#define UC_LINEAR_B_IDEOGRAM_B108M_BOAR          0x1008B 0  // 𐂋
#define UC_LINEAR_B_IDEOGRAM_B109F_COW           0x1008C 0  // 𐂌
#define UC_LINEAR_B_IDEOGRAM_B109M_BULL          0x1008D 0  // 𐂍
#define UC_LINEAR_B_IDEOGRAM_B120_WHEAT          0x1008E 0  // 𐂎
#define UC_LINEAR_B_IDEOGRAM_B121_BARLEY         0x1008F 0  // 𐂏
#define UC_LINEAR_B_IDEOGRAM_B122_OLIVE          0x10090 0  // 𐂐
#define UC_LINEAR_B_IDEOGRAM_B123_SPICE          0x10091 0  // 𐂑
#define UC_LINEAR_B_IDEOGRAM_B125_CYPERUS        0x10092 0  // 𐂒
#define UC_LINEAR_B_MONOGRAM_B127_KAPO           0x10093 0  // 𐂓
#define UC_LINEAR_B_MONOGRAM_B128_KANAKO         0x10094 0  // 𐂔
#define UC_LINEAR_B_IDEOGRAM_B130_OIL            0x10095 0  // 𐂕
#define UC_LINEAR_B_IDEOGRAM_B131_WINE           0x10096 0  // 𐂖
#define UC_LINEAR_B_IDEOGRAM_B132                0x10097 0  // 𐂗
#define UC_LINEAR_B_MONOGRAM_B133_AREPA          0x10098 0  // 𐂘
#define UC_LINEAR_B_MONOGRAM_B135_MERI           0x10099 0  // 𐂙
#define UC_LINEAR_B_IDEOGRAM_B140_BRONZE         0x1009A 0  // 𐂚
#define UC_LINEAR_B_IDEOGRAM_B141_GOLD           0x1009B 0  // 𐂛
#define UC_LINEAR_B_IDEOGRAM_B142                0x1009C 0  // 𐂜
#define UC_LINEAR_B_IDEOGRAM_B145_WOOL           0x1009D 0  // 𐂝
#define UC_LINEAR_B_IDEOGRAM_B146                0x1009E 0  // 𐂞
#define UC_LINEAR_B_IDEOGRAM_B150                0x1009F 0  // 𐂟
#define UC_LINEAR_B_IDEOGRAM_B151_HORN           0x100A0 0  // 𐂠
#define UC_LINEAR_B_IDEOGRAM_B152                0x100A1 0  // 𐂡
#define UC_LINEAR_B_IDEOGRAM_B153                0x100A2 0  // 𐂢
#define UC_LINEAR_B_IDEOGRAM_B154                0x100A3 0  // 𐂣
#define UC_LINEAR_B_MONOGRAM_B156_TURO2          0x100A4 0  // 𐂤
#define UC_LINEAR_B_IDEOGRAM_B157                0x100A5 0  // 𐂥
#define UC_LINEAR_B_IDEOGRAM_B158                0x100A6 0  // 𐂦
#define UC_LINEAR_B_IDEOGRAM_B159_CLOTH          0x100A7 0  // 𐂧
#define UC_LINEAR_B_IDEOGRAM_B160                0x100A8 0  // 𐂨
#define UC_LINEAR_B_IDEOGRAM_B161                0x100A9 0  // 𐂩
#define UC_LINEAR_B_IDEOGRAM_B162_GARMENT        0x100AA 0  // 𐂪
#define UC_LINEAR_B_IDEOGRAM_B163_ARMOUR         0x100AB 0  // 𐂫
#define UC_LINEAR_B_IDEOGRAM_B164                0x100AC 0  // 𐂬
#define UC_LINEAR_B_IDEOGRAM_B165                0x100AD 0  // 𐂭
#define UC_LINEAR_B_IDEOGRAM_B166                0x100AE 0  // 𐂮
#define UC_LINEAR_B_IDEOGRAM_B167                0x100AF 0  // 𐂯
#define UC_LINEAR_B_IDEOGRAM_B168                0x100B0 0  // 𐂰
#define UC_LINEAR_B_IDEOGRAM_B169                0x100B1 0  // 𐂱
#define UC_LINEAR_B_IDEOGRAM_B170                0x100B2 0  // 𐂲
#define UC_LINEAR_B_IDEOGRAM_B171                0x100B3 0  // 𐂳
#define UC_LINEAR_B_IDEOGRAM_B172                0x100B4 0  // 𐂴
#define UC_LINEAR_B_IDEOGRAM_B173_MONTH          0x100B5 0  // 𐂵
#define UC_LINEAR_B_IDEOGRAM_B174                0x100B6 0  // 𐂶
#define UC_LINEAR_B_IDEOGRAM_B176_TREE           0x100B7 0  // 𐂷
#define UC_LINEAR_B_IDEOGRAM_B177                0x100B8 0  // 𐂸
#define UC_LINEAR_B_IDEOGRAM_B178                0x100B9 0  // 𐂹
#define UC_LINEAR_B_IDEOGRAM_B179                0x100BA 0  // 𐂺
#define UC_LINEAR_B_IDEOGRAM_B180                0x100BB 0  // 𐂻
#define UC_LINEAR_B_IDEOGRAM_B181                0x100BC 0  // 𐂼
#define UC_LINEAR_B_IDEOGRAM_B182                0x100BD 0  // 𐂽
#define UC_LINEAR_B_IDEOGRAM_B183                0x100BE 0  // 𐂾
#define UC_LINEAR_B_IDEOGRAM_B184                0x100BF 0  // 𐂿
#define UC_LINEAR_B_IDEOGRAM_B185                0x100C0 0  // 𐃀
#define UC_LINEAR_B_IDEOGRAM_B189                0x100C1 0  // 𐃁
#define UC_LINEAR_B_IDEOGRAM_B190                0x100C2 0  // 𐃂
#define UC_LINEAR_B_IDEOGRAM_B191_HELMET         0x100C3 0  // 𐃃
#define UC_LINEAR_B_IDEOGRAM_B220_FOOTSTOOL      0x100C4 0  // 𐃄
#define UC_LINEAR_B_IDEOGRAM_B225_BATHTUB        0x100C5 0  // 𐃅
#define UC_LINEAR_B_IDEOGRAM_B230_SPEAR          0x100C6 0  // 𐃆
#define UC_LINEAR_B_IDEOGRAM_B231_ARROW          0x100C7 0  // 𐃇
#define UC_LINEAR_B_IDEOGRAM_B232                0x100C8 0  // 𐃈
#define UC_LINEAR_B_IDEOGRAM_B233_SWORD          0x100C9 0  // 𐃉
#define UC_LINEAR_B_IDEOGRAM_B234                0x100CA 0  // 𐃊
#define UC_LINEAR_B_IDEOGRAM_B236                0x100CB 0  // 𐃋
#define UC_LINEAR_B_IDEOGRAM_B240_WHEELED_CHARIOT 0x100CC 0  // 𐃌
#define UC_LINEAR_B_IDEOGRAM_B241_CHARIOT        0x100CD 0  // 𐃍
#define UC_LINEAR_B_IDEOGRAM_B242_CHARIOT_FRAME  0x100CE 0  // 𐃎
#define UC_LINEAR_B_IDEOGRAM_B243_WHEEL          0x100CF 0  // 𐃏
#define UC_LINEAR_B_IDEOGRAM_B245                0x100D0 0  // 𐃐
#define UC_LINEAR_B_IDEOGRAM_B246                0x100D1 0  // 𐃑
#define UC_LINEAR_B_MONOGRAM_B247_DIPTE          0x100D2 0  // 𐃒
#define UC_LINEAR_B_IDEOGRAM_B248                0x100D3 0  // 𐃓
#define UC_LINEAR_B_IDEOGRAM_B249                0x100D4 0  // 𐃔
#define UC_LINEAR_B_IDEOGRAM_B251                0x100D5 0  // 𐃕
#define UC_LINEAR_B_IDEOGRAM_B252                0x100D6 0  // 𐃖
#define UC_LINEAR_B_IDEOGRAM_B253                0x100D7 0  // 𐃗
#define UC_LINEAR_B_IDEOGRAM_B254_DART           0x100D8 0  // 𐃘
#define UC_LINEAR_B_IDEOGRAM_B255                0x100D9 0  // 𐃙
#define UC_LINEAR_B_IDEOGRAM_B256                0x100DA 0  // 𐃚
#define UC_LINEAR_B_IDEOGRAM_B257                0x100DB 0  // 𐃛
#define UC_LINEAR_B_IDEOGRAM_B258                0x100DC 0  // 𐃜
#define UC_LINEAR_B_IDEOGRAM_B259                0x100DD 0  // 𐃝
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B155         0x100DE 0  // 𐃞
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B200         0x100DF 0  // 𐃟
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B201         0x100E0 0  // 𐃠
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B202         0x100E1 0  // 𐃡
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B203         0x100E2 0  // 𐃢
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B204         0x100E3 0  // 𐃣
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B205         0x100E4 0  // 𐃤
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B206         0x100E5 0  // 𐃥
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B207         0x100E6 0  // 𐃦
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B208         0x100E7 0  // 𐃧
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B209         0x100E8 0  // 𐃨
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B210         0x100E9 0  // 𐃩
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B211         0x100EA 0  // 𐃪
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B212         0x100EB 0  // 𐃫
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B213         0x100EC 0  // 𐃬
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B214         0x100ED 0  // 𐃭
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B215         0x100EE 0  // 𐃮
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B216         0x100EF 0  // 𐃯
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B217         0x100F0 0  // 𐃰
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B218         0x100F1 0  // 𐃱
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B219         0x100F2 0  // 𐃲
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B221         0x100F3 0  // 𐃳
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B222         0x100F4 0  // 𐃴
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B226         0x100F5 0  // 𐃵
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B227         0x100F6 0  // 𐃶
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B228         0x100F7 0  // 𐃷
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B229         0x100F8 0  // 𐃸
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B250         0x100F9 0  // 𐃹
#define UC_LINEAR_B_IDEOGRAM_VESSEL_B305         0x100FA 0  // 𐃺
