/* makasar.h – Unicode constants for U+11EE0 … U+11EFF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Makasar
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U11EE0.pdf
 
* Consistency Check:
* Total Defined Code Points: 25
* Total Significant Hex Values: 25
* Status: OK (Counts Match)

*/

#pragma once

#define UC_MAKASAR_KA                            0x11EE0 0  // 𑻠
#define UC_MAKASAR_GA                            0x11EE1 0  // 𑻡
#define UC_MAKASAR_NGA                           0x11EE2 0  // 𑻢
#define UC_MAKASAR_PA                            0x11EE3 0  // 𑻣
#define UC_MAKASAR_BA                            0x11EE4 0  // 𑻤
#define UC_MAKASAR_MA                            0x11EE5 0  // 𑻥
#define UC_MAKASAR_TA                            0x11EE6 0  // 𑻦
#define UC_MAKASAR_DA                            0x11EE7 0  // 𑻧
#define UC_MAKASAR_NA                            0x11EE8 0  // 𑻨
#define UC_MAKASAR_CA                            0x11EE9 0  // 𑻩
#define UC_MAKASAR_JA                            0x11EEA 0  // 𑻪
#define UC_MAKASAR_NYA                           0x11EEB 0  // 𑻫
#define UC_MAKASAR_YA                            0x11EEC 0  // 𑻬
#define UC_MAKASAR_RA                            0x11EED 0  // 𑻭
#define UC_MAKASAR_LA                            0x11EEE 0  // 𑻮
#define UC_MAKASAR_VA                            0x11EEF 0  // 𑻯
#define UC_MAKASAR_SA                            0x11EF0 0  // 𑻰
#define UC_MAKASAR_A                             0x11EF1 0  // 𑻱
#define UC_MAKASAR_ANGKA                         0x11EF2 0  // 𑻲
#define UC_MAKASAR_VOWEL_SIGN_I                  0x11EF3 0  // 𑻳
#define UC_MAKASAR_VOWEL_SIGN_U                  0x11EF4 0  // 𑻴
#define UC_MAKASAR_VOWEL_SIGN_E                  0x11EF5 0  // 𑻵
#define UC_MAKASAR_VOWEL_SIGN_O                  0x11EF6 0  // 𑻶
#define UC_MAKASAR_PASSIMBANG                    0x11EF7 0  // 𑻷
#define UC_MAKASAR_END_OF_SECTION                0x11EF8 0  // 𑻸
