/* marchen.h – Unicode constants for U+11C70 … U+11CBF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Märchen is the German diminutive of the obsolete German word Mär ,
 * meaning "news, tale" (see Märchen ). It may refer to:
 * Märchen or Marchen may also refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Marchen
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U11C70.pdf
 
* Consistency Check:
* Total Defined Code Points: 68
* Total Significant Hex Values: 68
* Status: OK (Counts Match)

*/

#pragma once

#define UC_MARCHEN_HEAD_MARK                     0x11C70 0  // 𑱰
#define UC_MARCHEN_MARK_SHAD                     0x11C71 0  // 𑱱
#define UC_MARCHEN_KA                            0x11C72 0  // 𑱲
#define UC_MARCHEN_KHA                           0x11C73 0  // 𑱳
#define UC_MARCHEN_GA                            0x11C74 0  // 𑱴
#define UC_MARCHEN_NGA                           0x11C75 0  // 𑱵
#define UC_MARCHEN_CA                            0x11C76 0  // 𑱶
#define UC_MARCHEN_CHA                           0x11C77 0  // 𑱷
#define UC_MARCHEN_JA                            0x11C78 0  // 𑱸
#define UC_MARCHEN_NYA                           0x11C79 0  // 𑱹
#define UC_MARCHEN_TA                            0x11C7A 0  // 𑱺
#define UC_MARCHEN_THA                           0x11C7B 0  // 𑱻
#define UC_MARCHEN_DA                            0x11C7C 0  // 𑱼
#define UC_MARCHEN_NA                            0x11C7D 0  // 𑱽
#define UC_MARCHEN_PA                            0x11C7E 0  // 𑱾
#define UC_MARCHEN_PHA                           0x11C7F 0  // 𑱿
#define UC_MARCHEN_BA                            0x11C80 0  // 𑲀
#define UC_MARCHEN_MA                            0x11C81 0  // 𑲁
#define UC_MARCHEN_TSA                           0x11C82 0  // 𑲂
#define UC_MARCHEN_TSHA                          0x11C83 0  // 𑲃
#define UC_MARCHEN_DZA                           0x11C84 0  // 𑲄
#define UC_MARCHEN_WA                            0x11C85 0  // 𑲅
#define UC_MARCHEN_ZHA                           0x11C86 0  // 𑲆
#define UC_MARCHEN_ZA                            0x11C87 0  // 𑲇
#define UC_MARCHEN_A                             0x11C88 0  // 𑲈
#define UC_MARCHEN_YA                            0x11C89 0  // 𑲉
#define UC_MARCHEN_RA                            0x11C8A 0  // 𑲊
#define UC_MARCHEN_LA                            0x11C8B 0  // 𑲋
#define UC_MARCHEN_SHA                           0x11C8C 0  // 𑲌
#define UC_MARCHEN_SA                            0x11C8D 0  // 𑲍
#define UC_MARCHEN_HA                            0x11C8E 0  // 𑲎
#define UC_MARCHEN_LETTER_A                      0x11C8F 0  // 𑲏
#define UC_MARCHEN_SUBJOINED_KA                  0x11C92 0  // 𑲒
#define UC_MARCHEN_SUBJOINED_KHA                 0x11C93 0  // 𑲓
#define UC_MARCHEN_SUBJOINED_GA                  0x11C94 0  // 𑲔
#define UC_MARCHEN_SUBJOINED_NGA                 0x11C95 0  // 𑲕
#define UC_MARCHEN_SUBJOINED_CA                  0x11C96 0  // 𑲖
#define UC_MARCHEN_SUBJOINED_CHA                 0x11C97 0  // 𑲗
#define UC_MARCHEN_SUBJOINED_JA                  0x11C98 0  // 𑲘
#define UC_MARCHEN_SUBJOINED_NYA                 0x11C99 0  // 𑲙
#define UC_MARCHEN_SUBJOINED_TA                  0x11C9A 0  // 𑲚
#define UC_MARCHEN_SUBJOINED_THA                 0x11C9B 0  // 𑲛
#define UC_MARCHEN_SUBJOINED_DA                  0x11C9C 0  // 𑲜
#define UC_MARCHEN_SUBJOINED_NA                  0x11C9D 0  // 𑲝
#define UC_MARCHEN_SUBJOINED_PA                  0x11C9E 0  // 𑲞
#define UC_MARCHEN_SUBJOINED_PHA                 0x11C9F 0  // 𑲟
#define UC_MARCHEN_SUBJOINED_BA                  0x11CA0 0  // 𑲠
#define UC_MARCHEN_SUBJOINED_MA                  0x11CA1 0  // 𑲡
#define UC_MARCHEN_SUBJOINED_TSA                 0x11CA2 0  // 𑲢
#define UC_MARCHEN_SUBJOINED_TSHA                0x11CA3 0  // 𑲣
#define UC_MARCHEN_SUBJOINED_DZA                 0x11CA4 0  // 𑲤
#define UC_MARCHEN_SUBJOINED_WA                  0x11CA5 0  // 𑲥
#define UC_MARCHEN_SUBJOINED_ZHA                 0x11CA6 0  // 𑲦
#define UC_MARCHEN_SUBJOINED_ZA                  0x11CA7 0  // 𑲧
#define UC_MARCHEN_SUBJOINED_YA                  0x11CA9 0  // 𑲩
#define UC_MARCHEN_SUBJOINED_RA                  0x11CAA 0  // 𑲪
#define UC_MARCHEN_SUBJOINED_LA                  0x11CAB 0  // 𑲫
#define UC_MARCHEN_SUBJOINED_SHA                 0x11CAC 0  // 𑲬
#define UC_MARCHEN_SUBJOINED_SA                  0x11CAD 0  // 𑲭
#define UC_MARCHEN_SUBJOINED_HA                  0x11CAE 0  // 𑲮
#define UC_MARCHEN_SUBJOINED_A                   0x11CAF 0  // 𑲯
#define UC_MARCHEN_VOWEL_SIGN_AA                 0x11CB0 0  // 𑲰
#define UC_MARCHEN_VOWEL_SIGN_I                  0x11CB1 0  // 𑲱
#define UC_MARCHEN_VOWEL_SIGN_U                  0x11CB2 0  // 𑲲
#define UC_MARCHEN_VOWEL_SIGN_E                  0x11CB3 0  // 𑲳
#define UC_MARCHEN_VOWEL_SIGN_O                  0x11CB4 0  // 𑲴
#define UC_MARCHEN_SIGN_ANUSVARA                 0x11CB5 0  // 𑲵
#define UC_MARCHEN_SIGN_CANDRABINDU              0x11CB6 0  // 𑲶
