/* masaram_gondi.h – Unicode constants for U+11D00 … U+11D5F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Gondi has typically been written in Devanagari script or Telugu script
 * , but native scripts are in existence. A Gond by the name of Munshi
 * Mangal Singh Masaram designed a Brahmi-based script in 1918, and in
 * 2006, a native script that dates up to 1750 has been discovered by a
 * group of researchers from the University of Hyderabad.
 * Nonetheless, most Gonds are unaware of their well developed language
 * and do not use any script now. The Gunjala Gondi Lipi has witnessed a
 * surge in prominence, and well-supported efforts are being undertaken
 * in villages of northern Andhra Pradesh to widen its usage.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Masaram_Gondi
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U11D00.pdf
 
* Consistency Check:
* Total Defined Code Points: 75
* Total Significant Hex Values: 75
* Status: OK (Counts Match)

*/

#pragma once

#define UC_MASARAM_GONDI_A                       0x11D00 0  // 𑴀
#define UC_MASARAM_GONDI_AA                      0x11D01 0  // 𑴁
#define UC_MASARAM_GONDI_I                       0x11D02 0  // 𑴂
#define UC_MASARAM_GONDI_II                      0x11D03 0  // 𑴃
#define UC_MASARAM_GONDI_U                       0x11D04 0  // 𑴄
#define UC_MASARAM_GONDI_UU                      0x11D05 0  // 𑴅
#define UC_MASARAM_GONDI_E                       0x11D06 0  // 𑴆
#define UC_MASARAM_GONDI_AI                      0x11D08 0  // 𑴈
#define UC_MASARAM_GONDI_O                       0x11D09 0  // 𑴉
#define UC_MASARAM_GONDI_AU                      0x11D0B 0  // 𑴋
#define UC_MASARAM_GONDI_KA                      0x11D0C 0  // 𑴌
#define UC_MASARAM_GONDI_KHA                     0x11D0D 0  // 𑴍
#define UC_MASARAM_GONDI_GA                      0x11D0E 0  // 𑴎
#define UC_MASARAM_GONDI_GHA                     0x11D0F 0  // 𑴏
#define UC_MASARAM_GONDI_NGA                     0x11D10 0  // 𑴐
#define UC_MASARAM_GONDI_CA                      0x11D11 0  // 𑴑
#define UC_MASARAM_GONDI_CHA                     0x11D12 0  // 𑴒
#define UC_MASARAM_GONDI_JA                      0x11D13 0  // 𑴓
#define UC_MASARAM_GONDI_JHA                     0x11D14 0  // 𑴔
#define UC_MASARAM_GONDI_NYA                     0x11D15 0  // 𑴕
#define UC_MASARAM_GONDI_TTA                     0x11D16 0  // 𑴖
#define UC_MASARAM_GONDI_TTHA                    0x11D17 0  // 𑴗
#define UC_MASARAM_GONDI_DDA                     0x11D18 0  // 𑴘
#define UC_MASARAM_GONDI_DDHA                    0x11D19 0  // 𑴙
#define UC_MASARAM_GONDI_NNA                     0x11D1A 0  // 𑴚
#define UC_MASARAM_GONDI_TA                      0x11D1B 0  // 𑴛
#define UC_MASARAM_GONDI_THA                     0x11D1C 0  // 𑴜
#define UC_MASARAM_GONDI_DA                      0x11D1D 0  // 𑴝
#define UC_MASARAM_GONDI_DHA                     0x11D1E 0  // 𑴞
#define UC_MASARAM_GONDI_NA                      0x11D1F 0  // 𑴟
#define UC_MASARAM_GONDI_PA                      0x11D20 0  // 𑴠
#define UC_MASARAM_GONDI_PHA                     0x11D21 0  // 𑴡
#define UC_MASARAM_GONDI_BA                      0x11D22 0  // 𑴢
#define UC_MASARAM_GONDI_BHA                     0x11D23 0  // 𑴣
#define UC_MASARAM_GONDI_MA                      0x11D24 0  // 𑴤
#define UC_MASARAM_GONDI_YA                      0x11D25 0  // 𑴥
#define UC_MASARAM_GONDI_RA                      0x11D26 0  // 𑴦
#define UC_MASARAM_GONDI_LA                      0x11D27 0  // 𑴧
#define UC_MASARAM_GONDI_VA                      0x11D28 0  // 𑴨
#define UC_MASARAM_GONDI_SHA                     0x11D29 0  // 𑴩
#define UC_MASARAM_GONDI_SSA                     0x11D2A 0  // 𑴪
#define UC_MASARAM_GONDI_SA                      0x11D2B 0  // 𑴫
#define UC_MASARAM_GONDI_HA                      0x11D2C 0  // 𑴬
#define UC_MASARAM_GONDI_LLA                     0x11D2D 0  // 𑴭
#define UC_MASARAM_GONDI_KSSA                    0x11D2E 0  // 𑴮
#define UC_MASARAM_GONDI_JNYA                    0x11D2F 0  // 𑴯
#define UC_MASARAM_GONDI_TRA                     0x11D30 0  // 𑴰
#define UC_MASARAM_GONDI_VOWEL_SIGN_AA           0x11D31 0  // 𑴱
#define UC_MASARAM_GONDI_VOWEL_SIGN_I            0x11D32 0  // 𑴲
#define UC_MASARAM_GONDI_VOWEL_SIGN_II           0x11D33 0  // 𑴳
#define UC_MASARAM_GONDI_VOWEL_SIGN_U            0x11D34 0  // 𑴴
#define UC_MASARAM_GONDI_VOWEL_SIGN_UU           0x11D35 0  // 𑴵
#define UC_MASARAM_GONDI_VOWEL_SIGN_VOCALIC_R    0x11D36 0  // 𑴶
#define UC_MASARAM_GONDI_VOWEL_SIGN_E            0x11D3A 0  // 𑴺
#define UC_MASARAM_GONDI_VOWEL_SIGN_AI           0x11D3C 0  // 𑴼
#define UC_MASARAM_GONDI_VOWEL_SIGN_O            0x11D3D 0  // 𑴽
#define UC_MASARAM_GONDI_VOWEL_SIGN_AU           0x11D3F 0  // 𑴿
#define UC_MASARAM_GONDI_SIGN_ANUSVARA           0x11D40 0  // 𑵀
#define UC_MASARAM_GONDI_SIGN_VISARGA            0x11D41 0  // 𑵁
#define UC_MASARAM_GONDI_SIGN_NUKTA              0x11D42 0  // 𑵂
#define UC_MASARAM_GONDI_SIGN_CANDRA             0x11D43 0  // 𑵃
#define UC_MASARAM_GONDI_SIGN_HALANTA            0x11D44 0  // 𑵄
#define UC_MASARAM_GONDI_VIRAMA                  0x11D45 0  // 𑵅
#define UC_MASARAM_GONDI_REPHA                   0x11D46 0  // 𑵆
#define UC_MASARAM_GONDI_RA_KARA                 0x11D47 0  // 𑵇
#define UC_MASARAM_GONDI_ZERO                    0x11D50 0  // 𑵐
#define UC_MASARAM_GONDI_ONE                     0x11D51 0  // 𑵑
#define UC_MASARAM_GONDI_TWO                     0x11D52 0  // 𑵒
#define UC_MASARAM_GONDI_THREE                   0x11D53 0  // 𑵓
#define UC_MASARAM_GONDI_FOUR                    0x11D54 0  // 𑵔
#define UC_MASARAM_GONDI_FIVE                    0x11D55 0  // 𑵕
#define UC_MASARAM_GONDI_SIX                     0x11D56 0  // 𑵖
#define UC_MASARAM_GONDI_SEVEN                   0x11D57 0  // 𑵗
#define UC_MASARAM_GONDI_EIGHT                   0x11D58 0  // 𑵘
#define UC_MASARAM_GONDI_NINE                    0x11D59 0  // 𑵙
