/* mathematical_operators.h – Unicode constants for U+2200 … U+22FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Mathematical Operators is a Unicode block containing characters for
 * mathematical, logical, and set notation.
 * Notably absent are the plus sign ( + {\displaystyle +} ), greater than
 * sign ( > {\displaystyle >} ) and less than sign ( < {\displaystyle <}
 * ), due to them already appearing in the Basic Latin Unicode block, and
 * the plus-or-minus sign ( ± {\displaystyle \pm } ), multiplication sign
 * ( × {\displaystyle \times } ) and obelus ( ÷ {\displaystyle \div } ),
 * due to them already appearing in the Latin-1 Supplement block,
 * although a distinct minus sign ( − {\displaystyle -} ) is included,
 * semantically different from the Basic Latin hyphen-minus (-).
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Mathematical_Operators
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U2200.pdf
 
* Consistency Check:
* Total Defined Code Points: 256
* Total Significant Hex Values: 256
* Status: OK (Counts Match)

*/

#pragma once

#define UC_MOP_FOR_ALL                           0x2200 0  // ∀
#define UC_MOP_COMPLEMENT                        0x2201 0  // ∁
#define UC_MOP_PARTIAL_DIFFERENTIAL              0x2202 0  // ∂
#define UC_MOP_THERE_EXISTS                      0x2203 0  // ∃
#define UC_MOP_THERE_DOES_NOT_EXIST              0x2204 0  // ∄
#define UC_MOP_EMPTY_SET                         0x2205 0  // ∅
#define UC_MOP_INCREMENT                         0x2206 0  // ∆
#define UC_MOP_NABLA                             0x2207 0  // ∇
#define UC_MOP_ELEMENT_OF                        0x2208 0  // ∈
#define UC_MOP_NOT_AN_ELEMENT_OF                 0x2209 0  // ∉
#define UC_MOP_SMALL_ELEMENT_OF                  0x220A 0  // ∊
#define UC_MOP_CONTAINS_AS_MEMBER                0x220B 0  // ∋
#define UC_MOP_DOES_NOT_CONTAIN_AS_MEMBER        0x220C 0  // ∌
#define UC_MOP_SMALL_CONTAINS_AS_MEMBER          0x220D 0  // ∍
#define UC_MOP_END_OF_PROOF                      0x220E 0  // ∎
#define UC_MOP_N_ARY_PRODUCT                     0x220F 0  // ∏
#define UC_MOP_N_ARY_COPRODUCT                   0x2210 0  // ∐
#define UC_MOP_N_ARY_SUMMATION                   0x2211 0  // ∑
#define UC_MOP_MINUS_SIGN                        0x2212 0  // −
#define UC_MOP_MINUS_OR_PLUS_SIGN                0x2213 0  // ∓
#define UC_MOP_DOT_PLUS                          0x2214 0  // ∔
#define UC_MOP_DIVISION_SLASH                    0x2215 0  // ∕
#define UC_MOP_SET_MINUS                         0x2216 0  // ∖
#define UC_MOP_ASTERISK_OPERATOR                 0x2217 0  // ∗
#define UC_MOP_RING_OPERATOR                     0x2218 0  // ∘
#define UC_MOP_BULLET_OPERATOR                   0x2219 0  // ∙
#define UC_MOP_SQUARE_ROOT                       0x221A 0  // √
#define UC_MOP_CUBE_ROOT                         0x221B 0  // ∛
#define UC_MOP_FOURTH_ROOT                       0x221C 0  // ∜
#define UC_MOP_PROPORTIONAL_TO                   0x221D 0  // ∝
#define UC_MOP_INFINITY                          0x221E 0  // ∞
#define UC_MOP_RIGHT_ANGLE                       0x221F 0  // ∟
#define UC_MOP_ANGLE                             0x2220 0  // ∠
#define UC_MOP_MEASURED_ANGLE                    0x2221 0  // ∡
#define UC_MOP_SPHERICAL_ANGLE                   0x2222 0  // ∢
#define UC_MOP_DIVIDES                           0x2223 0  // ∣
#define UC_MOP_DOES_NOT_DIVIDE                   0x2224 0  // ∤
#define UC_MOP_PARALLEL_TO                       0x2225 0  // ∥
#define UC_MOP_NOT_PARALLEL_TO                   0x2226 0  // ∦
#define UC_MOP_LOGICAL_AND                       0x2227 0  // ∧
#define UC_MOP_LOGICAL_OR                        0x2228 0  // ∨
#define UC_MOP_INTERSECTION                      0x2229 0  // ∩
#define UC_MOP_UNION                             0x222A 0  // ∪
#define UC_MOP_INTEGRAL                          0x222B 0  // ∫
#define UC_MOP_DOUBLE_INTEGRAL                   0x222C 0  // ∬
#define UC_MOP_TRIPLE_INTEGRAL                   0x222D 0  // ∭
#define UC_MOP_CONTOUR_INTEGRAL                  0x222E 0  // ∮
#define UC_MOP_SURFACE_INTEGRAL                  0x222F 0  // ∯
#define UC_MOP_VOLUME_INTEGRAL                   0x2230 0  // ∰
#define UC_MOP_CLOCKWISE_INTEGRAL                0x2231 0  // ∱
#define UC_MOP_CLOCKWISE_CONTOUR_INTEGRAL        0x2232 0  // ∲
#define UC_MOP_ANTICLOCKWISE_CONTOUR_INTEGRAL    0x2233 0  // ∳
#define UC_MOP_THEREFORE                         0x2234 0  // ∴
#define UC_MOP_BECAUSE                           0x2235 0  // ∵
#define UC_MOP_RATIO                             0x2236 0  // ∶
#define UC_MOP_PROPORTION                        0x2237 0  // ∷
#define UC_MOP_DOT_MINUS                         0x2238 0  // ∸
#define UC_MOP_EXCESS                            0x2239 0  // ∹
#define UC_MOP_GEOMETRIC_PROPORTION              0x223A 0  // ∺
#define UC_MOP_HOMOTHETIC                        0x223B 0  // ∻
#define UC_MOP_TILDE_OPERATOR                    0x223C 0  // ∼
#define UC_MOP_REVERSED_TILDE                    0x223D 0  // ∽
#define UC_MOP_INVERTED_LAZY_S                   0x223E 0  // ∾
#define UC_MOP_SINE_WAVE                         0x223F 0  // ∿
#define UC_MOP_WREATH_PRODUCT                    0x2240 0  // ≀
#define UC_MOP_NOT_TILDE                         0x2241 0  // ≁
#define UC_MOP_MINUS_TILDE                       0x2242 0  // ≂
#define UC_MOP_ASYMPTOTICALLY_EQUAL_TO           0x2243 0  // ≃
#define UC_MOP_NOT_ASYMPTOTICALLY_EQUAL_TO       0x2244 0  // ≄
#define UC_MOP_APPROXIMATELY_EQUAL_TO            0x2245 0  // ≅
#define UC_MOP_APPROXIMATELY_BUT_NOT_ACTUALLY_EQUAL_TO 0x2246 0  // ≆
#define UC_MOP_NEITHER_APPROXIMATELY_NOR_ACTUALLY_EQUAL_TO 0x2247 0  // ≇
#define UC_MOP_ALMOST_EQUAL_TO                   0x2248 0  // ≈
#define UC_MOP_NOT_ALMOST_EQUAL_TO               0x2249 0  // ≉
#define UC_MOP_ALMOST_EQUAL_OR_EQUAL_TO          0x224A 0  // ≊
#define UC_MOP_TRIPLE_TILDE                      0x224B 0  // ≋
#define UC_MOP_ALL_EQUAL_TO                      0x224C 0  // ≌
#define UC_MOP_EQUIVALENT_TO                     0x224D 0  // ≍
#define UC_MOP_GEOMETRICALLY_EQUIVALENT_TO       0x224E 0  // ≎
#define UC_MOP_DIFFERENCE_BETWEEN                0x224F 0  // ≏
#define UC_MOP_APPROACHES_THE_LIMIT              0x2250 0  // ≐
#define UC_MOP_GEOMETRICALLY_EQUAL_TO            0x2251 0  // ≑
#define UC_MOP_APPROXIMATELY_EQUAL_TO_OR_THE_IMAGE_OF 0x2252 0  // ≒
#define UC_MOP_IMAGE_OF_OR_APPROXIMATELY_EQUAL_TO 0x2253 0  // ≓
#define UC_MOP_COLON_EQUALS                      0x2254 0  // ≔
#define UC_MOP_EQUALS_COLON                      0x2255 0  // ≕
#define UC_MOP_RING_IN_EQUAL_TO                  0x2256 0  // ≖
#define UC_MOP_RING_EQUAL_TO                     0x2257 0  // ≗
#define UC_MOP_CORRESPONDS_TO                    0x2258 0  // ≘
#define UC_MOP_ESTIMATES                         0x2259 0  // ≙
#define UC_MOP_EQUIANGULAR_TO                    0x225A 0  // ≚
#define UC_MOP_STAR_EQUALS                       0x225B 0  // ≛
#define UC_MOP_DELTA_EQUAL_TO                    0x225C 0  // ≜
#define UC_MOP_EQUAL_TO_BY_DEFINITION            0x225D 0  // ≝
#define UC_MOP_MEASURED_BY                       0x225E 0  // ≞
#define UC_MOP_QUESTIONED_EQUAL_TO               0x225F 0  // ≟
#define UC_MOP_NOT_EQUAL_TO                      0x2260 0  // ≠
#define UC_MOP_IDENTICAL_TO                      0x2261 0  // ≡
#define UC_MOP_NOT_IDENTICAL_TO                  0x2262 0  // ≢
#define UC_MOP_STRICTLY_EQUIVALENT_TO            0x2263 0  // ≣
#define UC_MOP_LESS_THAN_OR_EQUAL_TO             0x2264 0  // ≤
#define UC_MOP_GREATER_THAN_OR_EQUAL_TO          0x2265 0  // ≥
#define UC_MOP_LESS_THAN_OVER_EQUAL_TO           0x2266 0  // ≦
#define UC_MOP_GREATER_THAN_OVER_EQUAL_TO        0x2267 0  // ≧
#define UC_MOP_LESS_THAN_BUT_NOT_EQUAL_TO        0x2268 0  // ≨
#define UC_MOP_GREATER_THAN_BUT_NOT_EQUAL_TO     0x2269 0  // ≩
#define UC_MOP_MUCH_LESS_THAN                    0x226A 0  // ≪
#define UC_MOP_MUCH_GREATER_THAN                 0x226B 0  // ≫
#define UC_MOP_BETWEEN                           0x226C 0  // ≬
#define UC_MOP_NOT_EQUIVALENT_TO                 0x226D 0  // ≭
#define UC_MOP_NOT_LESS_THAN                     0x226E 0  // ≮
#define UC_MOP_NOT_GREATER_THAN                  0x226F 0  // ≯
#define UC_MOP_NEITHER_LESS_THAN_NOR_EQUAL_TO    0x2270 0  // ≰
#define UC_MOP_NEITHER_GREATER_THAN_NOR_EQUAL_TO 0x2271 0  // ≱
#define UC_MOP_LESS_THAN_OR_EQUIVALENT_TO        0x2272 0  // ≲
#define UC_MOP_GREATER_THAN_OR_EQUIVALENT_TO     0x2273 0  // ≳
#define UC_MOP_NEITHER_LESS_THAN_NOR_EQUIVALENT_TO 0x2274 0  // ≴
#define UC_MOP_NEITHER_GREATER_THAN_NOR_EQUIVALENT_TO 0x2275 0  // ≵
#define UC_MOP_LESS_THAN_OR_GREATER_THAN         0x2276 0  // ≶
#define UC_MOP_GREATER_THAN_OR_LESS_THAN         0x2277 0  // ≷
#define UC_MOP_NEITHER_LESS_THAN_NOR_GREATER_THAN 0x2278 0  // ≸
#define UC_MOP_NEITHER_GREATER_THAN_NOR_LESS_THAN 0x2279 0  // ≹
#define UC_MOP_PRECEDES                          0x227A 0  // ≺
#define UC_MOP_SUCCEEDS                          0x227B 0  // ≻
#define UC_MOP_PRECEDES_OR_EQUAL_TO              0x227C 0  // ≼
#define UC_MOP_SUCCEEDS_OR_EQUAL_TO              0x227D 0  // ≽
#define UC_MOP_PRECEDES_OR_EQUIVALENT_TO         0x227E 0  // ≾
#define UC_MOP_SUCCEEDS_OR_EQUIVALENT_TO         0x227F 0  // ≿
#define UC_MOP_DOES_NOT_PRECEDE                  0x2280 0  // ⊀
#define UC_MOP_DOES_NOT_SUCCEED                  0x2281 0  // ⊁
#define UC_MOP_SUBSET_OF                         0x2282 0  // ⊂
#define UC_MOP_SUPERSET_OF                       0x2283 0  // ⊃
#define UC_MOP_NOT_A_SUBSET_OF                   0x2284 0  // ⊄
#define UC_MOP_NOT_A_SUPERSET_OF                 0x2285 0  // ⊅
#define UC_MOP_SUBSET_OF_OR_EQUAL_TO             0x2286 0  // ⊆
#define UC_MOP_SUPERSET_OF_OR_EQUAL_TO           0x2287 0  // ⊇
#define UC_MOP_NEITHER_A_SUBSET_OF_NOR_EQUAL_TO  0x2288 0  // ⊈
#define UC_MOP_NEITHER_A_SUPERSET_OF_NOR_EQUAL_TO 0x2289 0  // ⊉
#define UC_MOP_SUBSET_OF_NOT_EQUAL_TO            0x228A 0  // ⊊
#define UC_MOP_SUPERSET_OF_NOT_EQUAL_TO          0x228B 0  // ⊋
#define UC_MOP_MULTISET                          0x228C 0  // ⊌
#define UC_MOP_MULTISET_MULTIPLICATION           0x228D 0  // ⊍
#define UC_MOP_MULTISET_UNION                    0x228E 0  // ⊎
#define UC_MOP_SQUARE_IMAGE_OF                   0x228F 0  // ⊏
#define UC_MOP_SQUARE_ORIGINAL_OF                0x2290 0  // ⊐
#define UC_MOP_SQUARE_IMAGE_OF_OR_EQUAL_TO       0x2291 0  // ⊑
#define UC_MOP_SQUARE_ORIGINAL_OF_OR_EQUAL_TO    0x2292 0  // ⊒
#define UC_MOP_SQUARE_CAP                        0x2293 0  // ⊓
#define UC_MOP_SQUARE_CUP                        0x2294 0  // ⊔
#define UC_MOP_C_PLUS                            0x2295 0  // ⊕
#define UC_MOP_C_MINUS                           0x2296 0  // ⊖
#define UC_MOP_C_TIMES                           0x2297 0  // ⊗
#define UC_MOP_C_DIVISION_SLASH                  0x2298 0  // ⊘
#define UC_MOP_C_DOT_OPERATOR                    0x2299 0  // ⊙
#define UC_MOP_C_RING_OPERATOR                   0x229A 0  // ⊚
#define UC_MOP_C_ASTERISK_OPERATOR               0x229B 0  // ⊛
#define UC_MOP_C_EQUALS                          0x229C 0  // ⊜
#define UC_MOP_C_DASH                            0x229D 0  // ⊝
#define UC_MOP_SQUARED_PLUS                      0x229E 0  // ⊞
#define UC_MOP_SQUARED_MINUS                     0x229F 0  // ⊟
#define UC_MOP_SQUARED_TIMES                     0x22A0 0  // ⊠
#define UC_MOP_SQUARED_DOT_OPERATOR              0x22A1 0  // ⊡
#define UC_MOP_RIGHT_TACK                        0x22A2 0  // ⊢
#define UC_MOP_LEFT_TACK                         0x22A3 0  // ⊣
#define UC_MOP_DOWN_TACK                         0x22A4 0  // ⊤
#define UC_MOP_UP_TACK                           0x22A5 0  // ⊥
#define UC_MOP_ASSERTION                         0x22A6 0  // ⊦
#define UC_MOP_MODELS                            0x22A7 0  // ⊧
#define UC_MOP_TRUE                              0x22A8 0  // ⊨
#define UC_MOP_FORCES                            0x22A9 0  // ⊩
#define UC_MOP_TRIPLE_VERTICAL_BAR_RIGHT_TURNSTILE 0x22AA 0  // ⊪
#define UC_MOP_DOUBLE_VERTICAL_BAR_DOUBLE_RIGHT_TURNSTILE 0x22AB 0  // ⊫
#define UC_MOP_DOES_NOT_PROVE                    0x22AC 0  // ⊬
#define UC_MOP_NOT_TRUE                          0x22AD 0  // ⊭
#define UC_MOP_DOES_NOT_FORCE                    0x22AE 0  // ⊮
#define UC_MOP_NEGATED_DOUBLE_VERTICAL_BAR_DOUBLE_RIGHT_TURNSTILE 0x22AF 0  // ⊯
#define UC_MOP_PRECEDES_UNDER_RELATION           0x22B0 0  // ⊰
#define UC_MOP_SUCCEEDS_UNDER_RELATION           0x22B1 0  // ⊱
#define UC_MOP_NORMAL_SUBGROUP_OF                0x22B2 0  // ⊲
#define UC_MOP_CONTAINS_AS_NORMAL_SUBGROUP       0x22B3 0  // ⊳
#define UC_MOP_NORMAL_SUBGROUP_OF_OR_EQUAL_TO    0x22B4 0  // ⊴
#define UC_MOP_CONTAINS_AS_NORMAL_SUBGROUP_OR_EQUAL_TO 0x22B5 0  // ⊵
#define UC_MOP_ORIGINAL_OF                       0x22B6 0  // ⊶
#define UC_MOP_IMAGE_OF                          0x22B7 0  // ⊷
#define UC_MOP_MULTIMAP                          0x22B8 0  // ⊸
#define UC_MOP_HERMITIAN_CONJUGATE_MATRIX        0x22B9 0  // ⊹
#define UC_MOP_INTERCALATE                       0x22BA 0  // ⊺
#define UC_MOP_XOR                               0x22BB 0  // ⊻
#define UC_MOP_NAND                              0x22BC 0  // ⊼
#define UC_MOP_NOR                               0x22BD 0  // ⊽
#define UC_MOP_RIGHT_ANGLE_ARC                   0x22BE 0  // ⊾
#define UC_MOP_RIGHT_TRIANGLE                    0x22BF 0  // ⊿
#define UC_MOP_N_ARY_LOGICAL_AND                 0x22C0 0  // ⋀
#define UC_MOP_N_ARY_LOGICAL_OR                  0x22C1 0  // ⋁
#define UC_MOP_N_ARY_INTERSECTION                0x22C2 0  // ⋂
#define UC_MOP_N_ARY_UNION                       0x22C3 0  // ⋃
#define UC_MOP_DIAMOND_OPERATOR                  0x22C4 0  // ⋄
#define UC_MOP_DOT_OPERATOR                      0x22C5 0  // ⋅
#define UC_MOP_STAR_OPERATOR                     0x22C6 0  // ⋆
#define UC_MOP_DIVISION_TIMES                    0x22C7 0  // ⋇
#define UC_MOP_BOWTIE                            0x22C8 0  // ⋈
#define UC_MOP_LEFT_NORMAL_FACTOR_SEMIDIRECT_PRODUCT 0x22C9 0  // ⋉
#define UC_MOP_RIGHT_NORMAL_FACTOR_SEMIDIRECT_PRODUCT 0x22CA 0  // ⋊
#define UC_MOP_LEFT_SEMIDIRECT_PRODUCT           0x22CB 0  // ⋋
#define UC_MOP_RIGHT_SEMIDIRECT_PRODUCT          0x22CC 0  // ⋌
#define UC_MOP_REVERSED_TILDE_EQUALS             0x22CD 0  // ⋍
#define UC_MOP_CURLY_LOGICAL_OR                  0x22CE 0  // ⋎
#define UC_MOP_CURLY_LOGICAL_AND                 0x22CF 0  // ⋏
#define UC_MOP_DOUBLE_SUBSET                     0x22D0 0  // ⋐
#define UC_MOP_DOUBLE_SUPERSET                   0x22D1 0  // ⋑
#define UC_MOP_DOUBLE_INTERSECTION               0x22D2 0  // ⋒
#define UC_MOP_DOUBLE_UNION                      0x22D3 0  // ⋓
#define UC_MOP_PITCHFORK                         0x22D4 0  // ⋔
#define UC_MOP_EQUAL_AND_PARALLEL_TO             0x22D5 0  // ⋕
#define UC_MOP_LESS_THAN_DOT                     0x22D6 0  // ⋖
#define UC_MOP_GREATER_THAN_DOT                  0x22D7 0  // ⋗
#define UC_MOP_VERY_MUCH_LESS_THAN               0x22D8 0  // ⋘
#define UC_MOP_VERY_MUCH_GREATER_THAN            0x22D9 0  // ⋙
#define UC_MOP_LESS_THAN_EQUAL_TO_OR_GREATER_THAN 0x22DA 0  // ⋚
#define UC_MOP_GREATER_THAN_EQUAL_TO_OR_LESS_THAN 0x22DB 0  // ⋛
#define UC_MOP_EQUAL_TO_OR_LESS_THAN             0x22DC 0  // ⋜
#define UC_MOP_EQUAL_TO_OR_GREATER_THAN          0x22DD 0  // ⋝
#define UC_MOP_EQUAL_TO_OR_PRECEDES              0x22DE 0  // ⋞
#define UC_MOP_EQUAL_TO_OR_SUCCEEDS              0x22DF 0  // ⋟
#define UC_MOP_DOES_NOT_PRECEDE_OR_EQUAL         0x22E0 0  // ⋠
#define UC_MOP_DOES_NOT_SUCCEED_OR_EQUAL         0x22E1 0  // ⋡
#define UC_MOP_NOT_SQUARE_IMAGE_OF_OR_EQUAL_TO   0x22E2 0  // ⋢
#define UC_MOP_NOT_SQUARE_ORIGINAL_OF_OR_EQUAL_TO 0x22E3 0  // ⋣
#define UC_MOP_SQUARE_IMAGE_OF_OR_NOT_EQUAL_TO   0x22E4 0  // ⋤
#define UC_MOP_SQUARE_ORIGINAL_OF_OR_NOT_EQUAL_TO 0x22E5 0  // ⋥
#define UC_MOP_LESS_THAN_BUT_NOT_EQUIVALENT_TO   0x22E6 0  // ⋦
#define UC_MOP_GREATER_THAN_BUT_NOT_EQUIVALENT_TO 0x22E7 0  // ⋧
#define UC_MOP_PRECEDES_BUT_NOT_EQUIVALENT_TO    0x22E8 0  // ⋨
#define UC_MOP_SUCCEEDS_BUT_NOT_EQUIVALENT_TO    0x22E9 0  // ⋩
#define UC_MOP_NOT_NORMAL_SUBGROUP_OF            0x22EA 0  // ⋪
#define UC_MOP_DOES_NOT_CONTAIN_AS_NORMAL_SUBGROUP 0x22EB 0  // ⋫
#define UC_MOP_NOT_NORMAL_SUBGROUP_OF_OR_EQUAL_TO 0x22EC 0  // ⋬
#define UC_MOP_DOES_NOT_CONTAIN_AS_NORMAL_SUBGROUP_OR_EQUAL 0x22ED 0  // ⋭
#define UC_MOP_VERTICAL_ELLIPSIS                 0x22EE 0  // ⋮
#define UC_MOP_MIDLINE_HORIZONTAL_ELLIPSIS       0x22EF 0  // ⋯
#define UC_MOP_UP_RIGHT_DIAGONAL_ELLIPSIS        0x22F0 0  // ⋰
#define UC_MOP_DOWN_RIGHT_DIAGONAL_ELLIPSIS      0x22F1 0  // ⋱
#define UC_MOP_ELEMENT_OF_LONG_HORIZONTAL_STROKE 0x22F2 0  // ⋲
#define UC_MOP_ELEMENT_OF_VERTICAL_BAR_AT_END_OF_HORIZONTAL_STROKE 0x22F3 0  // ⋳
#define UC_MOP_SMALL_ELEMENT_OF_VERTICAL_BAR_AT_END_OF_HORIZONTAL_STROKE 0x22F4 0  // ⋴
#define UC_MOP_ELEMENT_OF_DOT_ABOVE              0x22F5 0  // ⋵
#define UC_MOP_ELEMENT_OF_OVERBAR                0x22F6 0  // ⋶
#define UC_MOP_SMALL_ELEMENT_OF_OVERBAR          0x22F7 0  // ⋷
#define UC_MOP_ELEMENT_OF_UNDERBAR               0x22F8 0  // ⋸
#define UC_MOP_ELEMENT_OF_TWO_HORIZONTAL_STROKES 0x22F9 0  // ⋹
#define UC_MOP_CONTAINS_LONG_HORIZONTAL_STROKE   0x22FA 0  // ⋺
#define UC_MOP_CONTAINS_VERTICAL_BAR_AT_END_OF_HORIZONTAL_STROKE 0x22FB 0  // ⋻
#define UC_MOP_SMALL_CONTAINS_VERTICAL_BAR_AT_END_OF_HORIZONTAL_STROKE 0x22FC 0  // ⋼
#define UC_MOP_CONTAINS_OVERBAR                  0x22FD 0  // ⋽
#define UC_MOP_SMALL_CONTAINS_OVERBAR            0x22FE 0  // ⋾
#define UC_MOP_Z_NOTATION_BAG_MEMBERSHIP         0x22FF 0  // ⋿
