/* modifier_tone_letters.h – Unicode constants for U+A700 … U+A71F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Modifier Tone Letters is a Unicode block containing tone markings for
 * Chinese, Chinantec , Africanist, and other phonetic transcriptions. It
 * does not contain the standard IPA tone marks, which are found in
 * Spacing Modifier Letters .
 * ⟨ ꜀◌ ꜁◌ ꜂◌ ꜃◌ ◌꜄ ◌꜅ ◌꜆ ◌꜇ ⟩ are used to mark yin and (underlined) yang
 * splits of the ping, shang, qu and ru tones, respectively, in the
 * etymological four-tone analysis of Chinese. The dotted tone letters ⟨
 * ꜈ ꜉ ꜊ ꜋ ꜌ ⟩ are used for the pitch of neutral tones , while the
 * reversed tone letters ⟨ ꜒ ꜓ ꜔ ꜕ ꜖ ⟩ and neutral ⟨ ꜍ ꜎ ꜏ ꜐ ꜑ ⟩ are used
 * for tone sandhi . ⟨ ꜗ ꜘ ꜙ ꜚ ⟩ are modifier letters used in Ozumacín
 * Chinantec . ⟨ ꜛ ꜜ ⟩ are the IPA modifier letters for upstep and
 * downstep , while ⟨ ꜝ ꜞ ꜟ ⟩ are substitutes people used before broad
 * font support of the IPA, and still preferred by some.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Modifier_Tone_Letters
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/UA700.pdf
 
* Consistency Check:
* Total Defined Code Points: 32
* Total Significant Hex Values: 32
* Status: OK (Counts Match)

*/

#pragma once

#define UC_MODIFIER_CHINESE_TONE_YIN_PING        0xA700 0  // ꜀
#define UC_MODIFIER_CHINESE_TONE_YANG_PING       0xA701 0  // ꜁
#define UC_MODIFIER_CHINESE_TONE_YIN_SHANG       0xA702 0  // ꜂
#define UC_MODIFIER_CHINESE_TONE_YANG_SHANG      0xA703 0  // ꜃
#define UC_MODIFIER_CHINESE_TONE_YIN_QU          0xA704 0  // ꜄
#define UC_MODIFIER_CHINESE_TONE_YANG_QU         0xA705 0  // ꜅
#define UC_MODIFIER_CHINESE_TONE_YIN_RU          0xA706 0  // ꜆
#define UC_MODIFIER_CHINESE_TONE_YANG_RU         0xA707 0  // ꜇
#define UC_MODIFIER_EXTRA_HIGH_DOTTED_TONE_BAR   0xA708 0  // ꜈
#define UC_MODIFIER_HIGH_DOTTED_TONE_BAR         0xA709 0  // ꜉
#define UC_MODIFIER_MID_DOTTED_TONE_BAR          0xA70A 0  // ꜊
#define UC_MODIFIER_LOW_DOTTED_TONE_BAR          0xA70B 0  // ꜋
#define UC_MODIFIER_EXTRA_LOW_DOTTED_TONE_BAR    0xA70C 0  // ꜌
#define UC_MODIFIER_EXTRA_HIGH_DOTTED_LEFT_STEM_TONE_BAR 0xA70D 0  // ꜍
#define UC_MODIFIER_HIGH_DOTTED_LEFT_STEM_TONE_BAR 0xA70E 0  // ꜎
#define UC_MODIFIER_MID_DOTTED_LEFT_STEM_TONE_BAR 0xA70F 0  // ꜏
#define UC_MODIFIER_LOW_DOTTED_LEFT_STEM_TONE_BAR 0xA710 0  // ꜐
#define UC_MODIFIER_EXTRA_LOW_DOTTED_LEFT_STEM_TONE_BAR 0xA711 0  // ꜑
#define UC_MODIFIER_EXTRA_HIGH_LEFT_STEM_TONE_BAR 0xA712 0  // ꜒
#define UC_MODIFIER_HIGH_LEFT_STEM_TONE_BAR      0xA713 0  // ꜓
#define UC_MODIFIER_MID_LEFT_STEM_TONE_BAR       0xA714 0  // ꜔
#define UC_MODIFIER_LOW_LEFT_STEM_TONE_BAR       0xA715 0  // ꜕
#define UC_MODIFIER_EXTRA_LOW_LEFT_STEM_TONE_BAR 0xA716 0  // ꜖
#define UC_MODIFIER_DOT_VERTICAL_BAR             0xA717 0  // ꜗ
#define UC_MODIFIER_DOT_SLASH                    0xA718 0  // ꜘ
#define UC_MODIFIER_DOT_HORIZONTAL_BAR           0xA719 0  // ꜙ
#define UC_MODIFIER_LOWER_RIGHT_CORNER_ANGLE     0xA71A 0  // ꜚ
#define UC_MODIFIER_RAISED_UP_ARROW              0xA71B 0  // ꜛ
#define UC_MODIFIER_RAISED_DOWN_ARROW            0xA71C 0  // ꜜ
#define UC_MODIFIER_RAISED_EXCLAMATION_MARK      0xA71D 0  // ꜝ
#define UC_MODIFIER_RAISED_INVERTED_EXCLAMATION_MARK 0xA71E 0  // ꜞ
#define UC_MODIFIER_LOW_INVERTED_EXCLAMATION_MARK 0xA71F 0  // ꜟ
