/* mongolian.h – Unicode constants for U+1800 … U+18AF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Mongolian may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Mongolian
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1800.pdf
 
* Consistency Check:
* Total Defined Code Points: 158
* Total Significant Hex Values: 158
* Status: OK (Counts Match)

*/

#pragma once

#define UC_MONGOLIAN_BIRGA                       0x1800 0  // ᠀
#define UC_MONGOLIAN_ELLIPSIS                    0x1801 0  // ᠁
#define UC_MONGOLIAN                             0x1802 0  // ᠂
#define UC_MONGOLIAN_FULL_STOP                   0x1803 0  // ᠃
#define UC_MONGOLIAN_COLON                       0x1804 0  // ᠄
#define UC_MONGOLIAN_FOUR_DOTS                   0x1805 0  // ᠅
#define UC_MONGOLIAN_TODO_SOFT_HYPHEN            0x1806 0  // ᠆
#define UC_MONGOLIAN_SIBE_SYLLABLE_BOUNDARY_MARKER 0x1807 0  // ᠇
#define UC_MONGOLIAN_MANCHU                      0x1808 0  // ᠈
#define UC_MONGOLIAN_MANCHU_FULL_STOP            0x1809 0  // ᠉
#define UC_MONGOLIAN_NIRUGU                      0x180A 0  // ᠊
#define UC_MONGOLIAN_FREE_ONE                    0x180B 0  // ᠋
#define UC_MONGOLIAN_FREE_TWO                    0x180C 0  // ᠌
#define UC_MONGOLIAN_FREE_THREE                  0x180D 0  // ᠍
#define UC_MONGOLIAN_VOWEL_SEPARATOR             0x180E 0  /* U+180E (MONGOLIAN VOWEL SEPARATOR) */
#define UC_MONGOLIAN_FREE_FOUR                   0x180F 0  // ᠏
#define UC_MONGOLIAN_ZERO                        0x1810 0  // ᠐
#define UC_MONGOLIAN_ONE                         0x1811 0  // ᠑
#define UC_MONGOLIAN_TWO                         0x1812 0  // ᠒
#define UC_MONGOLIAN_THREE                       0x1813 0  // ᠓
#define UC_MONGOLIAN_FOUR                        0x1814 0  // ᠔
#define UC_MONGOLIAN_FIVE                        0x1815 0  // ᠕
#define UC_MONGOLIAN_SIX                         0x1816 0  // ᠖
#define UC_MONGOLIAN_SEVEN                       0x1817 0  // ᠗
#define UC_MONGOLIAN_EIGHT                       0x1818 0  // ᠘
#define UC_MONGOLIAN_NINE                        0x1819 0  // ᠙
#define UC_MONGOLIAN_A                           0x1820 0  // ᠠ
#define UC_MONGOLIAN_E                           0x1821 0  // ᠡ
#define UC_MONGOLIAN_I                           0x1822 0  // ᠢ
#define UC_MONGOLIAN_O                           0x1823 0  // ᠣ
#define UC_MONGOLIAN_U                           0x1824 0  // ᠤ
#define UC_MONGOLIAN_OE                          0x1825 0  // ᠥ
#define UC_MONGOLIAN_UE                          0x1826 0  // ᠦ
#define UC_MONGOLIAN_EE                          0x1827 0  // ᠧ
#define UC_MONGOLIAN_NA                          0x1828 0  // ᠨ
#define UC_MONGOLIAN_ANG                         0x1829 0  // ᠩ
#define UC_MONGOLIAN_BA                          0x182A 0  // ᠪ
#define UC_MONGOLIAN_PA                          0x182B 0  // ᠫ
#define UC_MONGOLIAN_QA                          0x182C 0  // ᠬ
#define UC_MONGOLIAN_GA                          0x182D 0  // ᠭ
#define UC_MONGOLIAN_MA                          0x182E 0  // ᠮ
#define UC_MONGOLIAN_LA                          0x182F 0  // ᠯ
#define UC_MONGOLIAN_SA                          0x1830 0  // ᠰ
#define UC_MONGOLIAN_SHA                         0x1831 0  // ᠱ
#define UC_MONGOLIAN_TA                          0x1832 0  // ᠲ
#define UC_MONGOLIAN_DA                          0x1833 0  // ᠳ
#define UC_MONGOLIAN_CHA                         0x1834 0  // ᠴ
#define UC_MONGOLIAN_JA                          0x1835 0  // ᠵ
#define UC_MONGOLIAN_YA                          0x1836 0  // ᠶ
#define UC_MONGOLIAN_RA                          0x1837 0  // ᠷ
#define UC_MONGOLIAN_WA                          0x1838 0  // ᠸ
#define UC_MONGOLIAN_FA                          0x1839 0  // ᠹ
#define UC_MONGOLIAN_KA                          0x183A 0  // ᠺ
#define UC_MONGOLIAN_KHA                         0x183B 0  // ᠻ
#define UC_MONGOLIAN_TSA                         0x183C 0  // ᠼ
#define UC_MONGOLIAN_ZA                          0x183D 0  // ᠽ
#define UC_MONGOLIAN_HAA                         0x183E 0  // ᠾ
#define UC_MONGOLIAN_ZRA                         0x183F 0  // ᠿ
#define UC_MONGOLIAN_LHA                         0x1840 0  // ᡀ
#define UC_MONGOLIAN_ZHI                         0x1841 0  // ᡁ
#define UC_MONGOLIAN_CHI                         0x1842 0  // ᡂ
#define UC_MONGOLIAN_TODO_LONG_VOWEL_SIGN        0x1843 0  // ᡃ
#define UC_MONGOLIAN_TODO_E                      0x1844 0  // ᡄ
#define UC_MONGOLIAN_TODO_I                      0x1845 0  // ᡅ
#define UC_MONGOLIAN_TODO_O                      0x1846 0  // ᡆ
#define UC_MONGOLIAN_TODO_U                      0x1847 0  // ᡇ
#define UC_MONGOLIAN_TODO_OE                     0x1848 0  // ᡈ
#define UC_MONGOLIAN_TODO_UE                     0x1849 0  // ᡉ
#define UC_MONGOLIAN_TODO_ANG                    0x184A 0  // ᡊ
#define UC_MONGOLIAN_TODO_BA                     0x184B 0  // ᡋ
#define UC_MONGOLIAN_TODO_PA                     0x184C 0  // ᡌ
#define UC_MONGOLIAN_TODO_QA                     0x184D 0  // ᡍ
#define UC_MONGOLIAN_TODO_GA                     0x184E 0  // ᡎ
#define UC_MONGOLIAN_TODO_MA                     0x184F 0  // ᡏ
#define UC_MONGOLIAN_TODO_TA                     0x1850 0  // ᡐ
#define UC_MONGOLIAN_TODO_DA                     0x1851 0  // ᡑ
#define UC_MONGOLIAN_TODO_CHA                    0x1852 0  // ᡒ
#define UC_MONGOLIAN_TODO_JA                     0x1853 0  // ᡓ
#define UC_MONGOLIAN_TODO_TSA                    0x1854 0  // ᡔ
#define UC_MONGOLIAN_TODO_YA                     0x1855 0  // ᡕ
#define UC_MONGOLIAN_TODO_WA                     0x1856 0  // ᡖ
#define UC_MONGOLIAN_TODO_KA                     0x1857 0  // ᡗ
#define UC_MONGOLIAN_TODO_GAA                    0x1858 0  // ᡘ
#define UC_MONGOLIAN_TODO_HAA                    0x1859 0  // ᡙ
#define UC_MONGOLIAN_TODO_JIA                    0x185A 0  // ᡚ
#define UC_MONGOLIAN_TODO_NIA                    0x185B 0  // ᡛ
#define UC_MONGOLIAN_TODO_DZA                    0x185C 0  // ᡜ
#define UC_MONGOLIAN_SIBE_E                      0x185D 0  // ᡝ
#define UC_MONGOLIAN_SIBE_I                      0x185E 0  // ᡞ
#define UC_MONGOLIAN_SIBE_IY                     0x185F 0  // ᡟ
#define UC_MONGOLIAN_SIBE_UE                     0x1860 0  // ᡠ
#define UC_MONGOLIAN_SIBE_U                      0x1861 0  // ᡡ
#define UC_MONGOLIAN_SIBE_ANG                    0x1862 0  // ᡢ
#define UC_MONGOLIAN_SIBE_KA                     0x1863 0  // ᡣ
#define UC_MONGOLIAN_SIBE_GA                     0x1864 0  // ᡤ
#define UC_MONGOLIAN_SIBE_HA                     0x1865 0  // ᡥ
#define UC_MONGOLIAN_SIBE_PA                     0x1866 0  // ᡦ
#define UC_MONGOLIAN_SIBE_SHA                    0x1867 0  // ᡧ
#define UC_MONGOLIAN_SIBE_TA                     0x1868 0  // ᡨ
#define UC_MONGOLIAN_SIBE_DA                     0x1869 0  // ᡩ
#define UC_MONGOLIAN_SIBE_JA                     0x186A 0  // ᡪ
#define UC_MONGOLIAN_SIBE_FA                     0x186B 0  // ᡫ
#define UC_MONGOLIAN_SIBE_GAA                    0x186C 0  // ᡬ
#define UC_MONGOLIAN_SIBE_HAA                    0x186D 0  // ᡭ
#define UC_MONGOLIAN_SIBE_TSA                    0x186E 0  // ᡮ
#define UC_MONGOLIAN_SIBE_ZA                     0x186F 0  // ᡯ
#define UC_MONGOLIAN_SIBE_RAA                    0x1870 0  // ᡰ
#define UC_MONGOLIAN_SIBE_CHA                    0x1871 0  // ᡱ
#define UC_MONGOLIAN_SIBE_ZHA                    0x1872 0  // ᡲ
#define UC_MONGOLIAN_MANCHU_I                    0x1873 0  // ᡳ
#define UC_MONGOLIAN_MANCHU_KA                   0x1874 0  // ᡴ
#define UC_MONGOLIAN_MANCHU_RA                   0x1875 0  // ᡵ
#define UC_MONGOLIAN_MANCHU_FA                   0x1876 0  // ᡶ
#define UC_MONGOLIAN_MANCHU_ZHA                  0x1877 0  // ᡷ
#define UC_MONGOLIAN_CHA_TWO_DOTS                0x1878 0  // ᡸ
#define UC_MONGOLIAN_ALI_GALI_ANUSVARA_ONE       0x1880 0  // ᢀ
#define UC_MONGOLIAN_ALI_GALI_VISARGA_ONE        0x1881 0  // ᢁ
#define UC_MONGOLIAN_ALI_GALI_DAMARU             0x1882 0  // ᢂ
#define UC_MONGOLIAN_ALI_GALI_UBADAMA            0x1883 0  // ᢃ
#define UC_MONGOLIAN_ALI_GALI_INVERTED_UBADAMA   0x1884 0  // ᢄ
#define UC_MONGOLIAN_ALI_GALI_BALUDA             0x1885 0  // ᢅ
#define UC_MONGOLIAN_ALI_GALI_THREE_BALUDA       0x1886 0  // ᢆ
#define UC_MONGOLIAN_ALI_GALI_A                  0x1887 0  // ᢇ
#define UC_MONGOLIAN_ALI_GALI_I                  0x1888 0  // ᢈ
#define UC_MONGOLIAN_ALI_GALI_KA                 0x1889 0  // ᢉ
#define UC_MONGOLIAN_ALI_GALI_NGA                0x188A 0  // ᢊ
#define UC_MONGOLIAN_ALI_GALI_CA                 0x188B 0  // ᢋ
#define UC_MONGOLIAN_ALI_GALI_TTA                0x188C 0  // ᢌ
#define UC_MONGOLIAN_ALI_GALI_TTHA               0x188D 0  // ᢍ
#define UC_MONGOLIAN_ALI_GALI_DDA                0x188E 0  // ᢎ
#define UC_MONGOLIAN_ALI_GALI_NNA                0x188F 0  // ᢏ
#define UC_MONGOLIAN_ALI_GALI_TA                 0x1890 0  // ᢐ
#define UC_MONGOLIAN_ALI_GALI_DA                 0x1891 0  // ᢑ
#define UC_MONGOLIAN_ALI_GALI_PA                 0x1892 0  // ᢒ
#define UC_MONGOLIAN_ALI_GALI_PHA                0x1893 0  // ᢓ
#define UC_MONGOLIAN_ALI_GALI_SSA                0x1894 0  // ᢔ
#define UC_MONGOLIAN_ALI_GALI_ZHA                0x1895 0  // ᢕ
#define UC_MONGOLIAN_ALI_GALI_ZA                 0x1896 0  // ᢖ
#define UC_MONGOLIAN_ALI_GALI_AH                 0x1897 0  // ᢗ
#define UC_MONGOLIAN_TODO_ALI_GALI_TA            0x1898 0  // ᢘ
#define UC_MONGOLIAN_TODO_ALI_GALI_ZHA           0x1899 0  // ᢙ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_GHA         0x189A 0  // ᢚ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_NGA         0x189B 0  // ᢛ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_CA          0x189C 0  // ᢜ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_JHA         0x189D 0  // ᢝ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_TTA         0x189E 0  // ᢞ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_DDHA        0x189F 0  // ᢟ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_TA          0x18A0 0  // ᢠ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_DHA         0x18A1 0  // ᢡ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_SSA         0x18A2 0  // ᢢ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_CYA         0x18A3 0  // ᢣ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_ZHA         0x18A4 0  // ᢤ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_ZA          0x18A5 0  // ᢥ
#define UC_MONGOLIAN_ALI_GALI_HALF_U             0x18A6 0  // ᢦ
#define UC_MONGOLIAN_ALI_GALI_HALF_YA            0x18A7 0  // ᢧ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_BHA         0x18A8 0  // ᢨ
#define UC_MONGOLIAN_ALI_GALI_DAGALGA            0x18A9 0  // ᢩ
#define UC_MONGOLIAN_MANCHU_ALI_GALI_LHA         0x18AA 0  // ᢪ
