/* nag_mundari.h – Unicode constants for U+1E4D0 … U+1E4FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Mundari Bani (Mundari: 𞓧𞓟𞓨𞓜𞓕𞓣𞓚 𞓗𞓕𞓨𞓚 Mundari Bani 'Mundari alphabet',
 * also known as Mundari Bani Hisir Hisir 'writing', Nag Mundari 𞓨𞓕𞓦
 * 𞓧𞓟𞓨𞓜𞓕𞓣𞓚 , or the Mundari alphabet ) is the writing system created for
 * the Mundari language , spoken in eastern India. Mundari is an
 * Austroasiatic language. Mundari Bani has 27 letters and five
 * diacritics, the forms of which are intended to evoke natural shapes.
 * The script is written from left to right .
 * Community elder and author Rohidas Singh Nag invented and published in
 * late 1980 the alphabetic writing system Mundari Bani, which has seen
 * limited but increasing use in literature, education, and computing.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Nag_Mundari
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1E4D0.pdf
 
* Consistency Check:
* Total Defined Code Points: 42
* Total Significant Hex Values: 42
* Status: OK (Counts Match)

*/

#pragma once

#define UC_NAG_MUNDARI_O                         0x1E4D0 0  // 𞓐
#define UC_NAG_MUNDARI_OP                        0x1E4D1 0  // 𞓑
#define UC_NAG_MUNDARI_OL                        0x1E4D2 0  // 𞓒
#define UC_NAG_MUNDARI_OY                        0x1E4D3 0  // 𞓓
#define UC_NAG_MUNDARI_ONG                       0x1E4D4 0  // 𞓔
#define UC_NAG_MUNDARI_A                         0x1E4D5 0  // 𞓕
#define UC_NAG_MUNDARI_AJ                        0x1E4D6 0  // 𞓖
#define UC_NAG_MUNDARI_AB                        0x1E4D7 0  // 𞓗
#define UC_NAG_MUNDARI_ANY                       0x1E4D8 0  // 𞓘
#define UC_NAG_MUNDARI_AH                        0x1E4D9 0  // 𞓙
#define UC_NAG_MUNDARI_I                         0x1E4DA 0  // 𞓚
#define UC_NAG_MUNDARI_IS                        0x1E4DB 0  // 𞓛
#define UC_NAG_MUNDARI_IDD                       0x1E4DC 0  // 𞓜
#define UC_NAG_MUNDARI_IT                        0x1E4DD 0  // 𞓝
#define UC_NAG_MUNDARI_IH                        0x1E4DE 0  // 𞓞
#define UC_NAG_MUNDARI_U                         0x1E4DF 0  // 𞓟
#define UC_NAG_MUNDARI_UC                        0x1E4E0 0  // 𞓠
#define UC_NAG_MUNDARI_UD                        0x1E4E1 0  // 𞓡
#define UC_NAG_MUNDARI_UK                        0x1E4E2 0  // 𞓢
#define UC_NAG_MUNDARI_UR                        0x1E4E3 0  // 𞓣
#define UC_NAG_MUNDARI_E                         0x1E4E4 0  // 𞓤
#define UC_NAG_MUNDARI_ENN                       0x1E4E5 0  // 𞓥
#define UC_NAG_MUNDARI_EG                        0x1E4E6 0  // 𞓦
#define UC_NAG_MUNDARI_EM                        0x1E4E7 0  // 𞓧
#define UC_NAG_MUNDARI_EN                        0x1E4E8 0  // 𞓨
#define UC_NAG_MUNDARI_ETT                       0x1E4E9 0  // 𞓩
#define UC_NAG_MUNDARI_ELL                       0x1E4EA 0  // 𞓪
#define UC_NAG_MUNDARI_SIGN_OJOD                 0x1E4EB 0  // 𞓫
#define UC_NAG_MUNDARI_SIGN_MUHOR                0x1E4EC 0  // 𞓬
#define UC_NAG_MUNDARI_SIGN_TOYOR                0x1E4ED 0  // 𞓭
#define UC_NAG_MUNDARI_SIGN_IKIR                 0x1E4EE 0  // 𞓮
#define UC_NAG_MUNDARI_SIGN_SUTUH                0x1E4EF 0  // 𞓯
#define UC_NAG_MUNDARI_ZERO                      0x1E4F0 0  // 𞓰
#define UC_NAG_MUNDARI_ONE                       0x1E4F1 0  // 𞓱
#define UC_NAG_MUNDARI_TWO                       0x1E4F2 0  // 𞓲
#define UC_NAG_MUNDARI_THREE                     0x1E4F3 0  // 𞓳
#define UC_NAG_MUNDARI_FOUR                      0x1E4F4 0  // 𞓴
#define UC_NAG_MUNDARI_FIVE                      0x1E4F5 0  // 𞓵
#define UC_NAG_MUNDARI_SIX                       0x1E4F6 0  // 𞓶
#define UC_NAG_MUNDARI_SEVEN                     0x1E4F7 0  // 𞓷
#define UC_NAG_MUNDARI_EIGHT                     0x1E4F8 0  // 𞓸
#define UC_NAG_MUNDARI_NINE                      0x1E4F9 0  // 𞓹
