/* nushu.h – Unicode constants for U+1B170 … U+1B2FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Nushu
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1B170.pdf
 
* Consistency Check:
* Total Defined Code Points: 396
* Total Significant Hex Values: 396
* Status: OK (Counts Match)

*/

#pragma once

#define UC_NUSHU_1B170                           0x1B170 0  // 𛅰
#define UC_NUSHU_1B171                           0x1B171 0  // 𛅱
#define UC_NUSHU_1B172                           0x1B172 0  // 𛅲
#define UC_NUSHU_1B173                           0x1B173 0  // 𛅳
#define UC_NUSHU_1B174                           0x1B174 0  // 𛅴
#define UC_NUSHU_1B175                           0x1B175 0  // 𛅵
#define UC_NUSHU_1B176                           0x1B176 0  // 𛅶
#define UC_NUSHU_1B177                           0x1B177 0  // 𛅷
#define UC_NUSHU_1B178                           0x1B178 0  // 𛅸
#define UC_NUSHU_1B179                           0x1B179 0  // 𛅹
#define UC_NUSHU_1B17A                           0x1B17A 0  // 𛅺
#define UC_NUSHU_1B17B                           0x1B17B 0  // 𛅻
#define UC_NUSHU_1B17C                           0x1B17C 0  // 𛅼
#define UC_NUSHU_1B17D                           0x1B17D 0  // 𛅽
#define UC_NUSHU_1B17E                           0x1B17E 0  // 𛅾
#define UC_NUSHU_1B17F                           0x1B17F 0  // 𛅿
#define UC_NUSHU_1B180                           0x1B180 0  // 𛆀
#define UC_NUSHU_1B181                           0x1B181 0  // 𛆁
#define UC_NUSHU_1B182                           0x1B182 0  // 𛆂
#define UC_NUSHU_1B183                           0x1B183 0  // 𛆃
#define UC_NUSHU_1B184                           0x1B184 0  // 𛆄
#define UC_NUSHU_1B185                           0x1B185 0  // 𛆅
#define UC_NUSHU_1B186                           0x1B186 0  // 𛆆
#define UC_NUSHU_1B187                           0x1B187 0  // 𛆇
#define UC_NUSHU_1B188                           0x1B188 0  // 𛆈
#define UC_NUSHU_1B189                           0x1B189 0  // 𛆉
#define UC_NUSHU_1B18A                           0x1B18A 0  // 𛆊
#define UC_NUSHU_1B18B                           0x1B18B 0  // 𛆋
#define UC_NUSHU_1B18C                           0x1B18C 0  // 𛆌
#define UC_NUSHU_1B18D                           0x1B18D 0  // 𛆍
#define UC_NUSHU_1B18E                           0x1B18E 0  // 𛆎
#define UC_NUSHU_1B18F                           0x1B18F 0  // 𛆏
#define UC_NUSHU_1B190                           0x1B190 0  // 𛆐
#define UC_NUSHU_1B191                           0x1B191 0  // 𛆑
#define UC_NUSHU_1B192                           0x1B192 0  // 𛆒
#define UC_NUSHU_1B193                           0x1B193 0  // 𛆓
#define UC_NUSHU_1B194                           0x1B194 0  // 𛆔
#define UC_NUSHU_1B195                           0x1B195 0  // 𛆕
#define UC_NUSHU_1B196                           0x1B196 0  // 𛆖
#define UC_NUSHU_1B197                           0x1B197 0  // 𛆗
#define UC_NUSHU_1B198                           0x1B198 0  // 𛆘
#define UC_NUSHU_1B199                           0x1B199 0  // 𛆙
#define UC_NUSHU_1B19A                           0x1B19A 0  // 𛆚
#define UC_NUSHU_1B19B                           0x1B19B 0  // 𛆛
#define UC_NUSHU_1B19C                           0x1B19C 0  // 𛆜
#define UC_NUSHU_1B19D                           0x1B19D 0  // 𛆝
#define UC_NUSHU_1B19E                           0x1B19E 0  // 𛆞
#define UC_NUSHU_1B19F                           0x1B19F 0  // 𛆟
#define UC_NUSHU_1B1A0                           0x1B1A0 0  // 𛆠
#define UC_NUSHU_1B1A1                           0x1B1A1 0  // 𛆡
#define UC_NUSHU_1B1A2                           0x1B1A2 0  // 𛆢
#define UC_NUSHU_1B1A3                           0x1B1A3 0  // 𛆣
#define UC_NUSHU_1B1A4                           0x1B1A4 0  // 𛆤
#define UC_NUSHU_1B1A5                           0x1B1A5 0  // 𛆥
#define UC_NUSHU_1B1A6                           0x1B1A6 0  // 𛆦
#define UC_NUSHU_1B1A7                           0x1B1A7 0  // 𛆧
#define UC_NUSHU_1B1A8                           0x1B1A8 0  // 𛆨
#define UC_NUSHU_1B1A9                           0x1B1A9 0  // 𛆩
#define UC_NUSHU_1B1AA                           0x1B1AA 0  // 𛆪
#define UC_NUSHU_1B1AB                           0x1B1AB 0  // 𛆫
#define UC_NUSHU_1B1AC                           0x1B1AC 0  // 𛆬
#define UC_NUSHU_1B1AD                           0x1B1AD 0  // 𛆭
#define UC_NUSHU_1B1AE                           0x1B1AE 0  // 𛆮
#define UC_NUSHU_1B1AF                           0x1B1AF 0  // 𛆯
#define UC_NUSHU_1B1B0                           0x1B1B0 0  // 𛆰
#define UC_NUSHU_1B1B1                           0x1B1B1 0  // 𛆱
#define UC_NUSHU_1B1B2                           0x1B1B2 0  // 𛆲
#define UC_NUSHU_1B1B3                           0x1B1B3 0  // 𛆳
#define UC_NUSHU_1B1B4                           0x1B1B4 0  // 𛆴
#define UC_NUSHU_1B1B5                           0x1B1B5 0  // 𛆵
#define UC_NUSHU_1B1B6                           0x1B1B6 0  // 𛆶
#define UC_NUSHU_1B1B7                           0x1B1B7 0  // 𛆷
#define UC_NUSHU_1B1B8                           0x1B1B8 0  // 𛆸
#define UC_NUSHU_1B1B9                           0x1B1B9 0  // 𛆹
#define UC_NUSHU_1B1BA                           0x1B1BA 0  // 𛆺
#define UC_NUSHU_1B1BB                           0x1B1BB 0  // 𛆻
#define UC_NUSHU_1B1BC                           0x1B1BC 0  // 𛆼
#define UC_NUSHU_1B1BD                           0x1B1BD 0  // 𛆽
#define UC_NUSHU_1B1BE                           0x1B1BE 0  // 𛆾
#define UC_NUSHU_1B1BF                           0x1B1BF 0  // 𛆿
#define UC_NUSHU_1B1C0                           0x1B1C0 0  // 𛇀
#define UC_NUSHU_1B1C1                           0x1B1C1 0  // 𛇁
#define UC_NUSHU_1B1C2                           0x1B1C2 0  // 𛇂
#define UC_NUSHU_1B1C3                           0x1B1C3 0  // 𛇃
#define UC_NUSHU_1B1C4                           0x1B1C4 0  // 𛇄
#define UC_NUSHU_1B1C5                           0x1B1C5 0  // 𛇅
#define UC_NUSHU_1B1C6                           0x1B1C6 0  // 𛇆
#define UC_NUSHU_1B1C7                           0x1B1C7 0  // 𛇇
#define UC_NUSHU_1B1C8                           0x1B1C8 0  // 𛇈
#define UC_NUSHU_1B1C9                           0x1B1C9 0  // 𛇉
#define UC_NUSHU_1B1CA                           0x1B1CA 0  // 𛇊
#define UC_NUSHU_1B1CB                           0x1B1CB 0  // 𛇋
#define UC_NUSHU_1B1CC                           0x1B1CC 0  // 𛇌
#define UC_NUSHU_1B1CD                           0x1B1CD 0  // 𛇍
#define UC_NUSHU_1B1CE                           0x1B1CE 0  // 𛇎
#define UC_NUSHU_1B1CF                           0x1B1CF 0  // 𛇏
#define UC_NUSHU_1B1D0                           0x1B1D0 0  // 𛇐
#define UC_NUSHU_1B1D1                           0x1B1D1 0  // 𛇑
#define UC_NUSHU_1B1D2                           0x1B1D2 0  // 𛇒
#define UC_NUSHU_1B1D3                           0x1B1D3 0  // 𛇓
#define UC_NUSHU_1B1D4                           0x1B1D4 0  // 𛇔
#define UC_NUSHU_1B1D5                           0x1B1D5 0  // 𛇕
#define UC_NUSHU_1B1D6                           0x1B1D6 0  // 𛇖
#define UC_NUSHU_1B1D7                           0x1B1D7 0  // 𛇗
#define UC_NUSHU_1B1D8                           0x1B1D8 0  // 𛇘
#define UC_NUSHU_1B1D9                           0x1B1D9 0  // 𛇙
#define UC_NUSHU_1B1DA                           0x1B1DA 0  // 𛇚
#define UC_NUSHU_1B1DB                           0x1B1DB 0  // 𛇛
#define UC_NUSHU_1B1DC                           0x1B1DC 0  // 𛇜
#define UC_NUSHU_1B1DD                           0x1B1DD 0  // 𛇝
#define UC_NUSHU_1B1DE                           0x1B1DE 0  // 𛇞
#define UC_NUSHU_1B1DF                           0x1B1DF 0  // 𛇟
#define UC_NUSHU_1B1E0                           0x1B1E0 0  // 𛇠
#define UC_NUSHU_1B1E1                           0x1B1E1 0  // 𛇡
#define UC_NUSHU_1B1E2                           0x1B1E2 0  // 𛇢
#define UC_NUSHU_1B1E3                           0x1B1E3 0  // 𛇣
#define UC_NUSHU_1B1E4                           0x1B1E4 0  // 𛇤
#define UC_NUSHU_1B1E5                           0x1B1E5 0  // 𛇥
#define UC_NUSHU_1B1E6                           0x1B1E6 0  // 𛇦
#define UC_NUSHU_1B1E7                           0x1B1E7 0  // 𛇧
#define UC_NUSHU_1B1E8                           0x1B1E8 0  // 𛇨
#define UC_NUSHU_1B1E9                           0x1B1E9 0  // 𛇩
#define UC_NUSHU_1B1EA                           0x1B1EA 0  // 𛇪
#define UC_NUSHU_1B1EB                           0x1B1EB 0  // 𛇫
#define UC_NUSHU_1B1EC                           0x1B1EC 0  // 𛇬
#define UC_NUSHU_1B1ED                           0x1B1ED 0  // 𛇭
#define UC_NUSHU_1B1EE                           0x1B1EE 0  // 𛇮
#define UC_NUSHU_1B1EF                           0x1B1EF 0  // 𛇯
#define UC_NUSHU_1B1F0                           0x1B1F0 0  // 𛇰
#define UC_NUSHU_1B1F1                           0x1B1F1 0  // 𛇱
#define UC_NUSHU_1B1F2                           0x1B1F2 0  // 𛇲
#define UC_NUSHU_1B1F3                           0x1B1F3 0  // 𛇳
#define UC_NUSHU_1B1F4                           0x1B1F4 0  // 𛇴
#define UC_NUSHU_1B1F5                           0x1B1F5 0  // 𛇵
#define UC_NUSHU_1B1F6                           0x1B1F6 0  // 𛇶
#define UC_NUSHU_1B1F7                           0x1B1F7 0  // 𛇷
#define UC_NUSHU_1B1F8                           0x1B1F8 0  // 𛇸
#define UC_NUSHU_1B1F9                           0x1B1F9 0  // 𛇹
#define UC_NUSHU_1B1FA                           0x1B1FA 0  // 𛇺
#define UC_NUSHU_1B1FB                           0x1B1FB 0  // 𛇻
#define UC_NUSHU_1B1FC                           0x1B1FC 0  // 𛇼
#define UC_NUSHU_1B1FD                           0x1B1FD 0  // 𛇽
#define UC_NUSHU_1B1FE                           0x1B1FE 0  // 𛇾
#define UC_NUSHU_1B1FF                           0x1B1FF 0  // 𛇿
#define UC_NUSHU_1B200                           0x1B200 0  // 𛈀
#define UC_NUSHU_1B201                           0x1B201 0  // 𛈁
#define UC_NUSHU_1B202                           0x1B202 0  // 𛈂
#define UC_NUSHU_1B203                           0x1B203 0  // 𛈃
#define UC_NUSHU_1B204                           0x1B204 0  // 𛈄
#define UC_NUSHU_1B205                           0x1B205 0  // 𛈅
#define UC_NUSHU_1B206                           0x1B206 0  // 𛈆
#define UC_NUSHU_1B207                           0x1B207 0  // 𛈇
#define UC_NUSHU_1B208                           0x1B208 0  // 𛈈
#define UC_NUSHU_1B209                           0x1B209 0  // 𛈉
#define UC_NUSHU_1B20A                           0x1B20A 0  // 𛈊
#define UC_NUSHU_1B20B                           0x1B20B 0  // 𛈋
#define UC_NUSHU_1B20C                           0x1B20C 0  // 𛈌
#define UC_NUSHU_1B20D                           0x1B20D 0  // 𛈍
#define UC_NUSHU_1B20E                           0x1B20E 0  // 𛈎
#define UC_NUSHU_1B20F                           0x1B20F 0  // 𛈏
#define UC_NUSHU_1B210                           0x1B210 0  // 𛈐
#define UC_NUSHU_1B211                           0x1B211 0  // 𛈑
#define UC_NUSHU_1B212                           0x1B212 0  // 𛈒
#define UC_NUSHU_1B213                           0x1B213 0  // 𛈓
#define UC_NUSHU_1B214                           0x1B214 0  // 𛈔
#define UC_NUSHU_1B215                           0x1B215 0  // 𛈕
#define UC_NUSHU_1B216                           0x1B216 0  // 𛈖
#define UC_NUSHU_1B217                           0x1B217 0  // 𛈗
#define UC_NUSHU_1B218                           0x1B218 0  // 𛈘
#define UC_NUSHU_1B219                           0x1B219 0  // 𛈙
#define UC_NUSHU_1B21A                           0x1B21A 0  // 𛈚
#define UC_NUSHU_1B21B                           0x1B21B 0  // 𛈛
#define UC_NUSHU_1B21C                           0x1B21C 0  // 𛈜
#define UC_NUSHU_1B21D                           0x1B21D 0  // 𛈝
#define UC_NUSHU_1B21E                           0x1B21E 0  // 𛈞
#define UC_NUSHU_1B21F                           0x1B21F 0  // 𛈟
#define UC_NUSHU_1B220                           0x1B220 0  // 𛈠
#define UC_NUSHU_1B221                           0x1B221 0  // 𛈡
#define UC_NUSHU_1B222                           0x1B222 0  // 𛈢
#define UC_NUSHU_1B223                           0x1B223 0  // 𛈣
#define UC_NUSHU_1B224                           0x1B224 0  // 𛈤
#define UC_NUSHU_1B225                           0x1B225 0  // 𛈥
#define UC_NUSHU_1B226                           0x1B226 0  // 𛈦
#define UC_NUSHU_1B227                           0x1B227 0  // 𛈧
#define UC_NUSHU_1B228                           0x1B228 0  // 𛈨
#define UC_NUSHU_1B229                           0x1B229 0  // 𛈩
#define UC_NUSHU_1B22A                           0x1B22A 0  // 𛈪
#define UC_NUSHU_1B22B                           0x1B22B 0  // 𛈫
#define UC_NUSHU_1B22C                           0x1B22C 0  // 𛈬
#define UC_NUSHU_1B22D                           0x1B22D 0  // 𛈭
#define UC_NUSHU_1B22E                           0x1B22E 0  // 𛈮
#define UC_NUSHU_1B22F                           0x1B22F 0  // 𛈯
#define UC_NUSHU_1B230                           0x1B230 0  // 𛈰
#define UC_NUSHU_1B231                           0x1B231 0  // 𛈱
#define UC_NUSHU_1B232                           0x1B232 0  // 𛈲
#define UC_NUSHU_1B233                           0x1B233 0  // 𛈳
#define UC_NUSHU_1B234                           0x1B234 0  // 𛈴
#define UC_NUSHU_1B235                           0x1B235 0  // 𛈵
#define UC_NUSHU_1B236                           0x1B236 0  // 𛈶
#define UC_NUSHU_1B237                           0x1B237 0  // 𛈷
#define UC_NUSHU_1B238                           0x1B238 0  // 𛈸
#define UC_NUSHU_1B239                           0x1B239 0  // 𛈹
#define UC_NUSHU_1B23A                           0x1B23A 0  // 𛈺
#define UC_NUSHU_1B23B                           0x1B23B 0  // 𛈻
#define UC_NUSHU_1B23C                           0x1B23C 0  // 𛈼
#define UC_NUSHU_1B23D                           0x1B23D 0  // 𛈽
#define UC_NUSHU_1B23E                           0x1B23E 0  // 𛈾
#define UC_NUSHU_1B23F                           0x1B23F 0  // 𛈿
#define UC_NUSHU_1B240                           0x1B240 0  // 𛉀
#define UC_NUSHU_1B241                           0x1B241 0  // 𛉁
#define UC_NUSHU_1B242                           0x1B242 0  // 𛉂
#define UC_NUSHU_1B243                           0x1B243 0  // 𛉃
#define UC_NUSHU_1B244                           0x1B244 0  // 𛉄
#define UC_NUSHU_1B245                           0x1B245 0  // 𛉅
#define UC_NUSHU_1B246                           0x1B246 0  // 𛉆
#define UC_NUSHU_1B247                           0x1B247 0  // 𛉇
#define UC_NUSHU_1B248                           0x1B248 0  // 𛉈
#define UC_NUSHU_1B249                           0x1B249 0  // 𛉉
#define UC_NUSHU_1B24A                           0x1B24A 0  // 𛉊
#define UC_NUSHU_1B24B                           0x1B24B 0  // 𛉋
#define UC_NUSHU_1B24C                           0x1B24C 0  // 𛉌
#define UC_NUSHU_1B24D                           0x1B24D 0  // 𛉍
#define UC_NUSHU_1B24E                           0x1B24E 0  // 𛉎
#define UC_NUSHU_1B24F                           0x1B24F 0  // 𛉏
#define UC_NUSHU_1B250                           0x1B250 0  // 𛉐
#define UC_NUSHU_1B251                           0x1B251 0  // 𛉑
#define UC_NUSHU_1B252                           0x1B252 0  // 𛉒
#define UC_NUSHU_1B253                           0x1B253 0  // 𛉓
#define UC_NUSHU_1B254                           0x1B254 0  // 𛉔
#define UC_NUSHU_1B255                           0x1B255 0  // 𛉕
#define UC_NUSHU_1B256                           0x1B256 0  // 𛉖
#define UC_NUSHU_1B257                           0x1B257 0  // 𛉗
#define UC_NUSHU_1B258                           0x1B258 0  // 𛉘
#define UC_NUSHU_1B259                           0x1B259 0  // 𛉙
#define UC_NUSHU_1B25A                           0x1B25A 0  // 𛉚
#define UC_NUSHU_1B25B                           0x1B25B 0  // 𛉛
#define UC_NUSHU_1B25C                           0x1B25C 0  // 𛉜
#define UC_NUSHU_1B25D                           0x1B25D 0  // 𛉝
#define UC_NUSHU_1B25E                           0x1B25E 0  // 𛉞
#define UC_NUSHU_1B25F                           0x1B25F 0  // 𛉟
#define UC_NUSHU_1B260                           0x1B260 0  // 𛉠
#define UC_NUSHU_1B261                           0x1B261 0  // 𛉡
#define UC_NUSHU_1B262                           0x1B262 0  // 𛉢
#define UC_NUSHU_1B263                           0x1B263 0  // 𛉣
#define UC_NUSHU_1B264                           0x1B264 0  // 𛉤
#define UC_NUSHU_1B265                           0x1B265 0  // 𛉥
#define UC_NUSHU_1B266                           0x1B266 0  // 𛉦
#define UC_NUSHU_1B267                           0x1B267 0  // 𛉧
#define UC_NUSHU_1B268                           0x1B268 0  // 𛉨
#define UC_NUSHU_1B269                           0x1B269 0  // 𛉩
#define UC_NUSHU_1B26A                           0x1B26A 0  // 𛉪
#define UC_NUSHU_1B26B                           0x1B26B 0  // 𛉫
#define UC_NUSHU_1B26C                           0x1B26C 0  // 𛉬
#define UC_NUSHU_1B26D                           0x1B26D 0  // 𛉭
#define UC_NUSHU_1B26E                           0x1B26E 0  // 𛉮
#define UC_NUSHU_1B26F                           0x1B26F 0  // 𛉯
#define UC_NUSHU_1B270                           0x1B270 0  // 𛉰
#define UC_NUSHU_1B271                           0x1B271 0  // 𛉱
#define UC_NUSHU_1B272                           0x1B272 0  // 𛉲
#define UC_NUSHU_1B273                           0x1B273 0  // 𛉳
#define UC_NUSHU_1B274                           0x1B274 0  // 𛉴
#define UC_NUSHU_1B275                           0x1B275 0  // 𛉵
#define UC_NUSHU_1B276                           0x1B276 0  // 𛉶
#define UC_NUSHU_1B277                           0x1B277 0  // 𛉷
#define UC_NUSHU_1B278                           0x1B278 0  // 𛉸
#define UC_NUSHU_1B279                           0x1B279 0  // 𛉹
#define UC_NUSHU_1B27A                           0x1B27A 0  // 𛉺
#define UC_NUSHU_1B27B                           0x1B27B 0  // 𛉻
#define UC_NUSHU_1B27C                           0x1B27C 0  // 𛉼
#define UC_NUSHU_1B27D                           0x1B27D 0  // 𛉽
#define UC_NUSHU_1B27E                           0x1B27E 0  // 𛉾
#define UC_NUSHU_1B27F                           0x1B27F 0  // 𛉿
#define UC_NUSHU_1B280                           0x1B280 0  // 𛊀
#define UC_NUSHU_1B281                           0x1B281 0  // 𛊁
#define UC_NUSHU_1B282                           0x1B282 0  // 𛊂
#define UC_NUSHU_1B283                           0x1B283 0  // 𛊃
#define UC_NUSHU_1B284                           0x1B284 0  // 𛊄
#define UC_NUSHU_1B285                           0x1B285 0  // 𛊅
#define UC_NUSHU_1B286                           0x1B286 0  // 𛊆
#define UC_NUSHU_1B287                           0x1B287 0  // 𛊇
#define UC_NUSHU_1B288                           0x1B288 0  // 𛊈
#define UC_NUSHU_1B289                           0x1B289 0  // 𛊉
#define UC_NUSHU_1B28A                           0x1B28A 0  // 𛊊
#define UC_NUSHU_1B28B                           0x1B28B 0  // 𛊋
#define UC_NUSHU_1B28C                           0x1B28C 0  // 𛊌
#define UC_NUSHU_1B28D                           0x1B28D 0  // 𛊍
#define UC_NUSHU_1B28E                           0x1B28E 0  // 𛊎
#define UC_NUSHU_1B28F                           0x1B28F 0  // 𛊏
#define UC_NUSHU_1B290                           0x1B290 0  // 𛊐
#define UC_NUSHU_1B291                           0x1B291 0  // 𛊑
#define UC_NUSHU_1B292                           0x1B292 0  // 𛊒
#define UC_NUSHU_1B293                           0x1B293 0  // 𛊓
#define UC_NUSHU_1B294                           0x1B294 0  // 𛊔
#define UC_NUSHU_1B295                           0x1B295 0  // 𛊕
#define UC_NUSHU_1B296                           0x1B296 0  // 𛊖
#define UC_NUSHU_1B297                           0x1B297 0  // 𛊗
#define UC_NUSHU_1B298                           0x1B298 0  // 𛊘
#define UC_NUSHU_1B299                           0x1B299 0  // 𛊙
#define UC_NUSHU_1B29A                           0x1B29A 0  // 𛊚
#define UC_NUSHU_1B29B                           0x1B29B 0  // 𛊛
#define UC_NUSHU_1B29C                           0x1B29C 0  // 𛊜
#define UC_NUSHU_1B29D                           0x1B29D 0  // 𛊝
#define UC_NUSHU_1B29E                           0x1B29E 0  // 𛊞
#define UC_NUSHU_1B29F                           0x1B29F 0  // 𛊟
#define UC_NUSHU_1B2A0                           0x1B2A0 0  // 𛊠
#define UC_NUSHU_1B2A1                           0x1B2A1 0  // 𛊡
#define UC_NUSHU_1B2A2                           0x1B2A2 0  // 𛊢
#define UC_NUSHU_1B2A3                           0x1B2A3 0  // 𛊣
#define UC_NUSHU_1B2A4                           0x1B2A4 0  // 𛊤
#define UC_NUSHU_1B2A5                           0x1B2A5 0  // 𛊥
#define UC_NUSHU_1B2A6                           0x1B2A6 0  // 𛊦
#define UC_NUSHU_1B2A7                           0x1B2A7 0  // 𛊧
#define UC_NUSHU_1B2A8                           0x1B2A8 0  // 𛊨
#define UC_NUSHU_1B2A9                           0x1B2A9 0  // 𛊩
#define UC_NUSHU_1B2AA                           0x1B2AA 0  // 𛊪
#define UC_NUSHU_1B2AB                           0x1B2AB 0  // 𛊫
#define UC_NUSHU_1B2AC                           0x1B2AC 0  // 𛊬
#define UC_NUSHU_1B2AD                           0x1B2AD 0  // 𛊭
#define UC_NUSHU_1B2AE                           0x1B2AE 0  // 𛊮
#define UC_NUSHU_1B2AF                           0x1B2AF 0  // 𛊯
#define UC_NUSHU_1B2B0                           0x1B2B0 0  // 𛊰
#define UC_NUSHU_1B2B1                           0x1B2B1 0  // 𛊱
#define UC_NUSHU_1B2B2                           0x1B2B2 0  // 𛊲
#define UC_NUSHU_1B2B3                           0x1B2B3 0  // 𛊳
#define UC_NUSHU_1B2B4                           0x1B2B4 0  // 𛊴
#define UC_NUSHU_1B2B5                           0x1B2B5 0  // 𛊵
#define UC_NUSHU_1B2B6                           0x1B2B6 0  // 𛊶
#define UC_NUSHU_1B2B7                           0x1B2B7 0  // 𛊷
#define UC_NUSHU_1B2B8                           0x1B2B8 0  // 𛊸
#define UC_NUSHU_1B2B9                           0x1B2B9 0  // 𛊹
#define UC_NUSHU_1B2BA                           0x1B2BA 0  // 𛊺
#define UC_NUSHU_1B2BB                           0x1B2BB 0  // 𛊻
#define UC_NUSHU_1B2BC                           0x1B2BC 0  // 𛊼
#define UC_NUSHU_1B2BD                           0x1B2BD 0  // 𛊽
#define UC_NUSHU_1B2BE                           0x1B2BE 0  // 𛊾
#define UC_NUSHU_1B2BF                           0x1B2BF 0  // 𛊿
#define UC_NUSHU_1B2C0                           0x1B2C0 0  // 𛋀
#define UC_NUSHU_1B2C1                           0x1B2C1 0  // 𛋁
#define UC_NUSHU_1B2C2                           0x1B2C2 0  // 𛋂
#define UC_NUSHU_1B2C3                           0x1B2C3 0  // 𛋃
#define UC_NUSHU_1B2C4                           0x1B2C4 0  // 𛋄
#define UC_NUSHU_1B2C5                           0x1B2C5 0  // 𛋅
#define UC_NUSHU_1B2C6                           0x1B2C6 0  // 𛋆
#define UC_NUSHU_1B2C7                           0x1B2C7 0  // 𛋇
#define UC_NUSHU_1B2C8                           0x1B2C8 0  // 𛋈
#define UC_NUSHU_1B2C9                           0x1B2C9 0  // 𛋉
#define UC_NUSHU_1B2CA                           0x1B2CA 0  // 𛋊
#define UC_NUSHU_1B2CB                           0x1B2CB 0  // 𛋋
#define UC_NUSHU_1B2CC                           0x1B2CC 0  // 𛋌
#define UC_NUSHU_1B2CD                           0x1B2CD 0  // 𛋍
#define UC_NUSHU_1B2CE                           0x1B2CE 0  // 𛋎
#define UC_NUSHU_1B2CF                           0x1B2CF 0  // 𛋏
#define UC_NUSHU_1B2D0                           0x1B2D0 0  // 𛋐
#define UC_NUSHU_1B2D1                           0x1B2D1 0  // 𛋑
#define UC_NUSHU_1B2D2                           0x1B2D2 0  // 𛋒
#define UC_NUSHU_1B2D3                           0x1B2D3 0  // 𛋓
#define UC_NUSHU_1B2D4                           0x1B2D4 0  // 𛋔
#define UC_NUSHU_1B2D5                           0x1B2D5 0  // 𛋕
#define UC_NUSHU_1B2D6                           0x1B2D6 0  // 𛋖
#define UC_NUSHU_1B2D7                           0x1B2D7 0  // 𛋗
#define UC_NUSHU_1B2D8                           0x1B2D8 0  // 𛋘
#define UC_NUSHU_1B2D9                           0x1B2D9 0  // 𛋙
#define UC_NUSHU_1B2DA                           0x1B2DA 0  // 𛋚
#define UC_NUSHU_1B2DB                           0x1B2DB 0  // 𛋛
#define UC_NUSHU_1B2DC                           0x1B2DC 0  // 𛋜
#define UC_NUSHU_1B2DD                           0x1B2DD 0  // 𛋝
#define UC_NUSHU_1B2DE                           0x1B2DE 0  // 𛋞
#define UC_NUSHU_1B2DF                           0x1B2DF 0  // 𛋟
#define UC_NUSHU_1B2E0                           0x1B2E0 0  // 𛋠
#define UC_NUSHU_1B2E1                           0x1B2E1 0  // 𛋡
#define UC_NUSHU_1B2E2                           0x1B2E2 0  // 𛋢
#define UC_NUSHU_1B2E3                           0x1B2E3 0  // 𛋣
#define UC_NUSHU_1B2E4                           0x1B2E4 0  // 𛋤
#define UC_NUSHU_1B2E5                           0x1B2E5 0  // 𛋥
#define UC_NUSHU_1B2E6                           0x1B2E6 0  // 𛋦
#define UC_NUSHU_1B2E7                           0x1B2E7 0  // 𛋧
#define UC_NUSHU_1B2E8                           0x1B2E8 0  // 𛋨
#define UC_NUSHU_1B2E9                           0x1B2E9 0  // 𛋩
#define UC_NUSHU_1B2EA                           0x1B2EA 0  // 𛋪
#define UC_NUSHU_1B2EB                           0x1B2EB 0  // 𛋫
#define UC_NUSHU_1B2EC                           0x1B2EC 0  // 𛋬
#define UC_NUSHU_1B2ED                           0x1B2ED 0  // 𛋭
#define UC_NUSHU_1B2EE                           0x1B2EE 0  // 𛋮
#define UC_NUSHU_1B2EF                           0x1B2EF 0  // 𛋯
#define UC_NUSHU_1B2F0                           0x1B2F0 0  // 𛋰
#define UC_NUSHU_1B2F1                           0x1B2F1 0  // 𛋱
#define UC_NUSHU_1B2F2                           0x1B2F2 0  // 𛋲
#define UC_NUSHU_1B2F3                           0x1B2F3 0  // 𛋳
#define UC_NUSHU_1B2F4                           0x1B2F4 0  // 𛋴
#define UC_NUSHU_1B2F5                           0x1B2F5 0  // 𛋵
#define UC_NUSHU_1B2F6                           0x1B2F6 0  // 𛋶
#define UC_NUSHU_1B2F7                           0x1B2F7 0  // 𛋷
#define UC_NUSHU_1B2F8                           0x1B2F8 0  // 𛋸
#define UC_NUSHU_1B2F9                           0x1B2F9 0  // 𛋹
#define UC_NUSHU_1B2FA                           0x1B2FA 0  // 𛋺
#define UC_NUSHU_1B2FB                           0x1B2FB 0  // 𛋻
