/* ol_onal.h – Unicode constants for U+1E5D0 … U+1E5FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * The Ol Onal , also known as also known as Bhumij Lipi or Bhumij Onal ,
 * is an alphabetic writing system for the Bhumij language . Ol Onal
 * script was created between 1981 and 1992 by Ol Guru Mahendra Nath
 * Sardar . Ol Onal script is used to write the Bhumij language in some
 * parts of West Bengal , Jharkhand , Orissa , and Assam .
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Ol_Onal
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1E5D0.pdf
 
* Consistency Check:
* Total Defined Code Points: 44
* Total Significant Hex Values: 44
* Status: OK (Counts Match)

*/

#pragma once

#define UC_OL_ONAL_O                             0x1E5D0 0  // 𞗐
#define UC_OL_ONAL_OM                            0x1E5D1 0  // 𞗑
#define UC_OL_ONAL_ONG                           0x1E5D2 0  // 𞗒
#define UC_OL_ONAL_ORR                           0x1E5D3 0  // 𞗓
#define UC_OL_ONAL_OO                            0x1E5D4 0  // 𞗔
#define UC_OL_ONAL_OY                            0x1E5D5 0  // 𞗕
#define UC_OL_ONAL_A                             0x1E5D6 0  // 𞗖
#define UC_OL_ONAL_AD                            0x1E5D7 0  // 𞗗
#define UC_OL_ONAL_AB                            0x1E5D8 0  // 𞗘
#define UC_OL_ONAL_AH                            0x1E5D9 0  // 𞗙
#define UC_OL_ONAL_AL                            0x1E5DA 0  // 𞗚
#define UC_OL_ONAL_AW                            0x1E5DB 0  // 𞗛
#define UC_OL_ONAL_I                             0x1E5DC 0  // 𞗜
#define UC_OL_ONAL_IT                            0x1E5DD 0  // 𞗝
#define UC_OL_ONAL_IP                            0x1E5DE 0  // 𞗞
#define UC_OL_ONAL_ITT                           0x1E5DF 0  // 𞗟
#define UC_OL_ONAL_ID                            0x1E5E0 0  // 𞗠
#define UC_OL_ONAL_IN                            0x1E5E1 0  // 𞗡
#define UC_OL_ONAL_U                             0x1E5E2 0  // 𞗢
#define UC_OL_ONAL_UK                            0x1E5E3 0  // 𞗣
#define UC_OL_ONAL_UDD                           0x1E5E4 0  // 𞗤
#define UC_OL_ONAL_UJ                            0x1E5E5 0  // 𞗥
#define UC_OL_ONAL_UNY                           0x1E5E6 0  // 𞗦
#define UC_OL_ONAL_UR                            0x1E5E7 0  // 𞗧
#define UC_OL_ONAL_E                             0x1E5E8 0  // 𞗨
#define UC_OL_ONAL_ES                            0x1E5E9 0  // 𞗩
#define UC_OL_ONAL_EH                            0x1E5EA 0  // 𞗪
#define UC_OL_ONAL_EC                            0x1E5EB 0  // 𞗫
#define UC_OL_ONAL_ENN                           0x1E5EC 0  // 𞗬
#define UC_OL_ONAL_EG                            0x1E5ED 0  // 𞗭
#define UC_OL_ONAL_SIGN_MU                       0x1E5EE 0  // 𞗮
#define UC_OL_ONAL_SIGN_IKIR                     0x1E5EF 0  // 𞗯
#define UC_OL_ONAL_SIGN_HODDOND                  0x1E5F0 0  // 𞗰
#define UC_OL_ONAL_ZERO                          0x1E5F1 0  // 𞗱
#define UC_OL_ONAL_ONE                           0x1E5F2 0  // 𞗲
#define UC_OL_ONAL_TWO                           0x1E5F3 0  // 𞗳
#define UC_OL_ONAL_THREE                         0x1E5F4 0  // 𞗴
#define UC_OL_ONAL_FOUR                          0x1E5F5 0  // 𞗵
#define UC_OL_ONAL_FIVE                          0x1E5F6 0  // 𞗶
#define UC_OL_ONAL_SIX                           0x1E5F7 0  // 𞗷
#define UC_OL_ONAL_SEVEN                         0x1E5F8 0  // 𞗸
#define UC_OL_ONAL_EIGHT                         0x1E5F9 0  // 𞗹
#define UC_OL_ONAL_NINE                          0x1E5FA 0  // 𞗺
#define UC_OL_ONAL_ABBREVIATION_SIGN             0x1E5FF 0  // 𞗿
