/* oriya.h – Unicode constants for U+0B00 … U+0B7F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Oriya (also spelled Odia ) may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Oriya
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U0B00.pdf
 
* Consistency Check:
* Total Defined Code Points: 91
* Total Significant Hex Values: 91
* Status: OK (Counts Match)

*/

#pragma once

#define UC_OR_ORIYA_SIGN_CANDRABINDU             0x0B01 0  // ଁ
#define UC_OR_ORIYA_SIGN_ANUSVARA                0x0B02 0  // ଂ
#define UC_OR_ORIYA_SIGN_VISARGA                 0x0B03 0  // ଃ
#define UC_OR_ORIYA_A                            0x0B05 0  // ଅ
#define UC_OR_ORIYA_AA                           0x0B06 0  // ଆ
#define UC_OR_ORIYA_I                            0x0B07 0  // ଇ
#define UC_OR_ORIYA_II                           0x0B08 0  // ଈ
#define UC_OR_ORIYA_U                            0x0B09 0  // ଉ
#define UC_OR_ORIYA_UU                           0x0B0A 0  // ଊ
#define UC_OR_ORIYA_VOCALIC_R                    0x0B0B 0  // ଋ
#define UC_OR_ORIYA_VOCALIC_L                    0x0B0C 0  // ଌ
#define UC_OR_ORIYA_E                            0x0B0F 0  // ଏ
#define UC_OR_ORIYA_AI                           0x0B10 0  // ଐ
#define UC_OR_ORIYA_O                            0x0B13 0  // ଓ
#define UC_OR_ORIYA_AU                           0x0B14 0  // ଔ
#define UC_OR_ORIYA_KA                           0x0B15 0  // କ
#define UC_OR_ORIYA_KHA                          0x0B16 0  // ଖ
#define UC_OR_ORIYA_GA                           0x0B17 0  // ଗ
#define UC_OR_ORIYA_GHA                          0x0B18 0  // ଘ
#define UC_OR_ORIYA_NGA                          0x0B19 0  // ଙ
#define UC_OR_ORIYA_CA                           0x0B1A 0  // ଚ
#define UC_OR_ORIYA_CHA                          0x0B1B 0  // ଛ
#define UC_OR_ORIYA_JA                           0x0B1C 0  // ଜ
#define UC_OR_ORIYA_JHA                          0x0B1D 0  // ଝ
#define UC_OR_ORIYA_NYA                          0x0B1E 0  // ଞ
#define UC_OR_ORIYA_TTA                          0x0B1F 0  // ଟ
#define UC_OR_ORIYA_TTHA                         0x0B20 0  // ଠ
#define UC_OR_ORIYA_DDA                          0x0B21 0  // ଡ
#define UC_OR_ORIYA_DDHA                         0x0B22 0  // ଢ
#define UC_OR_ORIYA_NNA                          0x0B23 0  // ଣ
#define UC_OR_ORIYA_TA                           0x0B24 0  // ତ
#define UC_OR_ORIYA_THA                          0x0B25 0  // ଥ
#define UC_OR_ORIYA_DA                           0x0B26 0  // ଦ
#define UC_OR_ORIYA_DHA                          0x0B27 0  // ଧ
#define UC_OR_ORIYA_NA                           0x0B28 0  // ନ
#define UC_OR_ORIYA_PA                           0x0B2A 0  // ପ
#define UC_OR_ORIYA_PHA                          0x0B2B 0  // ଫ
#define UC_OR_ORIYA_BA                           0x0B2C 0  // ବ
#define UC_OR_ORIYA_BHA                          0x0B2D 0  // ଭ
#define UC_OR_ORIYA_MA                           0x0B2E 0  // ମ
#define UC_OR_ORIYA_YA                           0x0B2F 0  // ଯ
#define UC_OR_ORIYA_RA                           0x0B30 0  // ର
#define UC_OR_ORIYA_LA                           0x0B32 0  // ଲ
#define UC_OR_ORIYA_LLA                          0x0B33 0  // ଳ
#define UC_OR_ORIYA_VA                           0x0B35 0  // ଵ
#define UC_OR_ORIYA_SHA                          0x0B36 0  // ଶ
#define UC_OR_ORIYA_SSA                          0x0B37 0  // ଷ
#define UC_OR_ORIYA_SA                           0x0B38 0  // ସ
#define UC_OR_ORIYA_HA                           0x0B39 0  // ହ
#define UC_OR_ORIYA_SIGN_NUKTA                   0x0B3C 0  // ଼
#define UC_OR_ORIYA_SIGN_AVAGRAHA                0x0B3D 0  // ଽ
#define UC_OR_ORIYA_VOWEL_SIGN_AA                0x0B3E 0  // ା
#define UC_OR_ORIYA_VOWEL_SIGN_I                 0x0B3F 0  // ି
#define UC_OR_ORIYA_VOWEL_SIGN_II                0x0B40 0  // ୀ
#define UC_OR_ORIYA_VOWEL_SIGN_U                 0x0B41 0  // ୁ
#define UC_OR_ORIYA_VOWEL_SIGN_UU                0x0B42 0  // ୂ
#define UC_OR_ORIYA_VOWEL_SIGN_VOCALIC_R         0x0B43 0  // ୃ
#define UC_OR_ORIYA_VOWEL_SIGN_VOCALIC_RR        0x0B44 0  // ୄ
#define UC_OR_ORIYA_VOWEL_SIGN_E                 0x0B47 0  // େ
#define UC_OR_ORIYA_VOWEL_SIGN_AI                0x0B48 0  // ୈ
#define UC_OR_ORIYA_VOWEL_SIGN_O                 0x0B4B 0  // ୋ
#define UC_OR_ORIYA_VOWEL_SIGN_AU                0x0B4C 0  // ୌ
#define UC_OR_ORIYA_SIGN_VIRAMA                  0x0B4D 0  // ୍
#define UC_OR_ORIYA_SIGN_OVERLINE                0x0B55 0  // ୕
#define UC_OR_ORIYA_AI_LENGTH_MARK               0x0B56 0  // ୖ
#define UC_OR_ORIYA_AU_LENGTH_MARK               0x0B57 0  // ୗ
#define UC_OR_ORIYA_RRA                          0x0B5C 0  // ଡ଼
#define UC_OR_ORIYA_RHA                          0x0B5D 0  // ଢ଼
#define UC_OR_ORIYA_YYA                          0x0B5F 0  // ୟ
#define UC_OR_ORIYA_VOCALIC_RR                   0x0B60 0  // ୠ
#define UC_OR_ORIYA_VOCALIC_LL                   0x0B61 0  // ୡ
#define UC_OR_ORIYA_VOWEL_SIGN_VOCALIC_L         0x0B62 0  // ୢ
#define UC_OR_ORIYA_VOWEL_SIGN_VOCALIC_LL        0x0B63 0  // ୣ
#define UC_OR_ORIYA_ZERO                         0x0B66 0  // ୦
#define UC_OR_ORIYA_ONE                          0x0B67 0  // ୧
#define UC_OR_ORIYA_TWO                          0x0B68 0  // ୨
#define UC_OR_ORIYA_THREE                        0x0B69 0  // ୩
#define UC_OR_ORIYA_FOUR                         0x0B6A 0  // ୪
#define UC_OR_ORIYA_FIVE                         0x0B6B 0  // ୫
#define UC_OR_ORIYA_SIX                          0x0B6C 0  // ୬
#define UC_OR_ORIYA_SEVEN                        0x0B6D 0  // ୭
#define UC_OR_ORIYA_EIGHT                        0x0B6E 0  // ୮
#define UC_OR_ORIYA_NINE                         0x0B6F 0  // ୯
#define UC_OR_ORIYA_ISSHAR                       0x0B70 0  // ୰
#define UC_OR_ORIYA_WA                           0x0B71 0  // ୱ
#define UC_OR_ORIYA_FRACTION_ONE_QUARTER         0x0B72 0  // ୲
#define UC_OR_ORIYA_FRACTION_ONE_HALF            0x0B73 0  // ୳
#define UC_OR_ORIYA_FRACTION_THREE_QUARTERS      0x0B74 0  // ୴
#define UC_OR_ORIYA_FRACTION_ONE_SIXTEENTH       0x0B75 0  // ୵
#define UC_OR_ORIYA_FRACTION_ONE_EIGHTH          0x0B76 0  // ୶
#define UC_OR_ORIYA_FRACTION_THREE_SIXTEENTHS    0x0B77 0  // ୷
