/* osmanya.h – Unicode constants for U+10480 … U+104AF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Osmanya ( Farta Cismaanya , 𐒍𐒖𐒇𐒂𐒖 𐒋𐒘𐒈𐒑𐒛𐒒𐒕𐒖 ), known in Somali as Far
 * Soomaali ( 𐒍𐒖𐒇 𐒈𐒝𐒑𐒛𐒐𐒘 , "Somali writing") and in Arabic as al-kitābah
 * al-ʿuthmānīyah ( الكتابة العثمانية ; "Osman writing"), is an
 * alphabetic script created to transcribe the Somali language . It was
 * invented by Osman Yusuf Kenadid , the son of Sultan Yusuf Ali Kenadid
 * and brother of Sultan Ali Yusuf Kenadid of the Sultanate of Hobyo .
 * Material written in the script is 'almost non-existent,' so it is
 * difficult to describe its use with certainty.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Osmanya
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U10480.pdf
 
* Consistency Check:
* Total Defined Code Points: 40
* Total Significant Hex Values: 40
* Status: OK (Counts Match)

*/

#pragma once

#define UC_OSMANYA_ALEF                          0x10480 0  // 𐒀
#define UC_OSMANYA_BA                            0x10481 0  // 𐒁
#define UC_OSMANYA_TA                            0x10482 0  // 𐒂
#define UC_OSMANYA_JA                            0x10483 0  // 𐒃
#define UC_OSMANYA_XA                            0x10484 0  // 𐒄
#define UC_OSMANYA_KHA                           0x10485 0  // 𐒅
#define UC_OSMANYA_DEEL                          0x10486 0  // 𐒆
#define UC_OSMANYA_RA                            0x10487 0  // 𐒇
#define UC_OSMANYA_SA                            0x10488 0  // 𐒈
#define UC_OSMANYA_SHIIN                         0x10489 0  // 𐒉
#define UC_OSMANYA_DHA                           0x1048A 0  // 𐒊
#define UC_OSMANYA_CAYN                          0x1048B 0  // 𐒋
#define UC_OSMANYA_GA                            0x1048C 0  // 𐒌
#define UC_OSMANYA_FA                            0x1048D 0  // 𐒍
#define UC_OSMANYA_QAAF                          0x1048E 0  // 𐒎
#define UC_OSMANYA_KAAF                          0x1048F 0  // 𐒏
#define UC_OSMANYA_LAAN                          0x10490 0  // 𐒐
#define UC_OSMANYA_MIIN                          0x10491 0  // 𐒑
#define UC_OSMANYA_NUUN                          0x10492 0  // 𐒒
#define UC_OSMANYA_WAW                           0x10493 0  // 𐒓
#define UC_OSMANYA_HA                            0x10494 0  // 𐒔
#define UC_OSMANYA_YA                            0x10495 0  // 𐒕
#define UC_OSMANYA_A                             0x10496 0  // 𐒖
#define UC_OSMANYA_E                             0x10497 0  // 𐒗
#define UC_OSMANYA_I                             0x10498 0  // 𐒘
#define UC_OSMANYA_O                             0x10499 0  // 𐒙
#define UC_OSMANYA_U                             0x1049A 0  // 𐒚
#define UC_OSMANYA_AA                            0x1049B 0  // 𐒛
#define UC_OSMANYA_EE                            0x1049C 0  // 𐒜
#define UC_OSMANYA_OO                            0x1049D 0  // 𐒝
#define UC_OSMANYA_ZERO                          0x104A0 0  // 𐒠
#define UC_OSMANYA_ONE                           0x104A1 0  // 𐒡
#define UC_OSMANYA_TWO                           0x104A2 0  // 𐒢
#define UC_OSMANYA_THREE                         0x104A3 0  // 𐒣
#define UC_OSMANYA_FOUR                          0x104A4 0  // 𐒤
#define UC_OSMANYA_FIVE                          0x104A5 0  // 𐒥
#define UC_OSMANYA_SIX                           0x104A6 0  // 𐒦
#define UC_OSMANYA_SEVEN                         0x104A7 0  // 𐒧
#define UC_OSMANYA_EIGHT                         0x104A8 0  // 𐒨
#define UC_OSMANYA_NINE                          0x104A9 0  // 𐒩
