/* rumi_numeral_symbols.h – Unicode constants for U+10E60 … U+10E7F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Wikipedia: https://en.wikipedia.org/wiki/Rumi_Numeral_Symbols
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U10E60.pdf
 
* Consistency Check:
* Total Defined Code Points: 31
* Total Significant Hex Values: 31
* Status: OK (Counts Match)

*/

#pragma once

#define UC_RUMI_ONE                              0x10E60 0  // 𐹠
#define UC_RUMI_TWO                              0x10E61 0  // 𐹡
#define UC_RUMI_THREE                            0x10E62 0  // 𐹢
#define UC_RUMI_FOUR                             0x10E63 0  // 𐹣
#define UC_RUMI_FIVE                             0x10E64 0  // 𐹤
#define UC_RUMI_SIX                              0x10E65 0  // 𐹥
#define UC_RUMI_SEVEN                            0x10E66 0  // 𐹦
#define UC_RUMI_EIGHT                            0x10E67 0  // 𐹧
#define UC_RUMI_NINE                             0x10E68 0  // 𐹨
#define UC_RUMI_TEN                              0x10E69 0  // 𐹩
#define UC_RUMI_TWENTY                           0x10E6A 0  // 𐹪
#define UC_RUMI_THIRTY                           0x10E6B 0  // 𐹫
#define UC_RUMI_FORTY                            0x10E6C 0  // 𐹬
#define UC_RUMI_FIFTY                            0x10E6D 0  // 𐹭
#define UC_RUMI_SIXTY                            0x10E6E 0  // 𐹮
#define UC_RUMI_SEVENTY                          0x10E6F 0  // 𐹯
#define UC_RUMI_EIGHTY                           0x10E70 0  // 𐹰
#define UC_RUMI_NINETY                           0x10E71 0  // 𐹱
#define UC_RUMI_ONE_HUNDRED                      0x10E72 0  // 𐹲
#define UC_RUMI_TWO_HUNDRED                      0x10E73 0  // 𐹳
#define UC_RUMI_THREE_HUNDRED                    0x10E74 0  // 𐹴
#define UC_RUMI_FOUR_HUNDRED                     0x10E75 0  // 𐹵
#define UC_RUMI_FIVE_HUNDRED                     0x10E76 0  // 𐹶
#define UC_RUMI_SIX_HUNDRED                      0x10E77 0  // 𐹷
#define UC_RUMI_SEVEN_HUNDRED                    0x10E78 0  // 𐹸
#define UC_RUMI_EIGHT_HUNDRED                    0x10E79 0  // 𐹹
#define UC_RUMI_NINE_HUNDRED                     0x10E7A 0  // 𐹺
#define UC_RUMI_FRACTION_ONE_HALF                0x10E7B 0  // 𐹻
#define UC_RUMI_FRACTION_ONE_QUARTER             0x10E7C 0  // 𐹼
#define UC_RUMI_FRACTION_ONE_THIRD               0x10E7D 0  // 𐹽
#define UC_RUMI_FRACTION_TWO_THIRDS              0x10E7E 0  // 𐹾
