/* sundanese.h – Unicode constants for U+1B80 … U+1BBF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Sundanese may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Sundanese
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1B80.pdf
 
* Consistency Check:
* Total Defined Code Points: 64
* Total Significant Hex Values: 64
* Status: OK (Counts Match)

*/

#pragma once

#define UC_SUNDANESE_SIGN_PANYECEK               0x1B80 0  // ᮀ
#define UC_SUNDANESE_SIGN_PANGLAYAR              0x1B81 0  // ᮁ
#define UC_SUNDANESE_SIGN_PANGWISAD              0x1B82 0  // ᮂ
#define UC_SUNDANESE_A                           0x1B83 0  // ᮃ
#define UC_SUNDANESE_I                           0x1B84 0  // ᮄ
#define UC_SUNDANESE_U                           0x1B85 0  // ᮅ
#define UC_SUNDANESE_AE                          0x1B86 0  // ᮆ
#define UC_SUNDANESE_O                           0x1B87 0  // ᮇ
#define UC_SUNDANESE_E                           0x1B88 0  // ᮈ
#define UC_SUNDANESE_EU                          0x1B89 0  // ᮉ
#define UC_SUNDANESE_KA                          0x1B8A 0  // ᮊ
#define UC_SUNDANESE_QA                          0x1B8B 0  // ᮋ
#define UC_SUNDANESE_GA                          0x1B8C 0  // ᮌ
#define UC_SUNDANESE_NGA                         0x1B8D 0  // ᮍ
#define UC_SUNDANESE_CA                          0x1B8E 0  // ᮎ
#define UC_SUNDANESE_JA                          0x1B8F 0  // ᮏ
#define UC_SUNDANESE_ZA                          0x1B90 0  // ᮐ
#define UC_SUNDANESE_NYA                         0x1B91 0  // ᮑ
#define UC_SUNDANESE_TA                          0x1B92 0  // ᮒ
#define UC_SUNDANESE_DA                          0x1B93 0  // ᮓ
#define UC_SUNDANESE_NA                          0x1B94 0  // ᮔ
#define UC_SUNDANESE_PA                          0x1B95 0  // ᮕ
#define UC_SUNDANESE_FA                          0x1B96 0  // ᮖ
#define UC_SUNDANESE_VA                          0x1B97 0  // ᮗ
#define UC_SUNDANESE_BA                          0x1B98 0  // ᮘ
#define UC_SUNDANESE_MA                          0x1B99 0  // ᮙ
#define UC_SUNDANESE_YA                          0x1B9A 0  // ᮚ
#define UC_SUNDANESE_RA                          0x1B9B 0  // ᮛ
#define UC_SUNDANESE_LA                          0x1B9C 0  // ᮜ
#define UC_SUNDANESE_WA                          0x1B9D 0  // ᮝ
#define UC_SUNDANESE_SA                          0x1B9E 0  // ᮞ
#define UC_SUNDANESE_XA                          0x1B9F 0  // ᮟ
#define UC_SUNDANESE_HA                          0x1BA0 0  // ᮠ
#define UC_SUNDANESE_CONSONANT_SIGN_PAMINGKAL    0x1BA1 0  // ᮡ
#define UC_SUNDANESE_CONSONANT_SIGN_PANYAKRA     0x1BA2 0  // ᮢ
#define UC_SUNDANESE_CONSONANT_SIGN_PANYIKU      0x1BA3 0  // ᮣ
#define UC_SUNDANESE_VOWEL_SIGN_PANGHULU         0x1BA4 0  // ᮤ
#define UC_SUNDANESE_VOWEL_SIGN_PANYUKU          0x1BA5 0  // ᮥ
#define UC_SUNDANESE_VOWEL_SIGN_PANAELAENG       0x1BA6 0  // ᮦ
#define UC_SUNDANESE_VOWEL_SIGN_PANOLONG         0x1BA7 0  // ᮧ
#define UC_SUNDANESE_VOWEL_SIGN_PAMEPET          0x1BA8 0  // ᮨ
#define UC_SUNDANESE_VOWEL_SIGN_PANEULEUNG       0x1BA9 0  // ᮩ
#define UC_SUNDANESE_SIGN_PAMAAEH                0x1BAA 0  // ᮪
#define UC_SUNDANESE_SIGN_VIRAMA                 0x1BAB 0  // ᮫
#define UC_SUNDANESE_CONSONANT_SIGN_PASANGAN_MA  0x1BAC 0  // ᮬ
#define UC_SUNDANESE_CONSONANT_SIGN_PASANGAN_WA  0x1BAD 0  // ᮭ
#define UC_SUNDANESE_KHA                         0x1BAE 0  // ᮮ
#define UC_SUNDANESE_SYA                         0x1BAF 0  // ᮯ
#define UC_SUNDANESE_ZERO                        0x1BB0 0  // ᮰
#define UC_SUNDANESE_ONE                         0x1BB1 0  // ᮱
#define UC_SUNDANESE_TWO                         0x1BB2 0  // ᮲
#define UC_SUNDANESE_THREE                       0x1BB3 0  // ᮳
#define UC_SUNDANESE_FOUR                        0x1BB4 0  // ᮴
#define UC_SUNDANESE_FIVE                        0x1BB5 0  // ᮵
#define UC_SUNDANESE_SIX                         0x1BB6 0  // ᮶
#define UC_SUNDANESE_SEVEN                       0x1BB7 0  // ᮷
#define UC_SUNDANESE_EIGHT                       0x1BB8 0  // ᮸
#define UC_SUNDANESE_NINE                        0x1BB9 0  // ᮹
#define UC_SUNDANESE_AVAGRAHA                    0x1BBA 0  // ᮺ
#define UC_SUNDANESE_REU                         0x1BBB 0  // ᮻ
#define UC_SUNDANESE_LEU                         0x1BBC 0  // ᮼ
#define UC_SUNDANESE_BHA                         0x1BBD 0  // ᮽ
#define UC_SUNDANESE_FINAL_K                     0x1BBE 0  // ᮾ
#define UC_SUNDANESE_FINAL_M                     0x1BBF 0  // ᮿ
