/* sunuwar.h – Unicode constants for U+11BC0 … U+11BFF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * The Sunuwar or Koinch are a Tibeto-Burman ethnic group ( Nepali
 * :सुनुवार जाति| Sunuwār Jāti ), a Kirati tribe native to Nepal , parts
 * of India ( West Bengal and Sikkim ) and southern Bhutan. They speak
 * the Sunuwar language . According to the 2001 census of Nepal, 17% of
 * the tribe follow the Kirant religion and adopt the Mundhum (Kiranti)
 * culture.
 * The Kõinchs (Sunuwar) number 82,705 in total. The term ‘Kõinchs’ is
 * also the name of the mother tongue. Other terms like Mukhiya or Mukhia
 * are exonyms of the tribe. Sunuwar have a distinct language, religion,
 * culture and social customs.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Sunuwar
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U11BC0.pdf
 
* Consistency Check:
* Total Defined Code Points: 44
* Total Significant Hex Values: 44
* Status: OK (Counts Match)

*/

#pragma once

#define UC_SUNUWAR_DEVI                          0x11BC0 0  // 𑯀
#define UC_SUNUWAR_TASLA                         0x11BC1 0  // 𑯁
#define UC_SUNUWAR_EKO                           0x11BC2 0  // 𑯂
#define UC_SUNUWAR_IMAR                          0x11BC3 0  // 𑯃
#define UC_SUNUWAR_REU                           0x11BC4 0  // 𑯄
#define UC_SUNUWAR_UTTHI                         0x11BC5 0  // 𑯅
#define UC_SUNUWAR_KIK                           0x11BC6 0  // 𑯆
#define UC_SUNUWAR_MA                            0x11BC7 0  // 𑯇
#define UC_SUNUWAR_APPHO                         0x11BC8 0  // 𑯈
#define UC_SUNUWAR_PIP                           0x11BC9 0  // 𑯉
#define UC_SUNUWAR_GIL                           0x11BCA 0  // 𑯊
#define UC_SUNUWAR_HAMSO                         0x11BCB 0  // 𑯋
#define UC_SUNUWAR_CARMI                         0x11BCC 0  // 𑯌
#define UC_SUNUWAR_NAH                           0x11BCD 0  // 𑯍
#define UC_SUNUWAR_BUR                           0x11BCE 0  // 𑯎
#define UC_SUNUWAR_JYAH                          0x11BCF 0  // 𑯏
#define UC_SUNUWAR_LOACHA                        0x11BD0 0  // 𑯐
#define UC_SUNUWAR_OTTHI                         0x11BD1 0  // 𑯑
#define UC_SUNUWAR_SHYELE                        0x11BD2 0  // 𑯒
#define UC_SUNUWAR_VARCA                         0x11BD3 0  // 𑯓
#define UC_SUNUWAR_YAT                           0x11BD4 0  // 𑯔
#define UC_SUNUWAR_AVA                           0x11BD5 0  // 𑯕
#define UC_SUNUWAR_AAL                           0x11BD6 0  // 𑯖
#define UC_SUNUWAR_DONGA                         0x11BD7 0  // 𑯗
#define UC_SUNUWAR_THARI                         0x11BD8 0  // 𑯘
#define UC_SUNUWAR_PHAR                          0x11BD9 0  // 𑯙
#define UC_SUNUWAR_NGAR                          0x11BDA 0  // 𑯚
#define UC_SUNUWAR_KHA                           0x11BDB 0  // 𑯛
#define UC_SUNUWAR_SHYER                         0x11BDC 0  // 𑯜
#define UC_SUNUWAR_CHELAP                        0x11BDD 0  // 𑯝
#define UC_SUNUWAR_TENTU                         0x11BDE 0  // 𑯞
#define UC_SUNUWAR_THELE                         0x11BDF 0  // 𑯟
#define UC_SUNUWAR_KLOKO                         0x11BE0 0  // 𑯠
#define UC_SUNUWAR_SIGN_PVO                      0x11BE1 0  // 𑯡
#define UC_SUNUWAR_ZERO                          0x11BF0 0  // 𑯰
#define UC_SUNUWAR_ONE                           0x11BF1 0  // 𑯱
#define UC_SUNUWAR_TWO                           0x11BF2 0  // 𑯲
#define UC_SUNUWAR_THREE                         0x11BF3 0  // 𑯳
#define UC_SUNUWAR_FOUR                          0x11BF4 0  // 𑯴
#define UC_SUNUWAR_FIVE                          0x11BF5 0  // 𑯵
#define UC_SUNUWAR_SIX                           0x11BF6 0  // 𑯶
#define UC_SUNUWAR_SEVEN                         0x11BF7 0  // 𑯷
#define UC_SUNUWAR_EIGHT                         0x11BF8 0  // 𑯸
#define UC_SUNUWAR_NINE                          0x11BF9 0  // 𑯹
