/* tai_viet.h – Unicode constants for U+AA80 … U+AADF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * The Tai Viet script ( Tai Dam : ꪎꪳ ꪼꪕ ("Tai script"), Vietnamese : Chữ
 * Thái Việt , Thai : อักษรไทดำ , RTGS : akson taidam ) is a Brahmic
 * script used by the Tai Dam people and various other Thai people in
 * Vietnam and Thailand .
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Tai_Viet
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/UAA80.pdf
 
* Consistency Check:
* Total Defined Code Points: 72
* Total Significant Hex Values: 72
* Status: OK (Counts Match)

*/

#pragma once

#define UC_TAI_VIET_LOW_KO                       0xAA80 0  // ꪀ
#define UC_TAI_VIET_HIGH_KO                      0xAA81 0  // ꪁ
#define UC_TAI_VIET_LOW_KHO                      0xAA82 0  // ꪂ
#define UC_TAI_VIET_HIGH_KHO                     0xAA83 0  // ꪃ
#define UC_TAI_VIET_LOW_KHHO                     0xAA84 0  // ꪄ
#define UC_TAI_VIET_HIGH_KHHO                    0xAA85 0  // ꪅ
#define UC_TAI_VIET_LOW_GO                       0xAA86 0  // ꪆ
#define UC_TAI_VIET_HIGH_GO                      0xAA87 0  // ꪇ
#define UC_TAI_VIET_LOW_NGO                      0xAA88 0  // ꪈ
#define UC_TAI_VIET_HIGH_NGO                     0xAA89 0  // ꪉ
#define UC_TAI_VIET_LOW_CO                       0xAA8A 0  // ꪊ
#define UC_TAI_VIET_HIGH_CO                      0xAA8B 0  // ꪋ
#define UC_TAI_VIET_LOW_CHO                      0xAA8C 0  // ꪌ
#define UC_TAI_VIET_HIGH_CHO                     0xAA8D 0  // ꪍ
#define UC_TAI_VIET_LOW_SO                       0xAA8E 0  // ꪎ
#define UC_TAI_VIET_HIGH_SO                      0xAA8F 0  // ꪏ
#define UC_TAI_VIET_LOW_NYO                      0xAA90 0  // ꪐ
#define UC_TAI_VIET_HIGH_NYO                     0xAA91 0  // ꪑ
#define UC_TAI_VIET_LOW_DO                       0xAA92 0  // ꪒ
#define UC_TAI_VIET_HIGH_DO                      0xAA93 0  // ꪓ
#define UC_TAI_VIET_LOW_TO                       0xAA94 0  // ꪔ
#define UC_TAI_VIET_HIGH_TO                      0xAA95 0  // ꪕ
#define UC_TAI_VIET_LOW_THO                      0xAA96 0  // ꪖ
#define UC_TAI_VIET_HIGH_THO                     0xAA97 0  // ꪗ
#define UC_TAI_VIET_LOW_NO                       0xAA98 0  // ꪘ
#define UC_TAI_VIET_HIGH_NO                      0xAA99 0  // ꪙ
#define UC_TAI_VIET_LOW_BO                       0xAA9A 0  // ꪚ
#define UC_TAI_VIET_HIGH_BO                      0xAA9B 0  // ꪛ
#define UC_TAI_VIET_LOW_PO                       0xAA9C 0  // ꪜ
#define UC_TAI_VIET_HIGH_PO                      0xAA9D 0  // ꪝ
#define UC_TAI_VIET_LOW_PHO                      0xAA9E 0  // ꪞ
#define UC_TAI_VIET_HIGH_PHO                     0xAA9F 0  // ꪟ
#define UC_TAI_VIET_LOW_FO                       0xAAA0 0  // ꪠ
#define UC_TAI_VIET_HIGH_FO                      0xAAA1 0  // ꪡ
#define UC_TAI_VIET_LOW_MO                       0xAAA2 0  // ꪢ
#define UC_TAI_VIET_HIGH_MO                      0xAAA3 0  // ꪣ
#define UC_TAI_VIET_LOW_YO                       0xAAA4 0  // ꪤ
#define UC_TAI_VIET_HIGH_YO                      0xAAA5 0  // ꪥ
#define UC_TAI_VIET_LOW_RO                       0xAAA6 0  // ꪦ
#define UC_TAI_VIET_HIGH_RO                      0xAAA7 0  // ꪧ
#define UC_TAI_VIET_LOW_LO                       0xAAA8 0  // ꪨ
#define UC_TAI_VIET_HIGH_LO                      0xAAA9 0  // ꪩ
#define UC_TAI_VIET_LOW_VO                       0xAAAA 0  // ꪪ
#define UC_TAI_VIET_HIGH_VO                      0xAAAB 0  // ꪫ
#define UC_TAI_VIET_LOW_HO                       0xAAAC 0  // ꪬ
#define UC_TAI_VIET_HIGH_HO                      0xAAAD 0  // ꪭ
#define UC_TAI_VIET_LOW_O                        0xAAAE 0  // ꪮ
#define UC_TAI_VIET_HIGH_O                       0xAAAF 0  // ꪯ
#define UC_TAI_VIET_MAI_KANG                     0xAAB0 0  // ꪰ
#define UC_TAI_VIET_VOWEL_AA                     0xAAB1 0  // ꪱ
#define UC_TAI_VIET_VOWEL_I                      0xAAB2 0  // ꪲ
#define UC_TAI_VIET_VOWEL_UE                     0xAAB3 0  // ꪳ
#define UC_TAI_VIET_VOWEL_U                      0xAAB4 0  // ꪴ
#define UC_TAI_VIET_VOWEL_E                      0xAAB5 0  // ꪵ
#define UC_TAI_VIET_VOWEL_O                      0xAAB6 0  // ꪶ
#define UC_TAI_VIET_MAI_KHIT                     0xAAB7 0  // ꪷ
#define UC_TAI_VIET_VOWEL_IA                     0xAAB8 0  // ꪸ
#define UC_TAI_VIET_VOWEL_UEA                    0xAAB9 0  // ꪹ
#define UC_TAI_VIET_VOWEL_UA                     0xAABA 0  // ꪺ
#define UC_TAI_VIET_VOWEL_AUE                    0xAABB 0  // ꪻ
#define UC_TAI_VIET_VOWEL_AY                     0xAABC 0  // ꪼ
#define UC_TAI_VIET_VOWEL_AN                     0xAABD 0  // ꪽ
#define UC_TAI_VIET_VOWEL_AM                     0xAABE 0  // ꪾ
#define UC_TAI_VIET_TONE_MAI_EK                  0xAABF 0  // ꪿
#define UC_TAI_VIET_TONE_MAI_NUENG               0xAAC0 0  // ꫀ
#define UC_TAI_VIET_TONE_MAI_THO                 0xAAC1 0  // ꫁
#define UC_TAI_VIET_TONE_MAI_SONG                0xAAC2 0  // ꫂ
#define UC_TAI_VIET_KON                          0xAADB 0  // ꫛ
#define UC_TAI_VIET_NUENG                        0xAADC 0  // ꫜ
#define UC_TAI_VIET_SAM                          0xAADD 0  // ꫝ
#define UC_TAI_VIET_HO_HOI                       0xAADE 0  // ꫞
#define UC_TAI_VIET_KOI_KOI                      0xAADF 0  // ꫟
