/* tangut_supplement.h – Unicode constants for U+18D00 … U+18D7F
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Tangut Supplement is a Unicode block containing characters from the
 * Tangut script , which was used for writing the Tangut language spoken
 * by the Tangut people in the Western Xia Empire, and in China during
 * the Yuan dynasty and early Ming dynasty . This block is a supplement
 * to the main Tangut block .
 * The Tangut Supplement block size was changed in Unicode version 14.0
 * to correct the erroneous block end point (version 13: 18D8F → version
 * 14.0: 18D7F ).
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Tangut_Supplement
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U18D00.pdf
 
* Consistency Check:
* Total Defined Code Points: 31
* Total Significant Hex Values: 31
* Status: OK (Counts Match)

*/

#pragma once

#define UC_LO_U18D00                             0x18D00 0  // 𘴀
#define UC_LO_U18D01                             0x18D01 0  // 𘴁
#define UC_LO_U18D02                             0x18D02 0  // 𘴂
#define UC_LO_U18D03                             0x18D03 0  // 𘴃
#define UC_LO_U18D04                             0x18D04 0  // 𘴄
#define UC_LO_U18D05                             0x18D05 0  // 𘴅
#define UC_LO_U18D06                             0x18D06 0  // 𘴆
#define UC_LO_U18D07                             0x18D07 0  // 𘴇
#define UC_LO_U18D08                             0x18D08 0  // 𘴈
#define UC_LO_U18D09                             0x18D09 0  // 𘴉
#define UC_LO_U18D0A                             0x18D0A 0  // 𘴊
#define UC_LO_U18D0B                             0x18D0B 0  // 𘴋
#define UC_LO_U18D0C                             0x18D0C 0  // 𘴌
#define UC_LO_U18D0D                             0x18D0D 0  // 𘴍
#define UC_LO_U18D0E                             0x18D0E 0  // 𘴎
#define UC_LO_U18D0F                             0x18D0F 0  // 𘴏
#define UC_LO_U18D10                             0x18D10 0  // 𘴐
#define UC_LO_U18D11                             0x18D11 0  // 𘴑
#define UC_LO_U18D12                             0x18D12 0  // 𘴒
#define UC_LO_U18D13                             0x18D13 0  // 𘴓
#define UC_LO_U18D14                             0x18D14 0  // 𘴔
#define UC_LO_U18D15                             0x18D15 0  // 𘴕
#define UC_LO_U18D16                             0x18D16 0  // 𘴖
#define UC_LO_U18D17                             0x18D17 0  // 𘴗
#define UC_LO_U18D18                             0x18D18 0  // 𘴘
#define UC_LO_U18D19                             0x18D19 0  // 𘴙
#define UC_LO_U18D1A                             0x18D1A 0  // 𘴚
#define UC_LO_U18D1B                             0x18D1B 0  // 𘴛
#define UC_LO_U18D1C                             0x18D1C 0  // 𘴜
#define UC_LO_U18D1D                             0x18D1D 0  // 𘴝
#define UC_LO_U18D1E                             0x18D1E 0  // 𘴞
