/* tangut_components_supplement.h – Unicode constants for U+18D80 … U+18DFF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Tangut Components Supplement is a Unicode block containing additional
 * components used in the study of Tangut script . It supplements the
 * Tangut Components Unicode block.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Tangut_Components_Supplement
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U18D80.pdf
 
* Consistency Check:
* Total Defined Code Points: 115
* Total Significant Hex Values: 115
* Status: OK (Counts Match)

*/

#pragma once

#define UC_TANGUT_COMPONENT_769                  0x18D80 0  // 𘶀
#define UC_TANGUT_COMPONENT_770                  0x18D81 0  // 𘶁
#define UC_TANGUT_COMPONENT_771                  0x18D82 0  // 𘶂
#define UC_TANGUT_COMPONENT_772                  0x18D83 0  // 𘶃
#define UC_TANGUT_COMPONENT_773                  0x18D84 0  // 𘶄
#define UC_TANGUT_COMPONENT_774                  0x18D85 0  // 𘶅
#define UC_TANGUT_COMPONENT_775                  0x18D86 0  // 𘶆
#define UC_TANGUT_COMPONENT_776                  0x18D87 0  // 𘶇
#define UC_TANGUT_COMPONENT_777                  0x18D88 0  // 𘶈
#define UC_TANGUT_COMPONENT_778                  0x18D89 0  // 𘶉
#define UC_TANGUT_COMPONENT_779                  0x18D8A 0  // 𘶊
#define UC_TANGUT_COMPONENT_780                  0x18D8B 0  // 𘶋
#define UC_TANGUT_COMPONENT_781                  0x18D8C 0  // 𘶌
#define UC_TANGUT_COMPONENT_782                  0x18D8D 0  // 𘶍
#define UC_TANGUT_COMPONENT_783                  0x18D8E 0  // 𘶎
#define UC_TANGUT_COMPONENT_784                  0x18D8F 0  // 𘶏
#define UC_TANGUT_COMPONENT_785                  0x18D90 0  // 𘶐
#define UC_TANGUT_COMPONENT_786                  0x18D91 0  // 𘶑
#define UC_TANGUT_COMPONENT_787                  0x18D92 0  // 𘶒
#define UC_TANGUT_COMPONENT_788                  0x18D93 0  // 𘶓
#define UC_TANGUT_COMPONENT_789                  0x18D94 0  // 𘶔
#define UC_TANGUT_COMPONENT_790                  0x18D95 0  // 𘶕
#define UC_TANGUT_COMPONENT_791                  0x18D96 0  // 𘶖
#define UC_TANGUT_COMPONENT_792                  0x18D97 0  // 𘶗
#define UC_TANGUT_COMPONENT_793                  0x18D98 0  // 𘶘
#define UC_TANGUT_COMPONENT_794                  0x18D99 0  // 𘶙
#define UC_TANGUT_COMPONENT_795                  0x18D9A 0  // 𘶚
#define UC_TANGUT_COMPONENT_796                  0x18D9B 0  // 𘶛
#define UC_TANGUT_COMPONENT_797                  0x18D9C 0  // 𘶜
#define UC_TANGUT_COMPONENT_798                  0x18D9D 0  // 𘶝
#define UC_TANGUT_COMPONENT_799                  0x18D9E 0  // 𘶞
#define UC_TANGUT_COMPONENT_800                  0x18D9F 0  // 𘶟
#define UC_TANGUT_COMPONENT_801                  0x18DA0 0  // 𘶠
#define UC_TANGUT_COMPONENT_802                  0x18DA1 0  // 𘶡
#define UC_TANGUT_COMPONENT_803                  0x18DA2 0  // 𘶢
#define UC_TANGUT_COMPONENT_804                  0x18DA3 0  // 𘶣
#define UC_TANGUT_COMPONENT_805                  0x18DA4 0  // 𘶤
#define UC_TANGUT_COMPONENT_806                  0x18DA5 0  // 𘶥
#define UC_TANGUT_COMPONENT_807                  0x18DA6 0  // 𘶦
#define UC_TANGUT_COMPONENT_808                  0x18DA7 0  // 𘶧
#define UC_TANGUT_COMPONENT_809                  0x18DA8 0  // 𘶨
#define UC_TANGUT_COMPONENT_810                  0x18DA9 0  // 𘶩
#define UC_TANGUT_COMPONENT_811                  0x18DAA 0  // 𘶪
#define UC_TANGUT_COMPONENT_812                  0x18DAB 0  // 𘶫
#define UC_TANGUT_COMPONENT_813                  0x18DAC 0  // 𘶬
#define UC_TANGUT_COMPONENT_814                  0x18DAD 0  // 𘶭
#define UC_TANGUT_COMPONENT_815                  0x18DAE 0  // 𘶮
#define UC_TANGUT_COMPONENT_816                  0x18DAF 0  // 𘶯
#define UC_TANGUT_COMPONENT_817                  0x18DB0 0  // 𘶰
#define UC_TANGUT_COMPONENT_818                  0x18DB1 0  // 𘶱
#define UC_TANGUT_COMPONENT_819                  0x18DB2 0  // 𘶲
#define UC_TANGUT_COMPONENT_820                  0x18DB3 0  // 𘶳
#define UC_TANGUT_COMPONENT_821                  0x18DB4 0  // 𘶴
#define UC_TANGUT_COMPONENT_822                  0x18DB5 0  // 𘶵
#define UC_TANGUT_COMPONENT_823                  0x18DB6 0  // 𘶶
#define UC_TANGUT_COMPONENT_824                  0x18DB7 0  // 𘶷
#define UC_TANGUT_COMPONENT_825                  0x18DB8 0  // 𘶸
#define UC_TANGUT_COMPONENT_826                  0x18DB9 0  // 𘶹
#define UC_TANGUT_COMPONENT_827                  0x18DBA 0  // 𘶺
#define UC_TANGUT_COMPONENT_828                  0x18DBB 0  // 𘶻
#define UC_TANGUT_COMPONENT_829                  0x18DBC 0  // 𘶼
#define UC_TANGUT_COMPONENT_830                  0x18DBD 0  // 𘶽
#define UC_TANGUT_COMPONENT_831                  0x18DBE 0  // 𘶾
#define UC_TANGUT_COMPONENT_832                  0x18DBF 0  // 𘶿
#define UC_TANGUT_COMPONENT_833                  0x18DC0 0  // 𘷀
#define UC_TANGUT_COMPONENT_834                  0x18DC1 0  // 𘷁
#define UC_TANGUT_COMPONENT_835                  0x18DC2 0  // 𘷂
#define UC_TANGUT_COMPONENT_836                  0x18DC3 0  // 𘷃
#define UC_TANGUT_COMPONENT_837                  0x18DC4 0  // 𘷄
#define UC_TANGUT_COMPONENT_838                  0x18DC5 0  // 𘷅
#define UC_TANGUT_COMPONENT_839                  0x18DC6 0  // 𘷆
#define UC_TANGUT_COMPONENT_840                  0x18DC7 0  // 𘷇
#define UC_TANGUT_COMPONENT_841                  0x18DC8 0  // 𘷈
#define UC_TANGUT_COMPONENT_842                  0x18DC9 0  // 𘷉
#define UC_TANGUT_COMPONENT_843                  0x18DCA 0  // 𘷊
#define UC_TANGUT_COMPONENT_844                  0x18DCB 0  // 𘷋
#define UC_TANGUT_COMPONENT_845                  0x18DCC 0  // 𘷌
#define UC_TANGUT_COMPONENT_846                  0x18DCD 0  // 𘷍
#define UC_TANGUT_COMPONENT_847                  0x18DCE 0  // 𘷎
#define UC_TANGUT_COMPONENT_848                  0x18DCF 0  // 𘷏
#define UC_TANGUT_COMPONENT_849                  0x18DD0 0  // 𘷐
#define UC_TANGUT_COMPONENT_850                  0x18DD1 0  // 𘷑
#define UC_TANGUT_COMPONENT_851                  0x18DD2 0  // 𘷒
#define UC_TANGUT_COMPONENT_852                  0x18DD3 0  // 𘷓
#define UC_TANGUT_COMPONENT_853                  0x18DD4 0  // 𘷔
#define UC_TANGUT_COMPONENT_854                  0x18DD5 0  // 𘷕
#define UC_TANGUT_COMPONENT_855                  0x18DD6 0  // 𘷖
#define UC_TANGUT_COMPONENT_856                  0x18DD7 0  // 𘷗
#define UC_TANGUT_COMPONENT_857                  0x18DD8 0  // 𘷘
#define UC_TANGUT_COMPONENT_858                  0x18DD9 0  // 𘷙
#define UC_TANGUT_COMPONENT_859                  0x18DDA 0  // 𘷚
#define UC_TANGUT_COMPONENT_860                  0x18DDB 0  // 𘷛
#define UC_TANGUT_COMPONENT_861                  0x18DDC 0  // 𘷜
#define UC_TANGUT_COMPONENT_862                  0x18DDD 0  // 𘷝
#define UC_TANGUT_COMPONENT_863                  0x18DDE 0  // 𘷞
#define UC_TANGUT_COMPONENT_864                  0x18DDF 0  // 𘷟
#define UC_TANGUT_COMPONENT_865                  0x18DE0 0  // 𘷠
#define UC_TANGUT_COMPONENT_866                  0x18DE1 0  // 𘷡
#define UC_TANGUT_COMPONENT_867                  0x18DE2 0  // 𘷢
#define UC_TANGUT_COMPONENT_868                  0x18DE3 0  // 𘷣
#define UC_TANGUT_COMPONENT_869                  0x18DE4 0  // 𘷤
#define UC_TANGUT_COMPONENT_870                  0x18DE5 0  // 𘷥
#define UC_TANGUT_COMPONENT_871                  0x18DE6 0  // 𘷦
#define UC_TANGUT_COMPONENT_872                  0x18DE7 0  // 𘷧
#define UC_TANGUT_COMPONENT_873                  0x18DE8 0  // 𘷨
#define UC_TANGUT_COMPONENT_874                  0x18DE9 0  // 𘷩
#define UC_TANGUT_COMPONENT_875                  0x18DEA 0  // 𘷪
#define UC_TANGUT_COMPONENT_876                  0x18DEB 0  // 𘷫
#define UC_TANGUT_COMPONENT_877                  0x18DEC 0  // 𘷬
#define UC_TANGUT_COMPONENT_878                  0x18DED 0  // 𘷭
#define UC_TANGUT_COMPONENT_879                  0x18DEE 0  // 𘷮
#define UC_TANGUT_COMPONENT_880                  0x18DEF 0  // 𘷯
#define UC_TANGUT_COMPONENT_881                  0x18DF0 0  // 𘷰
#define UC_TANGUT_COMPONENT_882                  0x18DF1 0  // 𘷱
#define UC_TANGUT_COMPONENT_883                  0x18DF2 0  // 𘷲
