/* todhri.h – Unicode constants for U+105C0 … U+105FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * The Todhri alphabet is an 18th-century Albanian alphabetical writing
 * system invented for writing the Albanian language by Theodhor
 * Haxhifilipi , also known as Dhaskal Todhri.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Todhri
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U105C0.pdf
 
* Consistency Check:
* Total Defined Code Points: 52
* Total Significant Hex Values: 52
* Status: OK (Counts Match)

*/

#pragma once

#define UC_TODHRI_A                              0x105C0 0  // 𐗀
#define UC_TODHRI_AS                             0x105C1 0  // 𐗁
#define UC_TODHRI_BA                             0x105C2 0  // 𐗂
#define UC_TODHRI_MBA                            0x105C3 0  // 𐗃
#define UC_TODHRI_CA                             0x105C4 0  // 𐗄
#define UC_TODHRI_CHA                            0x105C5 0  // 𐗅
#define UC_TODHRI_DA                             0x105C6 0  // 𐗆
#define UC_TODHRI_NDA                            0x105C7 0  // 𐗇
#define UC_TODHRI_DHA                            0x105C8 0  // 𐗈
#define UC_TODHRI_EI                             0x105C9 0  // 𐗉
#define UC_TODHRI_E                              0x105CA 0  // 𐗊
#define UC_TODHRI_FA                             0x105CB 0  // 𐗋
#define UC_TODHRI_GA                             0x105CC 0  // 𐗌
#define UC_TODHRI_NGA                            0x105CD 0  // 𐗍
#define UC_TODHRI_GJA                            0x105CE 0  // 𐗎
#define UC_TODHRI_NGJA                           0x105CF 0  // 𐗏
#define UC_TODHRI_HA                             0x105D0 0  // 𐗐
#define UC_TODHRI_HJA                            0x105D1 0  // 𐗑
#define UC_TODHRI_I                              0x105D2 0  // 𐗒
#define UC_TODHRI_JA                             0x105D3 0  // 𐗓
#define UC_TODHRI_KA                             0x105D4 0  // 𐗔
#define UC_TODHRI_LA                             0x105D5 0  // 𐗕
#define UC_TODHRI_LLA                            0x105D6 0  // 𐗖
#define UC_TODHRI_MA                             0x105D7 0  // 𐗗
#define UC_TODHRI_NA                             0x105D8 0  // 𐗘
#define UC_TODHRI_NJAN                           0x105D9 0  // 𐗙
#define UC_TODHRI_O                              0x105DA 0  // 𐗚
#define UC_TODHRI_PA                             0x105DB 0  // 𐗛
#define UC_TODHRI_QA                             0x105DC 0  // 𐗜
#define UC_TODHRI_RA                             0x105DD 0  // 𐗝
#define UC_TODHRI_RRA                            0x105DE 0  // 𐗞
#define UC_TODHRI_SA                             0x105DF 0  // 𐗟
#define UC_TODHRI_SHA                            0x105E0 0  // 𐗠
#define UC_TODHRI_SHTA                           0x105E1 0  // 𐗡
#define UC_TODHRI_TA                             0x105E2 0  // 𐗢
#define UC_TODHRI_THA                            0x105E3 0  // 𐗣
#define UC_TODHRI_U                              0x105E4 0  // 𐗤
#define UC_TODHRI_VA                             0x105E5 0  // 𐗥
#define UC_TODHRI_XA                             0x105E6 0  // 𐗦
#define UC_TODHRI_NXA                            0x105E7 0  // 𐗧
#define UC_TODHRI_XHA                            0x105E8 0  // 𐗨
#define UC_TODHRI_NXHA                           0x105E9 0  // 𐗩
#define UC_TODHRI_Y                              0x105EA 0  // 𐗪
#define UC_TODHRI_JY                             0x105EB 0  // 𐗫
#define UC_TODHRI_ZA                             0x105EC 0  // 𐗬
#define UC_TODHRI_ZHA                            0x105ED 0  // 𐗭
#define UC_TODHRI_GHA                            0x105EE 0  // 𐗮
#define UC_TODHRI_STA                            0x105EF 0  // 𐗯
#define UC_TODHRI_SKAN                           0x105F0 0  // 𐗰
#define UC_TODHRI_KHA                            0x105F1 0  // 𐗱
#define UC_TODHRI_PSA                            0x105F2 0  // 𐗲
#define UC_TODHRI_OO                             0x105F3 0  // 𐗳
