/* vedic_extensions.h – Unicode constants for U+1CD0 … U+1CFF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Vedic Extensions is a Unicode block containing characters for
 * representing tones and other vedic symbols in Devanagari and other
 * Indic scripts. Related symbols (also used in many scripts to represent
 * vedic accents) are defined in two other blocks: Devanagari
 * (U+0900–U+097F) and Devanagari Extended (U+A8E0–U+A8FF).
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Vedic_Extensions
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1CD0.pdf
 
* Consistency Check:
* Total Defined Code Points: 43
* Total Significant Hex Values: 43
* Status: OK (Counts Match)

*/

#pragma once

#define UC_VEDIC_TONE_KARSHANA                   0x1CD0 0  // ᳐
#define UC_VEDIC_TONE_SHARA                      0x1CD1 0  // ᳑
#define UC_VEDIC_TONE_PRENKHA                    0x1CD2 0  // ᳒
#define UC_VEDIC_SIGN_NIHSHVASA                  0x1CD3 0  // ᳓
#define UC_VEDIC_SIGN_YAJURVEDIC_MIDLINE_SVARITA 0x1CD4 0  // ᳔
#define UC_VEDIC_TONE_YAJURVEDIC_AGGRAVATED_INDEPENDENT_SVARITA 0x1CD5 0  // ᳕
#define UC_VEDIC_TONE_YAJURVEDIC_INDEPENDENT_SVARITA 0x1CD6 0  // ᳖
#define UC_VEDIC_TONE_YAJURVEDIC_KATHAKA_INDEPENDENT_SVARITA 0x1CD7 0  // ᳗
#define UC_VEDIC_TONE_CANDRA_BELOW               0x1CD8 0  // ᳘
#define UC_VEDIC_TONE_YAJURVEDIC_KATHAKA_INDEPENDENT_SVARITA_SCHROEDER 0x1CD9 0  // ᳙
#define UC_VEDIC_TONE_DOUBLE_SVARITA             0x1CDA 0  // ᳚
#define UC_VEDIC_TONE_TRIPLE_SVARITA             0x1CDB 0  // ᳛
#define UC_VEDIC_TONE_KATHAKA_ANUDATTA           0x1CDC 0  // ᳜
#define UC_VEDIC_TONE_DOT_BELOW                  0x1CDD 0  // ᳝
#define UC_VEDIC_TONE_TWO_DOTS_BELOW             0x1CDE 0  // ᳞
#define UC_VEDIC_TONE_THREE_DOTS_BELOW           0x1CDF 0  // ᳟
#define UC_VEDIC_TONE_RIGVEDIC_KASHMIRI_INDEPENDENT_SVARITA 0x1CE0 0  // ᳠
#define UC_VEDIC_TONE_ATHARVAVEDIC_INDEPENDENT_SVARITA 0x1CE1 0  // ᳡
#define UC_VEDIC_SIGN_VISARGA_SVARITA            0x1CE2 0  // ᳢
#define UC_VEDIC_SIGN_VISARGA_UDATTA             0x1CE3 0  // ᳣
#define UC_VEDIC_SIGN_REVERSED_VISARGA_UDATTA    0x1CE4 0  // ᳤
#define UC_VEDIC_SIGN_VISARGA_ANUDATTA           0x1CE5 0  // ᳥
#define UC_VEDIC_SIGN_REVERSED_VISARGA_ANUDATTA  0x1CE6 0  // ᳦
#define UC_VEDIC_SIGN_VISARGA_UDATTA_TAIL        0x1CE7 0  // ᳧
#define UC_VEDIC_SIGN_VISARGA_ANUDATTA_TAIL      0x1CE8 0  // ᳨
#define UC_VEDIC_SIGN_ANUSVARA_ANTARGOMUKHA      0x1CE9 0  // ᳩ
#define UC_VEDIC_SIGN_ANUSVARA_BAHIRGOMUKHA      0x1CEA 0  // ᳪ
#define UC_VEDIC_SIGN_ANUSVARA_VAMAGOMUKHA       0x1CEB 0  // ᳫ
#define UC_VEDIC_SIGN_ANUSVARA_VAMAGOMUKHA_TAIL  0x1CEC 0  // ᳬ
#define UC_VEDIC_SIGN_TIRYAK                     0x1CED 0  // ᳭
#define UC_VEDIC_SIGN_HEXIFORM_LONG_ANUSVARA     0x1CEE 0  // ᳮ
#define UC_VEDIC_SIGN_LONG_ANUSVARA              0x1CEF 0  // ᳯ
#define UC_VEDIC_SIGN_RTHANG_LONG_ANUSVARA       0x1CF0 0  // ᳰ
#define UC_VEDIC_SIGN_ANUSVARA_UBHAYATO_MUKHA    0x1CF1 0  // ᳱ
#define UC_VEDIC_SIGN_ARDHAVISARGA               0x1CF2 0  // ᳲ
#define UC_VEDIC_SIGN_ROTATED_ARDHAVISARGA       0x1CF3 0  // ᳳ
#define UC_VEDIC_TONE_CANDRA_ABOVE               0x1CF4 0  // ᳴
#define UC_VEDIC_SIGN_JIHVAMULIYA                0x1CF5 0  // ᳵ
#define UC_VEDIC_SIGN_UPADHMANIYA                0x1CF6 0  // ᳶ
#define UC_VEDIC_SIGN_ATIKRAMA                   0x1CF7 0  // ᳷
#define UC_VEDIC_TONE_RING_ABOVE                 0x1CF8 0  // ᳸
#define UC_VEDIC_TONE_DOUBLE_RING_ABOVE          0x1CF9 0  // ᳹
#define UC_VEDIC_SIGN_DOUBLE_ANUSVARA_ANTARGOMUKHA 0x1CFA 0  // ᳺ
