/* wancho.h – Unicode constants for U+1E2C0 … U+1E2FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Wancho may refer to:
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Wancho
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U1E2C0.pdf
 
* Consistency Check:
* Total Defined Code Points: 59
* Total Significant Hex Values: 59
* Status: OK (Counts Match)

*/

#pragma once

#define UC_WANCHO_AA                             0x1E2C0 0  // 𞋀
#define UC_WANCHO_A                              0x1E2C1 0  // 𞋁
#define UC_WANCHO_BA                             0x1E2C2 0  // 𞋂
#define UC_WANCHO_CA                             0x1E2C3 0  // 𞋃
#define UC_WANCHO_DA                             0x1E2C4 0  // 𞋄
#define UC_WANCHO_GA                             0x1E2C5 0  // 𞋅
#define UC_WANCHO_YA                             0x1E2C6 0  // 𞋆
#define UC_WANCHO_PHA                            0x1E2C7 0  // 𞋇
#define UC_WANCHO_LA                             0x1E2C8 0  // 𞋈
#define UC_WANCHO_NA                             0x1E2C9 0  // 𞋉
#define UC_WANCHO_PA                             0x1E2CA 0  // 𞋊
#define UC_WANCHO_TA                             0x1E2CB 0  // 𞋋
#define UC_WANCHO_THA                            0x1E2CC 0  // 𞋌
#define UC_WANCHO_FA                             0x1E2CD 0  // 𞋍
#define UC_WANCHO_SA                             0x1E2CE 0  // 𞋎
#define UC_WANCHO_SHA                            0x1E2CF 0  // 𞋏
#define UC_WANCHO_JA                             0x1E2D0 0  // 𞋐
#define UC_WANCHO_ZA                             0x1E2D1 0  // 𞋑
#define UC_WANCHO_WA                             0x1E2D2 0  // 𞋒
#define UC_WANCHO_VA                             0x1E2D3 0  // 𞋓
#define UC_WANCHO_KA                             0x1E2D4 0  // 𞋔
#define UC_WANCHO_O                              0x1E2D5 0  // 𞋕
#define UC_WANCHO_AU                             0x1E2D6 0  // 𞋖
#define UC_WANCHO_RA                             0x1E2D7 0  // 𞋗
#define UC_WANCHO_MA                             0x1E2D8 0  // 𞋘
#define UC_WANCHO_KHA                            0x1E2D9 0  // 𞋙
#define UC_WANCHO_HA                             0x1E2DA 0  // 𞋚
#define UC_WANCHO_E                              0x1E2DB 0  // 𞋛
#define UC_WANCHO_I                              0x1E2DC 0  // 𞋜
#define UC_WANCHO_NGA                            0x1E2DD 0  // 𞋝
#define UC_WANCHO_U                              0x1E2DE 0  // 𞋞
#define UC_WANCHO_LLHA                           0x1E2DF 0  // 𞋟
#define UC_WANCHO_TSA                            0x1E2E0 0  // 𞋠
#define UC_WANCHO_TRA                            0x1E2E1 0  // 𞋡
#define UC_WANCHO_ONG                            0x1E2E2 0  // 𞋢
#define UC_WANCHO_AANG                           0x1E2E3 0  // 𞋣
#define UC_WANCHO_ANG                            0x1E2E4 0  // 𞋤
#define UC_WANCHO_ING                            0x1E2E5 0  // 𞋥
#define UC_WANCHO_ON                             0x1E2E6 0  // 𞋦
#define UC_WANCHO_EN                             0x1E2E7 0  // 𞋧
#define UC_WANCHO_AAN                            0x1E2E8 0  // 𞋨
#define UC_WANCHO_NYA                            0x1E2E9 0  // 𞋩
#define UC_WANCHO_UEN                            0x1E2EA 0  // 𞋪
#define UC_WANCHO_YIH                            0x1E2EB 0  // 𞋫
#define UC_WANCHO_TONE_TUP                       0x1E2EC 0  // 𞋬
#define UC_WANCHO_TONE_TUPNI                     0x1E2ED 0  // 𞋭
#define UC_WANCHO_TONE_KOI                       0x1E2EE 0  // 𞋮
#define UC_WANCHO_TONE_KOINI                     0x1E2EF 0  // 𞋯
#define UC_WANCHO_ZERO                           0x1E2F0 0  // 𞋰
#define UC_WANCHO_ONE                            0x1E2F1 0  // 𞋱
#define UC_WANCHO_TWO                            0x1E2F2 0  // 𞋲
#define UC_WANCHO_THREE                          0x1E2F3 0  // 𞋳
#define UC_WANCHO_FOUR                           0x1E2F4 0  // 𞋴
#define UC_WANCHO_FIVE                           0x1E2F5 0  // 𞋵
#define UC_WANCHO_SIX                            0x1E2F6 0  // 𞋶
#define UC_WANCHO_SEVEN                          0x1E2F7 0  // 𞋷
#define UC_WANCHO_EIGHT                          0x1E2F8 0  // 𞋸
#define UC_WANCHO_NINE                           0x1E2F9 0  // 𞋹
#define UC_WANCHO_NGUN_SIGN                      0x1E2FF 0  // 𞋿
