/* warang_citi.h – Unicode constants for U+118A0 … U+118FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 * Generated by generate_unicode_headers.py
 * Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
 * Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
 *
 * See https://www.unicode.org/versions/latest/ for source data.

 *
 * Block Description:
 * Warang Chiti (also written Varang Kshiti ; Ho : 𑢹𑣗𑣁𑣜𑣊 𑣏𑣂𑣕𑣂 ‎ , IPA:
 * /wɐrɐŋ ʧɪt̪ɪ/) is a writing system invented by Lako Bodra for the Ho
 * language spoken in East India . It is used in primary and adult
 * education and in various publications.
 * It has mainly gained acceptance among the easternmost group of
 * speakers, and is more prevalent among those who have been educated in
 * it. Many other speakers prefer oral transmission of knowledge ,
 * Devanagari , or Latin , but Warang Chiti holds prestige among many Ho
 * speakers.
 *
 * Wikipedia: https://en.wikipedia.org/wiki/Warang_Citi
 *
 * Unicode Charts: https://www.unicode.org/charts/PDF/U118A0.pdf
 
* Consistency Check:
* Total Defined Code Points: 84
* Total Significant Hex Values: 84
* Status: OK (Counts Match)

*/

#pragma once

#define UC_WARANG_CITI_NGAA                      0x118C0 0x118A0  // 𑣀/𑢠
#define UC_WARANG_CITI_A                         0x118C1 0x118A1  // 𑣁/𑢡
#define UC_WARANG_CITI_WI                        0x118C2 0x118A2  // 𑣂/𑢢
#define UC_WARANG_CITI_YU                        0x118C3 0x118A3  // 𑣃/𑢣
#define UC_WARANG_CITI_YA                        0x118C4 0x118A4  // 𑣄/𑢤
#define UC_WARANG_CITI_YO                        0x118C5 0x118A5  // 𑣅/𑢥
#define UC_WARANG_CITI_II                        0x118C6 0x118A6  // 𑣆/𑢦
#define UC_WARANG_CITI_UU                        0x118C7 0x118A7  // 𑣇/𑢧
#define UC_WARANG_CITI_E                         0x118C8 0x118A8  // 𑣈/𑢨
#define UC_WARANG_CITI_O                         0x118C9 0x118A9  // 𑣉/𑢩
#define UC_WARANG_CITI_ANG                       0x118CA 0x118AA  // 𑣊/𑢪
#define UC_WARANG_CITI_GA                        0x118CB 0x118AB  // 𑣋/𑢫
#define UC_WARANG_CITI_KO                        0x118CC 0x118AC  // 𑣌/𑢬
#define UC_WARANG_CITI_ENY                       0x118CD 0x118AD  // 𑣍/𑢭
#define UC_WARANG_CITI_YUJ                       0x118CE 0x118AE  // 𑣎/𑢮
#define UC_WARANG_CITI_UC                        0x118CF 0x118AF  // 𑣏/𑢯
#define UC_WARANG_CITI_ENN                       0x118D0 0x118B0  // 𑣐/𑢰
#define UC_WARANG_CITI_ODD                       0x118D1 0x118B1  // 𑣑/𑢱
#define UC_WARANG_CITI_TTE                       0x118D2 0x118B2  // 𑣒/𑢲
#define UC_WARANG_CITI_NUNG                      0x118D3 0x118B3  // 𑣓/𑢳
#define UC_WARANG_CITI_DA                        0x118D4 0x118B4  // 𑣔/𑢴
#define UC_WARANG_CITI_AT                        0x118D5 0x118B5  // 𑣕/𑢵
#define UC_WARANG_CITI_AM                        0x118D6 0x118B6  // 𑣖/𑢶
#define UC_WARANG_CITI_BU                        0x118D7 0x118B7  // 𑣗/𑢷
#define UC_WARANG_CITI_PU                        0x118D8 0x118B8  // 𑣘/𑢸
#define UC_WARANG_CITI_HIYO                      0x118D9 0x118B9  // 𑣙/𑢹
#define UC_WARANG_CITI_HOLO                      0x118DA 0x118BA  // 𑣚/𑢺
#define UC_WARANG_CITI_HORR                      0x118DB 0x118BB  // 𑣛/𑢻
#define UC_WARANG_CITI_HAR                       0x118DC 0x118BC  // 𑣜/𑢼
#define UC_WARANG_CITI_SSUU                      0x118DD 0x118BD  // 𑣝/𑢽
#define UC_WARANG_CITI_SII                       0x118DE 0x118BE  // 𑣞/𑢾
#define UC_WARANG_CITI_VIYO                      0x118DF 0x118BF  // 𑣟/𑢿
#define UC_WARANG_CITI_ZERO                      0x118E0 0  // 𑣠
#define UC_WARANG_CITI_ONE                       0x118E1 0  // 𑣡
#define UC_WARANG_CITI_TWO                       0x118E2 0  // 𑣢
#define UC_WARANG_CITI_THREE                     0x118E3 0  // 𑣣
#define UC_WARANG_CITI_FOUR                      0x118E4 0  // 𑣤
#define UC_WARANG_CITI_FIVE                      0x118E5 0  // 𑣥
#define UC_WARANG_CITI_SIX                       0x118E6 0  // 𑣦
#define UC_WARANG_CITI_SEVEN                     0x118E7 0  // 𑣧
#define UC_WARANG_CITI_EIGHT                     0x118E8 0  // 𑣨
#define UC_WARANG_CITI_NINE                      0x118E9 0  // 𑣩
#define UC_WARANG_CITI_TEN                       0x118EA 0  // 𑣪
#define UC_WARANG_CITI_TWENTY                    0x118EB 0  // 𑣫
#define UC_WARANG_CITI_THIRTY                    0x118EC 0  // 𑣬
#define UC_WARANG_CITI_FORTY                     0x118ED 0  // 𑣭
#define UC_WARANG_CITI_FIFTY                     0x118EE 0  // 𑣮
#define UC_WARANG_CITI_SIXTY                     0x118EF 0  // 𑣯
#define UC_WARANG_CITI_SEVENTY                   0x118F0 0  // 𑣰
#define UC_WARANG_CITI_EIGHTY                    0x118F1 0  // 𑣱
#define UC_WARANG_CITI_NINETY                    0x118F2 0  // 𑣲
#define UC_WARANG_CITI_OM                        0x118FF 0  // 𑣿
