# Go to sleep after one hour (1*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Turn on logging, and set ZMK logging to debug output
#CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
# Enable receipt of HID/LED indicator state from the host
CONFIG_ZMK_HID_INDICATORS=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

CONFIG_ZMK_LEADER_MAX_SEQUENCES=750

CONFIG_ZMK_UNICODE_TAP_MS=8
CONFIG_ZMK_UNICODE_WAIT_MS=3

# Optional: Enhance E-ink refresh for indicator updates
CONFIG_ZMK_DISPLAY_FULL_REFRESH_PERIOD=300
